### ISSUE TITLE
Support serializing a char as a map key

### ISSUE THREAD

**Issue by dhardy** [toml-lang/toml#1001]
When attempting to use an untagged enum over a `char` as a map key while serializing to TOML I see this error: `map key was not a string`.

Writing my own serializer which uses `char::encode_utf8` lets me work around this, but I think TOML should directly support a `char` as a map key?

Deserializing does not require any workarounds. Edit: this might just be a side-effect of my untagged enum format.

**Comment by arp242** [comment]
This repo is for the TOML specification; you'll want to ask your question to the people maintaining the specific implementation you're using.

**Comment by dhardy** [comment]
Okay... why does the [toml-rs crate](https://crates.io/crates/toml) link here?
