### ISSUE TITLE
Grammar appears to allow character forbidden by docs

### ISSUE THREAD

**Issue by Lucretiel** [toml-lang/toml#1013]
https://github.com/toml-lang/toml/blob/8eae5e1c005bc5836098505f85a7aa06568999dd/toml.abnf#L39

The grammar for valid comment characters includes the class `U+0020 - U+007F`. The docs, however, [forbid](https://toml.io/en/v1.0.0#comment) the use of `U+007F` in comments.

**Comment by eksortso** [comment]
You're comparing different versions of the standard.

If you look at the current version:
* https://github.com/toml-lang/toml/blob/main/toml.md

and the current ABNF:
* https://github.com/toml-lang/toml/blob/main/toml.md

you will see that `%7f` is now allowed in comments.

This was a change that we made explicit in #924. It could be reverted if we merged #996, which I'm personally opposed to doing. So keep an eye out for this. By the time v1.1.0rc1 is released, this matter will be resolved, one way or another.

This could change before the first release candidate of v1.1.0, though, depending on whether we revert the more permissive set of comment characters per #996.

**Comment by Lucretiel** [comment]
Am I? I'm comparing the [specification 1.0.0](https://toml.io/en/v1.0.0):

> Control characters other than tab (U+0000 to U+0008, U+000A to U+001F, U+007F) are not permitted in comments.

To the [grammar tagged 1.0.0](https://github.com/toml-lang/toml/blob/1.0.0/toml.abnf)

> https://github.com/toml-lang/toml/blob/8eae5e1c005bc5836098505f85a7aa06568999dd/toml.abnf#L39

If it's going to be fixed in a later version then it's not a big deal, but it does seem to be a real mistake in one of the two documents.

**Comment by ChristianSi** [comment]
Indeed! I'm pretty sure the intent was to forbid "Control characters other than tab", like the written spec says, so the ABNF is wrong in U+007F.

But in any case it's a bug in one of the spec documents and the next version must fix it. So it's good that the current mainline already fixed it by allowing nearly all control chars.

**Comment by pradyunsg** [comment]
1.0 was fixed in https://github.com/toml-lang/toml/pull/812. We can discuss reverting #924 in the above PR.

Closing this out since that has been changed on `main` and will be resolved once 1.1.0 is out "soon". :)
