### ISSUE TITLE
Error in spec for multi-line literal string

### ISSUE THREAD

**Issue by J-Vernay** [toml-lang/toml#1026]
Hello,
In the TOML spec on the website, the following example is given for multi-line literal strings :

    quot15 = '''Here are fifteen quotation marks: """""""""""""""'''
    # apos15 = '''Here are fifteen apostrophes: ''''''''''''''''''  # INVALID
    apos15 = "Here are fifteen apostrophes: '''''''''''''''"
    # 'That,' she said, 'is still pointless.'
    str = ''''That,' she said, 'is still pointless.''''

`str` seems invalid to me, given that it ends with 4 apostrophes. Thus a parser would consider the string end at the dot, not at the apostrophe after the dot.

I don't think there is a way of writing a string ending with an apostrophe with a (multi-line) literal string.

Have a nice day!

**Comment by arp242** [comment]
It's valid; it just ends with a trailing `'`.

If `''' it's '''` is valid, then why shouldn't `'''end with q''''` be? It may look confusing and I wouldn't necessarily recommend it, but it's fine. Even `''' str '''''` is fine.

I don't think any of the commonly used parsers fail on the tests for this (all the examples in the TOML spec are also test cases in https://github.com/toml-lang/toml-test).

**Comment by arp242** [comment]
Also looking at the text of the specification:

> You can write a quotation mark, or two adjacent quotation marks, anywhere inside a multi-line basic string. They can also be written just inside the delimiters.
>
> [..]
>
> You can write 1 or 2 single quotes anywhere within a multi-line literal string, but sequences of three or more single quotes are not permitted.

I think it's reasonably obvious this is valid; "anywhere within" also means "at the end" (although, again, it does look funky).

**Comment by JamesParrott** [comment]
Even if a basic parser implementation required the multiline string to be terminated at the first  `'''`, inside `''''`, the very next character (`'`) would raise a syntax error

**Comment by ChristianSi** [comment]
@JamesParrott However, such a parser would be in violation of the spec.

**Comment by JamesParrott** [comment]
@ChristianSi You're right.  THe spec clearly allows multi-line literal strings (before the closing `'''`) to end in either one or two `''`s.

```
ml-literal-string = ml-literal-string-delim [ newline ] ml-literal-body
                    ml-literal-string-delim
ml-literal-string-delim = 3apostrophe
ml-literal-body = *mll-content *( mll-quotes 1*mll-content ) [ mll-quotes ]

mll-content = literal-char / newline
mll-quotes = 1*2apostrophe
```

**Comment by J-Vernay** [comment]
Ok then, my bad! I understood the multi-line literal string as stopping on the first occurrence of '''.
I am writing a TOML decoder, thus I was puzzled by the example. I have not read the ABNF correctly --'.
Thank you for your explanations!

**Comment by arp242** [comment]
In case of doubt, http://instaparse.mojombo.com/ mentioned in the toml.abnf file is pretty useful.
