### ISSUE TITLE
toml.decoder.TomlDecodeError: Invalid inline table encountered 

### ISSUE THREAD

**Issue by ednow** [toml-lang/toml#1047]
toml version：
__version__ = "0.10.2"
_spec_ = "0.5.0"

python version: 3.10+

content:
```
[[class]]
params = [
    {result = 1, param = [ [1, 2, 3], [1, 1] ]},
    {result = 2, param = [ [1, 2], [1, 2, 3] ]}
]
```

ouput: toml.decoder.TomlDecodeError: Invalid inline table encountered 

What cause this? Content below is decoded functionally

```
[[class]]
params = [
    {result = 1, param = [ [1, 2, 3]]},
    {result = 2, param = [ [1, 2] ]}
]
```

**Comment by arp242** [comment]
This is the repo for the TOML language specification, not for reporting bugs for specific implementations.

Also, your TOML is fine:

```
[~]% python
Python 3.12.7 (main, Oct  3 2024, 14:05:50) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tomllib

>>> tomllib.loads('''
... [[class]]
... params = [
...     {result = 1, param = [ [1, 2, 3]]},
...     {result = 2, param = [ [1, 2] ]}
... ]
... ''')

{'class': [{'params': [{'result': 1, 'param': [[1, 2, 3]]}, {'result': 2, 'param': [[1, 2]]}]}]}
```

**Comment by ednow** [comment]
> This is the repo for the TOML language specification, not for reporting bugs for specific implementations.
> 
> Also, your TOML is fine:
> 
> ```
> [~]% python
> Python 3.12.7 (main, Oct  3 2024, 14:05:50) [GCC 13.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> >>> import tomllib
> 
> >>> tomllib.loads('''
> ... [[class]]
> ... params = [
> ...     {result = 1, param = [ [1, 2, 3]]},
> ...     {result = 2, param = [ [1, 2] ]}
> ... ]
> ... ''')
> 
> {'class': [{'params': [{'result': 1, 'param': [[1, 2, 3]]}, {'result': 2, 'param': [[1, 2]]}]}]}
> ```

Sorry to bother again, that one work fine, yet try another content I listed above, the issue comes out

```
[[class]]
params = [
    {result = 1, param = [ [1, 2, 3], [1, 1] ]},
    {result = 2, param = [ [1, 2], [1, 2, 3] ]}
]
```

**Comment by ednow** [comment]
using import pip._vendor.tomli as tomllib fixed my problem~
