### ISSUE TITLE
Newlines in inline tables

### ISSUE THREAD

**Issue by dwilliamson** [toml-lang/toml#1048]
Is there any chance of supporting newlines in inline tables?

It appears this was added to the spec in 2022: https://github.com/toml-lang/toml/issues/516

It looks to be something as simple as allowing newlines to be eaten in this piece of code here, which contains explicit logic to error when newlines are encountered: https://github.com/xoofx/Tomlyn/blob/c264d1d7a417a51e9e8aec04b867be7248d3200a/src/Tomlyn/Parsing/Parser.cs#L374

**Comment by ChristianSi** [comment]
Yes, that's part of the latest spec draft, so it should almost certainly be in TOML 1.1 if and when that version comes. Now all we need is an active maintainer that helps us get that version finalized and published ...

**Comment by dwilliamson** [comment]
I'm really sorry, I opened this in the wrong project.
