### ISSUE TITLE
Long strings without line breaks.

### ISSUE THREAD

**Issue by pygy** [toml-lang/toml#163]
That point has already been discussed in #92, but it is really its own thing:

What about very long strings that don't contain a carriage return, and can't thus be properly displayed with the triple quote syntax in editors with limited width?

Three solutions were proposed so far:

``` CoffeeScript
# Java/Javascript style
key = "First part, " +
      "second part and " + 
      "third part."

# Ignore embedded CR/LF/CLRF
key = "First part, 
second part and
third part"

# C style
key = "First part, "
      "second part and "
      "third part."
```

I don't like the second style, because it forces you to unindent the text.

I proposed the third style, but I'm now partial to the first one, because it is more explicit. For example, a coma forgotten in an array would trigger a syntax error, rather than concatenate values.

Thoughts?

**Comment by gerrywastaken** [comment]
For anybody else. This ended up 4 PRs deep, so to save you some time: https://github.com/toml-lang/toml/pull/232

```toml
val = """
This is
a mulitline
string
"""
```

**Comment by gdennie** [comment]
In summary....

```
single_line_of_text = """
This is a very very very \
long sentence \
that is all \
in one line.
"""
```
and

```
multiple_lines_of_text = """
This is
a mulitline
string
"""
```

**Comment by eksortso** [comment]
> In summary....

Ah. Not exactly. Only the first newline is automatically trimmed, _not the last newline_. If you load these from TOML, you'll end up with an extra newline at the end of each string.

So the first one really should be:

```toml
single_line_of_text = """
This is a very very very \
long sentence \
that is all \
in one line."""
```

The second one is good, if you intend the multiline string to end with a newline.
