### ISSUE TITLE
\uXXXX escaping only covers Basic Multilingual Plane.

### ISSUE THREAD

**Issue by tobyink** [toml-lang/toml#179]
U+0000 to U+FFFF is only a small portion of the Unicode space. It's the so-called "basic multilingual plane" (Plane 0), but Unicode defines 17 different planes, supporting characters all the way up to U+10FFFF.

Plane 1 (U+10000 to U+1FFFF) contains a bunch of mostly historic scripts (e.g. Egyptian hieroglyphs) but also a lot of mathematical and musical notation symbols.

Many Chinese, Japanese and Korean characters are in Plane 2 (U+20000 to U+2FFFF).

**Comment by hax** [comment]
ES6 also use `\u{xxxxx}` and I think it's much better than `\UXXXXXXXX`.
But maybe it's too late...
