### ISSUE TITLE
Bulk Comments

### ISSUE THREAD

**Issue by k2xl** [toml-lang/toml#218]
Any way to do bulk comments in TOML files?

If not, may I propose `###` ala coffeescript?

**Comment by rojares** [comment]
Nine years later and the need for block comments is as strong as before.
It is a very typical scenario that there is a larger block of key-value pairs that go together.
And when testing software you want to keep a block of configurations around while trying another set of configurations.
line comments and block comments can be found in all languages and for a very good and practical reason.

**Comment by k2xl** [comment]
9 years later I am embarrassed I was using coffeescript when I made this ticket 😂

I think likelihood of changing to multiline comments at this juncture is low. Editors nowadays make it easy to bulk add and remove comments per line anyway

**Comment by rojares** [comment]
Hmm, you maybe right.
But is there some reason why the format of toml has been frozen?
Is it because to spread the popularity there must not be any more confusing changes?

**Comment by arp242** [comment]
> block comments can be found in all languages

Python, TCL, and YAML don't have it, Perl also doesn't outside of some hackery, Ruby has it but is rarely used (I don't think I've ever encountered it). That's just from the top of my head. This statement is clearly incorrect.

We can't add multiline comments starting with a `#` as that would break compatibility. Using `=` would make parsing harder. I suppose `-` or some other character can be used, but there is no obvious syntax we can use for this. And as said: it's not so hard to add/remove multiple single-line comments in even most smaller editors.

> But is there some reason why the format of toml has been frozen?

It's not frozen; TOML is *"Tom's Obvious, Minimal Language"*. It tries to be useful while remaining obvious and minimal. Where the cut-off is for "minimal" and "obvious" is a matter of taste, but the goal is not and has never been to include every possible feature.

**Comment by rojares** [comment]
The c-style block comments are fairly standard and easy to parse.
/*
key = "value"
key2 = "value"
*/
Anyway it is true that block comments are not necessary.

**Comment by dliu-fn** [comment]
If I'm not mistaken, Python has:

```
"""Putting a full block explanation here.
And more details on a separate line.

Add examples too
 {a -> b}
"""
```

but @arp242 clearly explained a lot of valid concerns and reasons, thank you.

**Comment by eksortso** [comment]
> If I'm not mistaken, Python has:

What you're describing in Python is typically used in docstrings. But those aren't comments. They're just string values in Python, and they have special meaning when put in their right places.
