### ISSUE TITLE
Optional comma in multi-line arrays

### ISSUE THREAD

**Issue by ChristianSi** [toml-lang/toml#227]
I would like to propose a small change to the array syntax: make the comma between elements optional if they are separated by a newline. This would allow writing this array:

```
colors = [ "red", "yellow", "green" ]
```

alternatively like this:

```
colors = [
  "red"
  "yellow"
  "green"
]
```

Of course, commas after elements would still be allowed but they wouldn't be required provided the element is followed by newline.

This would be nicer for humans to write, and it would make the syntax of multi-line arrays more consistent with tables, where key/value pairs are likewise separated by just a newline.

**Comment by paul-hammant** [comment]
VCS diffs that are not as noisy would be one benefit to this feature
