### ISSUE TITLE
RFC: Canonical Implementation

### ISSUE THREAD

**Issue by pnathan** [toml-lang/toml#233]
Hi,

I see that we have several languages with a multiplicity of implementations of TOML. While variety is good in a garden and even more awesome in ideas, it kind of is lame when I just want to grab The $language Parser For TOML and trust that it's the best choice. 

I propose the idea that one implementation for the competing implementations should be chosen by a TOML maintainer (Probably with a PR to toml-lang!) to be Blessed based upon its test suite compliance and popularity.  If another implementation surpasses it, the Blessing will pass to the new implementation.  The Blessing will be noted in the README.md for TOML.

At least two advantages exist here: we can centralize a language's implementation effort on a particular heap of source code, and we can provide a happy path for new users of TOML.

At least two disadvantages exists here: if the implementation rots, someone has to work to  get a new library Blessed, and it (IMO) discourages new implementations from being written if one is already Blessed.

**Comment by mojombo** [comment]
I think it's premature to start naming canonical implementations. The first step will be to see which parsers become 1.0 compliant once we reach that milestone. I'd love to prominently list those that are compliant in the spec when the time comes. Once there are many 1.0 capable parsers we might benefit from blessing one per language, but that will be a while. Until then, closing this out.
