### ISSUE TITLE
Allow space to seperate date and time

### ISSUE THREAD

**Issue by flaviut** [toml-lang/toml#279]
The RFC cited allows applications to use ` ` along with `T` as the date-time separator:

> NOTE: ISO 8601 defines date and time separated by "T".
> Applications using this syntax may choose, for the sake of
> readability, to specify a full-date and full-time separated by
> (say) a space character.

This would be a nice extension, and the RFC mentioning it creates precedent.

**Comment by mojombo** [comment]
Yes, that's true, but TOML craves simplicity, and I don't see a huge benefit to allowing the SPACE variant. Unless there are reasons I'm not seeing (and I don't think readability is one of them), I'd like to enforce the T format of RFC 3339.
