### ISSUE TITLE
arrays can mix multiple data types

### ISSUE THREAD

**Issue by BurntSushi** [toml-lang/toml#28]
I believe

```
No, you can't mix data types, that's stupid.
```

is at odds with

```
[ [ 1, 2 ], ["a", "b", "c"] ]
```

Namely, the above is an array with two elements: the first element is an array of integers and the second element is an array of strings. This is a mixing of data types.

Practically, this makes it awkward for languages whose native lists are homogeneous to read `TOML` correctly.

`TOML` allows mixing of data types at the level of the hash table. I propose that `TOML` not allow the mixing of data types at the array level.

**Comment by nhooyr** [comment]
I read through all further discussion but I am still confused on how this was addressed. Why are arrays of integers allowed to be mixed in with arrays of strings?

**Comment by nhooyr** [comment]
Especially since we now that we have inline tables.
