### ISSUE TITLE
Do not allow `"` in table names

### ISSUE THREAD

**Issue by flaviut** [toml-lang/toml#280]
`["foo.bar"]` should be parsed as `"foo`.`bar"`, but that is not immediately apparent for a human reading a configuration file.

I believe this, along with `'` should not be allowed in order to make human parsing simpler.

**Comment by BurntSushi** [comment]
This is probably reasonable if #220 doesn't get in, but I'd really like to see properly quoted keys.

**Comment by flaviut** [comment]
Also related, #65

**Comment by mojombo** [comment]
See #283.
