### ISSUE TITLE
Unicode escape syntax

### ISSUE THREAD

**Issue by flaviut** [toml-lang/toml#282]
The current spec provides the following escapes:

>     \uXXXX     - unicode         (U+XXXX)
>     \UXXXXXXXX - unicode         (U+XXXXXXXX)

Using the regular expression `\\[uU][0-9a-fA-F]{2,8}` ([regex101][re_example]) instead would have a couple advantages:

- It'd be backwards compatible
- 0-padding is unnecessary

[re_example]: https://regex101.com/r/wP0jS8/1

**Comment by dhardy** [comment]
But the parser wouldn't know how many digits to read.

**Comment by flaviut** [comment]
Good point, I hadn't considered that.
