### ISSUE TITLE
Synwrite lexer

### ISSUE THREAD

**Issue by Alexey-T** [toml-lang/toml#285]
Synwrite. to install lexer: open Options/ Addons manager/ Install, enter "TOML" in top edit, and choose it.

**Comment by mojombo** [comment]
Is there a link to an open source project that contains the relevant code for this? With a README or something that has these instructions?

**Comment by Alexey-T** [comment]
http://uvviewsoft.com/synwrite/download.html ; call Options/ Addons manager/ Install
