### ISSUE TITLE
hashmark i string

### ISSUE THREAD

**Issue by sajt** [toml-lang/toml#294]
I using Hugo to generating HTML pages. My menu in my config.toml file. In the menu I like to use # for anchors. How can I use it? I tried:
 url = "/team-and-mission\u0023press" // removed
 url = "/team-and-mission#press"  //removed
 url = "/team-and-mission##press"  //removed
 url = "/team-and-mission\#press"  //error

What is the solution?

**Comment by BurntSushi** [comment]
It seems to be working fine over here:

```bash
[andrew@Liger ~] echo 'url = "/team-and-mission#press"' | toml-test-decoder
{"url":{"type":"string","value":"/team-and-mission#press"}}
```

Could you please provide a reproducible test case that demonstrates your error? Is it possible the Hugo is doing something to your URLs and not TOML?

Also, your second and fourth examples appear to be identical, but the second says "// removed" and the fourth says "// error."

**Comment by ChristianSi** [comment]
This looks very much like a problem in a specific implementation, unrelated to the TOML spec per se.

**Comment by BurntSushi** [comment]
@ChristianSi Hah! I thought this was `BurntSushi/toml` and not `toml-lang/toml`.

@sajt This is definitely the wrong place to report it. I'd suggest that you report this bug to the Hugo folks. If it's a bug in my TOML implementation, then they'll hopefully let me know. :-)
