### ISSUE TITLE
Thousands separators: +1_200_300.45

### ISSUE THREAD

**Issue by hamstergene** [toml-lang/toml#295]
It would be good to allow thousand separators in numeric literals:

    x = 2_000_089
    y = 1_999.95

Only single `_` between digits must be allowed. Combinations like `_1`, `2_` and `3___4` should be illegal.

**Comment by mojombo** [comment]
This seems reasonable. Some kind of separator greatly enhances readability of large numbers, and I see that as highly desirable for config files. @BurntSushi thoughts?

**Comment by BurntSushi** [comment]
I personally love this. Rust has it and I use it all the time.

Config files are meant to be read and written by humans and I think this greatly improves readability.

**Comment by mojombo** [comment]
Cool. I'll work up a PR.

**Comment by mojombo** [comment]
Please continue discussion in #296.
