### ISSUE TITLE
hexidecimal floats

### ISSUE THREAD

**Issue by darcyparker** [toml-lang/toml#319]
There could be a loss of information when parsing the decimal string into a float.

See:
https://blogs.oracle.com/darcy/entry/hexadecimal_floating_point_literals

Hex floats are not pretty... but they are accurate and there is no risk of loss of information due to rounding when you move from decimal to binary or vice versa.

Supporting them would be valuable to people who need to exchange floats via a toml file.

**Comment by BurntSushi** [comment]
If you really need this, then just put the number in a string and let the application handle it.

**Comment by darcyparker** [comment]
Yes - that's a possible solution.  But it is misleading/confusing to call it a float when it isn't an accurate representation of a float. See https://github.com/toml-lang/toml#float

If this feature request isn't taken up, then it might be good to clarify the documentation.

**Comment by mojombo** [comment]
I don't think this passes the minimalism benchmark for TOML. I would also guess that most people that need such precision out of a float will be familiar with the limitations of floats. If this proves otherwise in the future, there may be a place for hex floats in a later version.
