### ISSUE TITLE
v0.4.0: Should these cases be allowed?

### ISSUE THREAD

**Issue by jakwings** [toml-lang/toml#320]
Spec: <https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md>

### Case 1

INPUT:
```
a = []
[[a]]
```

OUTPUT:

```
{
  "a": [
    {}
  ]
}
```

### Case 2

INPUT:
```
a = {c = {}}
[a]
b = 1
[a.c]
d = 2
```

OUTPUT:

```
{
  "a": {
    "b": 1,
    "c": {
      "d": 2
    }
  }
}
```

### Case 3

INPUT:
```
[[a]]
[[b]]
[a.c]
```

OUTPUT:

```
{
  "a": [
    {
      "c": {}
    }
  ],
  "b": [
    {}
  ]
}
```

My parser is almost finished. But these cases are really ambiguous. :-(

**Comment by BurntSushi** [comment]
The spec is pretty unambiguous on this actually:

> You cannot define any key or table more than once. Doing so is invalid.

**Comment by jakwings** [comment]
@BurntSushi Thanks. Do you mean:

* Case 1: Although table array is additive, it cannot add a table to a array with mixed-typed values.
* Case 2: Inline table `{c: {}}` is directly assigned to `a`, so `a` cannot be redefined.
* Still case 2: If we omit `[a]`, was `a.c` directly directly defined in `a = {c: {}}`? (I guess "yes")
* Case 3: Well, I don't think you have answer my question. Should `[a.c]` be placed next to `[[a]]`?

And I have case 4:

```
[x]
[y]
[x.y]  # Should I place [x.y] next to [x]?
```

**Comment by jakwings** [comment]
For case 3, please also search `[fruit.physical]` in the spec.

**Comment by mwanji** [comment]
In case 1, a is defined twice. It doesn't matter if the types are "compatible" or not (which I don't think they are).

In case 2, a and a.c are defined twice.

Case 4 is fine, though it's safer to put things in the most obvious order.

**Comment by jakwings** [comment]
Thanks for your opinions, @mwanji !

I am curious if someone would like to place the tables with longer path behind the simple ones.

**Comment by BurntSushi** [comment]
Ordering mostly doesn't matter. This:

```toml
[a]
[a.b]
```

Is equivalent to:

```toml
[a.b]
[a]
```

From the spec:

> As long as a super-table hasn't been directly defined and hasn't defined a specific key, you may still write to it.

Where ordering matters is table arrays. The spec says:

> Each table with the same double bracketed name will be an element in the array. The tables are inserted in the order encountered.

So your case 3 is correct and it is documented. `a` is the double-bracketed name and it belongs to the most recently defined element, which is `[[a]]` on the first line.

The wording could probably be clearer.

**Comment by BurntSushi** [comment]
Case 4 is fine. TOML gives the writer a lot of flexibility with respect to where things are defined. Ordering has little semantic value outside inherently sequential data types (like arrays). Tables are always unordered, which means keys/values can come in any order.

**Comment by jakwings** [comment]
Thanks!
