### ISSUE TITLE
How to strip space and \r \n  for TOML?

### ISSUE THREAD

**Issue by netroby** [toml-lang/toml#323]
How to strip space and \r \n  for TOML?

JSON can be strip space and \r\n, a large json can be stripped into one line.

**Comment by BurntSushi** [comment]
Huh? Can you give an example?

**Comment by jakwings** [comment]
Newlines can be stripped if they are not in strings or used as separators between key-value pairs and table headers like `[a.b]` or `[[a.b]]`. Spaces can be stripped only when not in strings.

**Comment by mojombo** [comment]
I think the spec is straightforward on the rules, let me know if you think there is ambiguity in a new issue.
