### ISSUE TITLE
Specify whether key-value pairs are ordered

### ISSUE THREAD

**Issue by Zero3** [toml-lang/toml#331]
The current spec doesn't seem to specify whether key-value pairs generally are ordered or not.

For example, given:

    [table1]
        text = "This is table 1"
    
    [table2]
        text = "This is table 2"

... is it then guaranteed that table 1 will occur before table 2 during an iteration over key-value pairs of the TOML?

My initial guess would be no, given that key-value pairs inside tables have no such guarantee according to the spec. Whether the same is true for top-level key-value pairs seems to be unspecified. It would be nice if this was specified too.

**Comment by jakwings** [comment]
> Key/value pairs within tables are not guaranteed to be in any specific order.

https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md

All table structures are the same, no matter it is top-level or embeded.

**Comment by mojombo** [comment]
@jakwings is correct. The top-level anonymous table follows the same general rules as other tables.
