### ISSUE TITLE
Decimal floats

### ISSUE THREAD

**Issue by mrange** [toml-lang/toml#335]
When reading the definition of floats it seems to imply that floats should be represented as 64-bit double which usually is a binary float.

Binary floating points works excellent for physics but aren't the best choice for finance.

Binary floating points have the drawback of not being able to represent common numbers in financial systems exactly, numbers such as 10.24, 9999.99, as well only having 53 significant bits.

Therefore many programming languages, databases and other tools supports decimal floats.

In order to improve the suitability of TOML for finance software it may be worth considering supporting decimal float literals for example 10.24M could be interpreted as a decimal floating point.

One might say that it's up to the parsers to determine how to interpret a floating point but in my opinion this is not good enough for a format used to pass financial information. An example from JSON world is that the some implementations allows serialization/deserialization of Int64 values as JSON numbers which work fine when both endpoints support it. When passing the JSON document to JavaScript which only supports double the Int64 number might get truncated which doesn't work that well for PrimaryKeys.

A work-around is to pass all sensitive numbers as Strings but I would prefer a specific literal.

PS. I think TOML looks like a vast improvement over said JSON and YAML for the exact reasons you mention.

**Comment by jakwings** [comment]
From the 0.4.0 spec:

> TOML aims to be a minimal **configuration file format** that's easy to read due to obvious semantics … should be **easy to parse** into data structures **in a wide variety of languages**.

So I wonder whether you are taking TOML as a format for exported financial data (instead of configuration data), and how many languages support decimal floats (fully? with modules?).

**Comment by mojombo** [comment]
Another option is to specify currency as an integer number of cents (for USD) or whatever the smallest unit is. As a configuration format, I'd guess this would be sufficient for almost all use cases. As was mentioned before, if transfer of bulk financial data is the goal, TOML may not be the best format to use, and that's ok.

**Comment by mrange** [comment]
Often useful tools get in situation that the inventors didn't originally intend so one could imagine someone using toml to transfer financial data.

Still even for configuration formats decimals arepreferable in my opinion as the physical representation of 10.2 is EXACTLY 10.2 instead of the closest thing that double can represent.

For me it's not a problem that that toml doesn't support decimals as I just represent financial amounts as strings. The problem is that I sometimes end up consuming data where developers unfortunately represent financial amounts as double thinking that is the best representation available.

Anyway it was worth a try
