### ISSUE TITLE
Terminology: "Table"

### ISSUE THREAD

**Issue by jhermann** [toml-lang/toml#338]
I find the term "table" very unintuitive, pretty much every other config format calls this a "section", and also I know of nowhere else where table is used to name a set or K/V pairs.

**Comment by jakwings** [comment]
hash table

**Comment by mojombo** [comment]
Yeah, "hash tables" are a very common name for k/v pair storage, but the "hash" part is just an implementation detail. Lua uses this terminology, fwiw. I'm happy with the term, it's concise and has served us well so far.
