### ISSUE TITLE
Allow omitting fractional part of floating point numbers

### ISSUE THREAD

**Issue by gsingh93** [toml-lang/toml#339]
It would be nice to be able to specify floating point numbers such as `0.0` as simply `0.`, similar to how it works in Rust.

**Comment by BurntSushi** [comment]
The very first lesson I was taught in my undergraduate chemistry course was to *always* put a digit after a decimal point because it can be easy to miss.

I favor the more explicit `0.0`.

**Comment by gsingh93** [comment]
It's a personal preference for a lot of people really. I don't mind if this doesn't get accepted, but I think we should have the choice to write it either way, like how Rust allows.

**Comment by BurntSushi** [comment]
Right. I disagree with the benefits of that choice.

**Comment by mojombo** [comment]
I think this proposal would violate the obviousness principle of TOML, as it creates multiple ways to do something that doesn't really warrant it. Adding a zero is not a burden and reduces readability, in my opinion.
