### ISSUE TITLE
Secure Data in TOML

### ISSUE THREAD

**Issue by jmelfi** [toml-lang/toml#342]
So I've not found a way of obscuring data from being directly readable.  A method like eyaml or gpg encryption would be beneficial when you want to store passwords/privatekeys/sensitive data within the TOML file itself.  This would then let you read that data our without having to keep an unsecured readable format of the file around.

I'm sure there are other solutions but I know the Salt project has their Pillars setup to be used with GPG if desired while Puppet refers to the EYaml ruby gem.

**Comment by BurntSushi** [comment]
I'd be very against putting something like this directly in the spec. It pretty explicitly goes against minimalism because there are other tools that will help you do this.

**Comment by jmelfi** [comment]
I assume you are referring to tools like [viper](https://github.com/spf13/viper) or using some product such as etcd or consul?

I get not wanting to put this directly into the spec in keeping this minimalist.  I've not found a project that fully supports TOML encryption/decryption like eyaml or other yaml/json encrypt/decrypt tools.

If you have some tools that do this already, it would be useful to be able to use them as business requirements need us to obscure some values in our configs and we use eyaml for this now and it works well.  If there isn't anything yet, I will probably look at writing my own.

Thanks for the quick reply.

**Comment by BurntSushi** [comment]
You can encoded any arbitrary byte sequence via base64 into a TOML string. So you should be able to use any kind of encryption you like.

**Comment by jmelfi** [comment]
Ok, that should work for testing purposes.  I'll probably look to write a wrapper for this to let it work in and out.  Thanks again.

**Comment by abathur** [comment]
I stumbled on both this issue and a project addressing the encryption of json/yaml/toml fields during the same search, so I'll just leave this breadcrumb for others: https://github.com/Shopify/ecfg
