### ISSUE TITLE
Key/Value should be explained in an earlier section

### ISSUE THREAD

**Issue by minoritea** [toml-lang/toml#348]
Hi,

I would like to see a description about Key/Value pair in an earlier section,
because we have to see the Table section to know about Key/Value pairs.

I think the description about Key/Value pair in an earlier section makes the document easy to understand even if it is obvious for familiar with .ini style format.

And then, I would like to see a description about Top-level table in the earlier section.

Unfortunately, I am not better at document writing in English.
Could anyone write above changes?

Thanks,

**Comment by mojombo** [comment]
Agreed. @minoritea can you take a look at #387?

**Comment by minoritea** [comment]
It looks fine!
Thank you so much.
