### ISSUE TITLE
Inline table should use colon

### ISSUE THREAD

**Issue by J-F-Liu** [toml-lang/toml#349]
All definations look good except inline table, I think
`name = { first: "Tom", last: "Preston-Werner" }`
is better than
`name = { first = "Tom", last = "Preston-Werner" }` because:
1. it avoids many equal signs in one line.
2. it is familiar js syntax and is used in [JSON5](http://json5.org/)

**Comment by BurntSushi** [comment]
I have a slight preference for colons myself, but `=` is just fine too. This is a bikeshed though, and the only appropriate solution is to "just pick one." We already did just that and I don't see a reason to change.

**Comment by J-F-Liu** [comment]
v0.4.0 is released not long ago, and it is not v1.0, so is changable. The reason as I listed:
1. it avoids many equal signs in one line.
2. it is familiar js syntax and is used in JSON5
3. it saves one space per key/value pair, so the total line is shorter
why not pick the best one?

**Comment by J-F-Liu** [comment]
Suddenly realised that if we use colon in inline table, then TOML is a superset of JSON5, and JSON5 is a superset of JSON, this is great for the adoption of TOML to the community!

**Comment by BurntSushi** [comment]
> v0.4.0 is released not long ago, and it is not v1.0, so is changable

No. We need to stabilize TOML, not break things.

Unless there's a *really* good reason, I'm opposed to any breaking changes leading up to 1.0 at this point. A syntax bikeshed is *not* a good reason, sorry.

**Comment by J-F-Liu** [comment]
Then how about allow colon as an alternative option, this won't break things, just give people another choice.

**Comment by BurntSushi** [comment]
That adds complexity with no appreciable benefit. Choice is not universally
good.

Sorry, but I just don't see this happening.

**Comment by skybon** [comment]
TOML is centered around INI-like **key** - ***equal sign*** - **value** pairs as opposed to **key** - ***colon*** - **value** of JSON. Therefore it would be plain confusing for end-users to mix colors in here.

If you're willing to use colons then switching to JSON (or as @J-F-Liu suggested, JSON5) completely would be a better choice.

**Comment by avakar** [comment]
@J-F-Liu TOML will never be a superset of JSON, not as long a there's `key=` at the beginning of each line.

**Comment by J-F-Liu** [comment]
Agree TOML should not be a superset of JSON, it should be simple. With similar syntax 'superset' can  mean mentally not strickly. Since inline style is seldom used, this is not a big issue.

**Comment by mojombo** [comment]
We already hashed out the = vs : issue while fleshing out the inline table spec, and I'm happy with the current approach. Thanks for the feedback!
