### ISSUE TITLE
how to handle to duplicate keys ?

### ISSUE THREAD

**Issue by rajeshpg** [toml-lang/toml#350]
Does the spec describe how to handle duplicate key value ?
eg:
admin = "Tom"
admin = "Rajesh"

should the parser give back "Tom" or "Rajesh" ?

**Comment by BurntSushi** [comment]
From the spec:

> You cannot define any key or table more than once. Doing so is invalid.

**Comment by rajeshpg** [comment]
@BurntSushi thank you and i agree . but, should a parser throw an error/exception in case it finds a duplicate key ?

**Comment by BinaryMuse** [comment]
I would expect a compliant parser to throw or provide an error rather than silently ignoring the problem.

**Comment by BurntSushi** [comment]
Yes, indeed. Duplicate keys are invalid, so a conforming parser should reject them.

**Comment by BurntSushi** [comment]
@rajeshpg You should probably check out the test suite, which, e.g., has a test that the parser should explicitly reject: https://github.com/BurntSushi/toml-test/blob/master/tests/invalid/duplicate-keys.toml

**Comment by rajeshpg** [comment]
@BurntSushi thanks again :-) 
@BinaryMuse thank you :-)

**Comment by Biswajit1234-a** [comment]
Duplicate key issue.... I want one unique key
