### ISSUE TITLE
Array of Inline Tables

### ISSUE THREAD

**Issue by uiri** [toml-lang/toml#352]
The spec has provisions for Arrays of Tables so it makes sense that Arrays of Inline Tables would be possible.
The spec says that Arrays only contain primitives. Are inline tables considered to be primitives?
Line breaks are allowed inside of arrays but not inside of inline tables. If arrays of inline tables are allowed, are line breaks not permitted at all or are they permitted but only between inline tables and not within them? What if there is an array of inline tables with an inline table inside of it which has an array in it?
Relevant for implementation in uiri/toml#41

**Comment by ChristianSi** [comment]
The spec already states that Arrays of Inline Tables are supported:

> You may also use inline tables where appropriate:
>
>     points = [ { x = 1, y = 2, z = 3 },
>                { x = 7, y = 8, z = 9 },
>                { x = 2, y = 4, z = 8 } ]

The spec is also clear stating that linebreaks are allowed inside arrays but not inside inline tables.

As for arrays *within* inline tables, I'd guess that no linkbreaks are allowed in them. The spec says:

> No newlines are allowed between the curly braces unless they are valid *within a value.*

(Emphasis added.) I'd guess that means that spaces within multi-line strings are allowed, but not spaces outside of strings (even if inside of arrays), as an array is not an (atomic) value. But the spec is not totally clear on this.

**Comment by ChristianSi** [comment]
I also think that the spec is a bit confusing in talking about "primitives", as the term is nowhere defined and, intuitively, neither nested arrays or nested inline tables are very "primitive".

**Comment by alexeyr** [comment]
> I'd guess that means that spaces within multi-line strings are allowed, but not spaces outside of strings (even if inside of arrays), as an array is not an (atomic) value. But the spec is not totally clear on this.

Note that it says "All value types are allowed, including inline tables". It would be strange if inline tables were considered values for this, and arrays weren't. Also, "arrays are only ever values".

**Comment by mojombo** [comment]
Yes, inline tables are values. I'm about to merge a clarification that should help.

**Comment by aggieben** [comment]
> Data types may not be mixed

Is `{ a = 3, b = "hey" }` a different type from `{ x = 7.0, y = false }`?

**Comment by TheElectronWill** [comment]
I think not: all tables have the same type.

**Comment by aggieben** [comment]
Oh, duh:  it was even in the commit: https://github.com/toml-lang/toml/commit/3232eb737908de01e46915118e83fcd42db7784a#diff-04c6e90faac2675aa89e2176d2eec7d8R383

Thanks.
