### ISSUE TITLE
Style guidelines instead of parser rule for inline table whitespacing?

### ISSUE THREAD

**Issue by atweiden** [toml-lang/toml#355]
I recently implemented [inline tables](https://github.com/atweiden/config-toml/commit/ee921fe79acaa108d594cdef29f0a7385d316963), and I made the whitespace rules consistent with the array whitespace rules out of instinct having not read that part of the spec closely enough. With respect to this quote:

> it is strongly discouraged to break an inline table onto multiples lines

Could inline table whitespacing become a general style guideline instead of a rule for parsers?

**Comment by mojombo** [comment]
That's essentially what it's already saying. If you really wanted to, you could do this and it would be valid:

```toml
key = { abc = [1,
2,
3] }
```

But the spec discourages it, as it's not very readable, and violates the purpose of inline tables.
