### ISSUE TITLE
Precise definition of the semantics

### ISSUE THREAD

**Issue by andrusha97** [toml-lang/toml#358]
There is ongoing work on a precise definition of the syntax using ABNF, but I want to point out that semantics of the language should be defined as well. By semantics I understand rules of how to generate DOM from any particular TOML document.

Example:

``` toml
[a]
b = [{key1=1, key2=2}]

[[a.b]]
key="value"
```

Is this document valid or not? The spec says that `[{key1=1, key2=2}]` is a valid way to define an array of tables. So probably this array may be appended with the `[[xxx]]` syntax?

But what if the initial array is empty:

``` toml
[a]
b = []
[[a.b]]
key="value"
```

[This test](https://github.com/BurntSushi/toml-test/blob/master/tests/valid/array-empty.toml) implies that an empty array is not an array of tables. So probably it cannot be updated this way.

Or may be both of these samples are not valid.

I think that such things should be specified in the spec. Otherwise different parsers still will implement slightly different versions of TOML.

**Comment by jakwings** [comment]
+1 

And the config should be easy to parse by humans, so I reject both samples.

**Comment by franklinyu** [comment]
Yes, this should be explicitly and precisely defined. I agree with @jakwings that these samples should be rejected.

**Comment by mojombo** [comment]
Clarified in 014644d8f1e9bc1c4f1b522687bc3f5ec7eab038.
