### ISSUE TITLE
Idea: Inline includes?

### ISSUE THREAD

**Issue by shazow** [toml-lang/toml#36]
In Python-land, it's not uncommon to include subsections of an INI file from another INI file. (Especially in Paste-style INI files.)

So I could have

```
# development.ini
[app]
database = "sqlite://whatevs.db"
# [... lots of other things]
```

And in my unit testing environment, I'd override just one key...

```
# testing.ini
[app]
use = config:development.ini#app
database = "sqlite:///:memory:"
```
# TOML proposal

As for how this would look like in TOML if we wanted to support it, perhaps some variation of...

```
# Assign to section?
[app] = development.ini#app
database = "override value"
```

Or perhaps...

```
# Non-assignments are treated as includes?
[app]
development.ini#app
database = "override value"

# Could even support multiple includes
[app]
app_defaults.ini
development.ini#app
somekey = "foo"
someotherkey = "bar"
override_keys.ini#app
```

Quite possibly out of scope for TOML, but an interesting thought experiment.

**Comment by babilen** [comment]
Any news on this? This is a serious limitation in toml and makes using software that uses toml as configuration file format much harder as there is no easy way to support common "`.d`" directories.

**Comment by Artoria2e5** [comment]
I am definitely not proposing to add this to TOML, but just for a better format proposal in case someone wants to do a little dialect:

In TOML the unquoted keys can only be alphanumeric or `-_` (see `unquoted-key` in ABNF). This leaves us a lot of space to expand using the symbols, so we can have:

```matlab
%include "foo.toml"
%include-dir "conf.d"
```

This could be described more concretely as:

```abnf
preprocessor-statement = %x2F preprocessor-key ws string
preprocessor-key = "include" / "include-dir"
```

(I am calling it "preprocessor" as it clearly belongs to such a separate pass. Integrating into the expression tree is not something I want to look at at all, but you can try if you insist.)

**Comment by dgutson** [comment]
What happened to this feature, why was closed? `%include` was very cool!

**Comment by pradyunsg** [comment]
See the closing note: https://github.com/toml-lang/toml/issues/36#issuecomment-14004723
