### ISSUE TITLE
Are arrays of arrays of different types allowed?

### ISSUE THREAD

**Issue by alexeyr** [toml-lang/toml#366]
Is `[ [1, 2], ["a"] ]` a legal value?

**Comment by alexeyr** [comment]
I see this is actually mentioned in #28, but the decision there depends on tuples. Currently the spec says 

> Arrays are square brackets with other primitives inside. Whitespace is ignored. Elements are separated by commas. Data types may not be mixed (though all string types should be considered the same type).

but it doesn't say that arrays of ints, arrays of strings, etc. are different types (and listing just "array" among other types creates the impression they aren't).

**Comment by skystrife** [comment]
Yes; see the key `arr5` in [the array section of the README](https://github.com/toml-lang/toml/blob/master/README.md#array).

**Comment by alexeyr** [comment]
Thank you.
