### ISSUE TITLE
Is there a support for complex string keys?

### ISSUE THREAD

**Issue by chillum** [toml-lang/toml#371]
It's not clear from the docs and, I believe, most of third-party tools have errors with it.

That is: I want to pass a string with whitespaces and special characters as a TOML key like:
```toml
# GitHub marks it as invalid because of "[" character. Same with single quotes.
# It also breaks the http://toml-to-json.matiaskorhonen.fi/ online converter badly.
["ping -c 1 192.168.7.1; [ $? = 1 -o $? = 2 ]"]
repeat = 30
```
The structure I assume with that in JSON is:
```json
"ping -c 1 192.168.7.1; [ $? = 1 -o $? = 2 ]": {
  "repeat": 30
}
```

Is that valid TOML v0.4?

If not, how I can achieve this?

If yes, it would be great if official examples included something alike, so that other programmers can implement this.

**Comment by chillum** [comment]
At this moment I think, the struct above is bad by design.

I think, a TOML way to achieve this is like:
```toml
[[check]]
shell  = "ping -c 1 192.168.7.1; [ $? = 1 -o $? = 2 ]"
repeat = 30
```

Closing this issue and thanks for reading.

**Comment by nicolas17** [comment]
Your original snippet looks valid to me.

Note that this is an example in the TOML 0.4 spec, and [that tomltojson converter](https://toml-to-json.matiaskorhonen.fi/) gets it very wrong too:
```toml
[dog."tater.man"]
type = "pug"
```
