### ISSUE TITLE
Example key/value pair exceeds representable range of a 64-bit IEEE 754 float

### ISSUE THREAD

**Issue by skystrife** [toml-lang/toml#377]
Specifically, the example

```toml
key9 = 1e1_000
```
cannot be represented using a 64-bit IEEE 754 float. Right below this key, however is the statement

> 64-bit (double) precision expected.

These seem to be in conflict. While `1e1_0000` may be able to be parsed by some libraries, it's not necessarily clear what should happen in this case. I'm fine with not specifying this in the spec itself, but we should probably not have this as an example if the result is likely to be implementation defined.

**Comment by mojombo** [comment]
Agreed, that is a very bad example! I'll get a fix for that in now.
