### ISSUE TITLE
Unquoted multi-line string literals

### ISSUE THREAD

**Issue by pfmoore** [toml-lang/toml#383]
Would it be possible to allow unquoted multi-line literals? Specifically, something like
```
long_description =
    Starting indented on a new line with nothing on the "key" line signals a multi-line literal.
    Newlines are preserved, but indentation equal to that of the first line is stripped
    from subsequent lines (for readability of the input).
        Additional indentation *is* preserved
    (so the above line would be indented 4 spaces, not 8).
```

The idea would be that multi-line literals give a way of including "blocks of text" such as SQL statements, or long descriptions, while not having to add quotes or end of line backslashes, or put the text flush left.

**Comment by mojombo** [comment]
Read the section on multi-line basic strings: https://github.com/toml-lang/toml#string, unless I'm missing something, they do exactly what you want.

**Comment by pfmoore** [comment]
The key points not covered are:

1. No quotes - it's not a huge deal, but "unquoted" was deliberate - for something like this, I find the quotes are a distraction.
2. Multi-line *basic* strings definitely aren't what I want, because I want no backslash interpretation. I assume you meant multi-line *literal* strings.
3. The indentation stripping is key to maintaining readability in the file as well, for me. Having to put the data flush left makes it very hard to see where the data value ends and the next key/value pair starts. I use triple-quoted strings a lot in Python, and this is a major readability disadvantage. In Python, the standard library ```textwrap.dedent``` function lets you indent triple-quoted strings in the source and remove the indent at runtime, but TOML has no such capability, as it's markup, not code.

It's certainly possible to use multi-line literal strings for the same data as I want to use unquoted multi-line literals for, but IMO it's much less readable.

FWIW, my use cases are things like:

* Embedding a chunk of descriptive text, possibly marked up using something like reStructured Text or HTML, in my configuration.
* Having a configuration item that's a piece of SQL (or a shell script, or some other programming language) to be run when the configuration is processed.

For both of these, stripping a level of indentation is the crucial aspect. If multi-line literal strings worked slightly differently, and instead of just stripping an initial newline they also de-indented the value,then that would be fine. But I assumed this wouldn't be acceptable because it's incompatible with current behaviour.

But if this isn't going to be added to TOML, so be it - I can either put up with multi-line literal strings, or implement my own TOML parser with this as a custom extension. Thanks for the reply.

**Comment by BurntSushi** [comment]
I think I'd be against all of your suggestions. Strings have been quoted in TOML since its inception; I think that ship has sailed.

I admit, being able to indent the text would be sort of nice, but that brings up weird peculiarities when you *want* to have the indent be present in the string. So do you strip only one whitespace character instead? Seems hairy.

I think "much less readable" is a pretty big overstatement. I think "slight preference for indented text" seems more reasonable. If you're that keen on permitting a visual indent that isn't part of the string, then it seems easy enough to do that in an application that uses any conforming TOML parser: simply wrap strings in your `dedent` function. Another way to solve this problem is syntax highlighting.

**Comment by pfmoore** [comment]
My expectation was:

* Check what whitespace is present on the first line of the data
* Confirm that all lines start with that same whitespace (ignore lines that are empty)
* If so, strip precisely that whitespace from the start of every line of the string.

If you want the indent, multi-line literal strings are likely to be fine (needing to include the quotes isn't a show-stopper).

My "much less readable" was based on a fairly large body of experience with Python's triple-quoted strings - both from the POV of someone writing Python code, and that of maintaining other people's code that uses flush-left literals. I've also dealt with the frustrations of *not* having a config format that allows the sort of strings I describe in a number of projects. But certainly embedding strings in code is different from config files, so my experience may not transfer well. And it's without a doubt a matter of opinion.

As I said, though, I accept that this isn't considered a good fit for TOML. Thanks for explaining your reasoning.

**Comment by BurntSushi** [comment]
If I write:

```toml
key = """
    I want the
    indent to be
    preserved in this string.
""""
```

then your logic means that the indentation is lost.

> But certainly embedding strings in code is different from config files, so my experience may not transfer well.

Exactly. I like the way Python handles things. In Python, doc strings are first members of the language, so they can be manipulated trivially depending on the context. TOML has no such conveniences as a markup language unfortunately. I still think doing the dedent yourself outside of a TOML parser would be just fine.

**Comment by pfmoore** [comment]
I really should shut up now as it sounds like I'm still arguing for the feature, and I'm not. But... :-)

```
key = """
    I want the
    indent to be
    preserved in this string.
"""
```
will preserve the indent because it's *not* my proposed string type, it's a basic multi-line string. I deliberately didn't suggest changing that because backward compatibility, as well as the ability to preserve whitespace if that's what you want, is important.

>  I like the way Python handles things. In Python, doc strings are first class members of the language, so they can be manipulated trivially depending on the context.

I've written/maintained/seen *lots* of code that goes through all sorts of hoops to adust the indentation of Python docstrings because indenting the content to match the surrounding context makes the string content very weirdly indented. And I've seen plenty of tools that format docstrings badly because they don't do this. Our experiences obviously differ.

> I still think doing the dedent yourself outside of a TOML parser would be just fine.

Yeah, I can say that fields X, Y and Z will have leading indent stripped, and write the code to do that.
