### ISSUE TITLE
cannot open file of type toml

### ISSUE THREAD

**Issue by jbshirk** [toml-lang/toml#384]
I know this is not really a problem with toml as it is just a text file, but i have a weird problem on OS X:

OS X does not know how to open a .toml file; if I tell it to open with textedit or text soap, it should just open it but instead both editors say "cannot open file of type toml." surely this has happened to someone else.

I suspect that when git cloning a default hugo site, something got converted to binary. but when i cat a toml in the shell, it just looks like a plain text file. it's driving me mad...

**Comment by jbshirk** [comment]
for example: when I did a commit in fossil after cloning, I got a bunch of these:

    ./themes/agency/exampleSite/data/projects/2014-07-05-project-1.yaml contains CR/NL line endings. Use --no-warnings or the "crnl-glob" setting to disable this warning. Commit anyhow (a=all/c=convert/y/N)? c

I told it to convert.

**Comment by mojombo** [comment]
Very strange. I'm able to open TOML files with TextEdit on my computer. Have you tried other editors, like Vim or Emacs or Atom or such?

You can also try using `hexdump` to see the raw bytes and verify that it's still in UTF8:

```terminal
$ hexdump whatever.toml
```

The fossil warning seems to be an unrelated line ending issue (Windows vs Mac vs Linux). That's a whole separate bag of worms. =)

**Comment by jbshirk** [comment]
There is a complex of problems at work here. First with Mavericks and Yosemite where certain editors that do 'atomic' save don't appear to write the file (as seen in Finder) until it is actually closed; Ctrl-S isn't always enough. Fossil, when committing, sometimes tries to convert CRLF to CR (depending on source filesystem from where a repo was cloned) if you don't tell it not to. This will mark TOML files as 'binary' to some editors. Sometimes the only fix is to copy the file to clipboard, delete the file, and recreate the file and paste clipboard. But avoiding certain editors helps a lot.

There are whole bunch of editors I can no longer trust on OS X because of all this. Brackets seems ok. TextEditor is ok. 

Atom is way too slow when a file gets up to ~100 lines. TextSoap is not reliable.
