### ISSUE TITLE
Case insensitive true/false

### ISSUE THREAD

**Issue by jodastephen** [toml-lang/toml#390]
The boolean values `true` and `false` should be case insensitive. Currently, the `E` in floating point and the `T` and `Z` in date-time are case insensitive, but booleans are case sensitive - an unnecessary inconsistency.

**Comment by mojombo** [comment]
A fair point. I honestly don't like that the E, T, and Z are case insensitive, but the T and Z come from RFC 3339 and it would be weird to contradict that. As such, I could be convinced to make booleans case insensitive. What do you think @BurntSushi @ChristianSi?

**Comment by ChristianSi** [comment]
@mojombo I'm against making these literals case-insensitive. They are case-sensitive in all major languages I'm aware of, except for SQL (which is pretty old) and YAML (which...well, I know what you think!). Table names and keys in TOML aren't case-insensitive, so why should literals be?

Having case-insensitive single letter markers is another matter and I agree that we should follow RFC 3339 in allowing case-insensitive T and Z. Following the principle of least surprise, that should apply to the E in floats as well.

But having case-insensitive multi-letter literals would also allow oddball spellings such as "trUE", and what would be the purpose of that? On the other hand, YAML allows just the more reasonable spellings, [accepting](http://yaml.org/type/bool.html) (among other things) "true|True|TRUE|false|False|FALSE". In a way, that makes more sense than full case-insensitivity, but it is also a pretty ugly way of defining things.

So no: lets keep it simple and stick with lowercase.

**Comment by BurntSushi** [comment]
I'm in complete agreement with @ChristianSi on this one.

**Comment by mojombo** [comment]
Ok, cool, I agree. Let's keep it as is, I'm always in favor of fewer arbitrary choices. Thanks all!

**Comment by nobozo** [comment]
I know it's late, but I ran into this case issue right away when trying to use TOML. In my case (sic) I was trying to parse a DNF configuration file (the Fedora replacement for Yum). In Fedora 28 /etc/dnf/dnf.conf (an .INI-style file) contains the  line

clean_requirements_on_remove=True

which isn't valid according to TOML. That's discouraging.

**Comment by eksortso** [comment]
Er... To be diplomatic, I'll add that the spec for dnf's configuration files is linked below. It isn't TOML-compliant, and was never intended to be.
http://dnf.readthedocs.io/en/latest/conf_ref.html
