### ISSUE TITLE
Don't be so specific about what numbers with decimal points mean

### ISSUE THREAD

**Issue by seagreen** [toml-lang/toml#392]
Would it be better to follow JSON's lead (on just this one thing) and not specify that numbers with decimal points are floats? JSON just calls them numbers and leaves it up to the program how to interpret them (http://www.json.org/). This is nice because specifying that they're floats adds a lot of complexity that isn't wanted for things like financial applications.

(Feel free to close this if it's not a productive question, but I really like the goal of an "obvious, minimal language" and wanted to suggest something that may help with it)

**Comment by treehau5** [comment]
It seems as the goal of toml is to map closely, as easily as possible, to the target language's data structures.

 In that vein, most languages interpret numbers with a decimal as a float, and that would seem to be the most obvious.

**Comment by seagreen** [comment]
Right, there's definitely a tradeoff here. Mapping directly to language data structures is great. But on the other hand you'd prefer that map to be an accurate one. Floats aren't really a good match for "numbers with decimal points", to use the most banal example you can't write `0.1` convert it to a float and back, and expect to get `0.1` again.

Say you want to write a GUI to modify human written TOML documents. The natural choice would be to convert the TOML to a data structure in your language, let the user change some values, and then write it back to TOML. But since this will clobber even the unmodified numbers in your document (`0.1` to `0.10000000000000001`) a better strategy would be to use an incorrect data structure (specifically not representing TOML numbers as floats) converting to floats only when the user modifies the value.

Anyway, I agree there's a tradeoff, I just don't want the cost of applications having to build two representations for TOML (the `0.1` invalid TOML but accurate data one and the `0.10000000000000001` valid TOML but changed data one) to go unnoticed.

**Comment by tshepang** [comment]
Rather than have the spec be ambiguous (leaving the application to decide), I would rather a different type be specified for this special case for money, say 'cost = $15.99'. This makes me curious if other config formats actually support such types.

Failing that, given this is a special case, I guess you could always fall back to string... 'cost = "15.99"'.

**Comment by mojombo** [comment]
If roundtripping a float value unchanged is desirable, the host application could certainly do so, and in fact, to keep the order of lines in the source document the same, you'd have to do something fancy anyhow. At the same time, if this peculiarity of floats causes consternation, it's probably best not to use floats. =)

**Comment by seagreen** [comment]
I think users of a markup language are much more likely to want decimals than floats (which is different than my view when I opened the issue and suggested making them unspecified), but it's your language.
