### ISSUE TITLE
Note about v0.2.0 only compatibility with "Language Agnostic Test Suite"

### ISSUE THREAD

**Issue by robmuh** [toml-lang/toml#406]
Took me a while to realize the "Language agnostic test suite for TOML decoders and encoders" only supports `v0.2.0` and not `v0.4.0` of the spec. Might be worth adding a note in the README to that section calling that out for others.

I seems like it would make the most sense to reference a validator that actually validates the current version v0.4.0.

**Comment by pradyunsg** [comment]
Now that the test suite has been updated, this issue can be closed. :)
