### ISSUE TITLE
Examples do not reflect Tom's original specification and examples

### ISSUE THREAD

**Issue by robmuh** [toml-lang/toml#407]
The main site is NOT v0.4.0, maybe it is v0.4.1 or something, but not 4.0:

![screen shot 2016-04-21 at 1 19 41 pm](https://cloud.githubusercontent.com/assets/3749067/14718471/da366bca-07c4-11e6-8199-f7d33b6baae9.png)

You have created a situation where all the people reading docs about TOML are following incorrect information that even the most modern implementations do not support, because they are using the **_actual**_ v0.4.0 specification. This is a worst possible scenario when it comes to specification management.

Here is what you have added to the main page that breaks most implementations. Notice that single quoted bare strings were **_not**_ allowed in v0.4.0, but you have them on the main page as valid v0.4.0.

<img width="920" alt="screen shot 2016-04-21 at 8 46 38 am" src="https://cloud.githubusercontent.com/assets/3749067/14715878/996c5962-07b8-11e6-854a-760173f71f3b.png">

This has been frustrating.

**Comment by robmuh** [comment]
Looks like Tom changed to allow single-quoted keys [here](https://github.com/toml-lang/toml/commit/6eaface3d936468b98f643f84bd6007bcc2eada8) on Jan 25, 2016 well after Feb 12, 2015 when v0.4.0 was tagged and pre-released, which means @mojombo simply didn't make another release before handing it off. So the question remains what do we call it? Maybe we should remove it entirely from the site since it is not v0.4.0.

**Comment by BurntSushi** [comment]
The README says the *latest* tag is 0.4.0. It links to the `0.4.0` spec. It also says:

> Be warned, this spec is still changing a lot. Until it's marked as 1.0, you should assume that it is unstable and act accordingly.

We've been marching toward 1.0, albeit at a snail's pace. Changes have mostly settled down at this point. I'd personally be against most or all breaking changes at this point---too much has become de facto stable. Certainly, some implementations need to play catch up (including mine and the test suite).

FWIW, @mojombo is still the lead maintainer.

**Comment by robmuh** [comment]
So my question is why not have created a branch for all the new work instead of adding information that everyone would read on the main readme? I'm not the only one. Everyone wanting to know what Frontmatter they can put in Hugo, for example, is wondering two things: why their inline tables don't work and why (god forbid) their single quoted key names are not supported.

**Comment by BurntSushi** [comment]
The Hugo project might consider linking to the version of the spec that they support. Even if the main `README` was stuck at `0.4.0`, there's no guarantee that Hugo actually supports `0.4.0`.

**Comment by robmuh** [comment]
Unfortunately Hugo is stuck at v0.2.0 since it uses your toml instead of one of the many that support v0.4.0 (as released, not as shown on the main page).

**Comment by BurntSushi** [comment]
My TOML library does note that it is using `0.2.0`. So even if this repo were pinned to `0.4.0`, you still would have run into problems. I think the best solution here is to request that upstream state which version of TOML is available.

**Comment by robmuh** [comment]
Thanks for your suggestions. I do understand why all this has happened better and certainly appreciate all the amazing contributions everyone has made. 

Honestly, I started out just as a Hugo user who read [this about front matter](http://gohugo.io/content/front-matter/) and simply read the linked doc there while considering a blogging framework to teach my students who enjoy Go. This was the first time I had heard about TOML so, of course, read everything I could about it—on the wrong page, lol. I am simply trying to avoid that problem for students to come.

![screen shot 2016-04-21 at 4 00 01 pm](https://cloud.githubusercontent.com/assets/3749067/14722575/221fa54a-07da-11e6-9a3b-ebba83becbb0.png)

This link is likely the first place many people on the planet will see the letters TOML and just hoping to reduce as much misunderstanding as possible. I am more than happy to document anything needed. In fact, I took a shot at an icon:

![toml-spec](https://cloud.githubusercontent.com/assets/3749067/14722664/8dcc6346-07da-11e6-9a79-5af06f40e45e.png)

I have SVG and AI if something that might work temporarily, @mojombo approving, of course.

**Comment by jdfergason** [comment]
@robmuh awesome icon ... +1 from me

**Comment by pradyunsg** [comment]
I think this can be closed.

@mojombo or @BurntSushi would have confirm but as far as I can tell, right now, the README file is not a "released" TOML spec -- it's just an in-progress variant of the next version. Actual releases would mean files are placed in `versions/` and named accordingly.

**Comment by mojombo** [comment]
@pradyunsg That's correct, however I definitely see @robmuh's point that doing ongoing development on the `master` branch could be confusing for newcomers that are operating with 0.4.0 implementations. After 1.0 we can think about changing how this works, although I'd love to have a proper website in place that will take over as the main place to learn about TOML, hopefully obviating the need.

**Comment by pradyunsg** [comment]
@mojombo toml-lang.github.io or are you thinking of registering a top level domain?

**Comment by mojombo** [comment]
I have the toml.io domain for just such purposes!

**Comment by pradyunsg** [comment]
Oh perfect. :)
