### ISSUE TITLE
Distinguish between dates and times

### ISSUE THREAD

**Issue by RobertBColton** [toml-lang/toml#412]
I've recently been prototyping an application where we are generating the UI in Qt Framework from toml files. Everything has been going good so far but we've hit a bit of an edge case. In Qt there are separate QTimeEdit, QDateEdit, and QDateTime editor widgets. It is impossible to determine using a toml implementation whether the toml file had only a date or only a time or both. This makes it difficult to generate the correct editor widget for the UI, we always have to use QDateTime and just ignore the date or the time if we don't want it. I wanted to mention this particular use case and suggest a separate DATE, TIME, and DATETIME type for the toml specification.

**Comment by mojombo** [comment]
See #414 for the latest proposal (and #362 for a long discussion leading up to it).
