### ISSUE TITLE
Add xpath-like specification

### ISSUE THREAD

**Issue by dkrikun** [toml-lang/toml#419]
Please add specification to access a value by a path.

Rationale: it is said that "TOML is designed to map unambiguosly to a hash table". Thus we need a way to define a "key" to access a value in an unambigous manner.

**Comment by mojombo** [comment]
I'm not sure I follow. You can use a dot-separated key-path to unambiguously denote a value:

```toml
[a.b.c]
key = "val"
```

```
a.b.c.key #=> "val"
```

Please reopen this issue if I'm misunderstanding.

**Comment by fabiomontefuscolo** [comment]
very unlikely, but technically possible (I suppose) 

```toml
[a.b.c]
key = "val"

[a.b]
c = {key = "val"}
```

Maybe it could be addressed by an idea like

- for the first
```
/a.b.c/key
```

- for the second
```
/a.b/c@key
```

I think it more or less looks like xpath (https://www.w3schools.com/xml/xpath_syntax.asp)

- `/` selects nodes
- `@` selects properties

and also, maybe, `[n]` to select the index `n` in arrays
