### ISSUE TITLE
Port of the ReadMe to a LearnXinYminutes tutorial

### ISSUE THREAD

**Issue by aloisdg** [toml-lang/toml#420]
Hello,

In my way to learn TOML, I decided to port the ReadMe to a LearnXinYminutes tutorial. You can see the current PR: [Add TOML support](https://github.com/adambard/learnxinyminutes-docs/pull/2282). Feel free to make any review to improving it. 

Cheers,

[Official website](https://learnxinyminutes.com/)

**Comment by mojombo** [comment]
Awesome work! Keep your eye on upcoming TOML releases (including a 1.0 soon, I hope), it would be great if you could keep your tutorial up to date as things progress. Cheers!

**Comment by aloisdg** [comment]
@mojombo I will do my best!
