### ISSUE TITLE
The "Comparison" section doesn't state if there would be any pitfalls to using TOML for data interchange

### ISSUE THREAD

**Issue by benrob0329** [toml-lang/toml#422]
Its probably unnecessary, but Readme.md touches on data exchange, but doesn't state if there if there would be any obvious pitfalls to using it for data exchange program to program. 

It could give newcomers (such as myself) a better understanding of usecases if such details were expanded upon.

**Comment by pradyunsg** [comment]
I think we'd be happy to accept a PR for this.

**Comment by LucidOne** [comment]
Here are some issues using yaml for embedded data interchange.
https://github.com/yaml/yaml/issues/41

Personally, I think the `---` and `...` document markers are useful for notifying endpoints that a unit of data is ready for processing without closing a connection. The lack of a header also means data must be identified by something other than [magic](https://en.wikipedia.org/wiki/List_of_file_signatures).

**Comment by pradyunsg** [comment]
I welcome PRs for fixing this issue. Please feel free to file a PR and post a comment here if you do. :)

**Comment by workingjubilee** [comment]
I believe something like #636 is what you were looking for?

**Comment by pradyunsg** [comment]
@workingjubilee Yes, almost! :)

**Comment by workingjubilee** [comment]
Cool, hopefully this wraps that up and answers @benrob0329's question (and also answers a few recurring issues generally?)!

**Comment by pradyunsg** [comment]
It does! Thanks @workingjubilee!
