### ISSUE TITLE
Suggestion: Allow colons inside bare keys

### ISSUE THREAD

**Issue by jleclanche** [toml-lang/toml#425]
From the README:

> Keys may be either bare or quoted. Bare keys may only contain letters, numbers, underscores, and dashes (A-Za-z0-9_-). 

I'd like to suggest allowing colons in bare keys. Colons are useful as key names for namespacing keys without creating sub-structures. Example:

``` toml
types = ["file", "folder"]
file:name = "foo"
folder:name = "bar"
```

Would result in the expected:

``` json
{
  "types": ["file", "folder"],
  "file:name": "foo",
  "folder:name": "bar"
}
```

Currently, colons are not used anywhere in TOML _except_ in datetimes. Allowing them in keys should cause no conflict or additional complexity.

There is an argument to be made that "if colons are allowed, maybe `chr(ord(':') + 1)` should be allowed as well" - but I'm not here to argue for that, only bringing up colons for evaluation.

**Comment by lmna** [comment]
It is not instantly obvious what does colon in bare key mean. Colons provide intuitive syntax for names composition, if it would be necessary to add some kind of prefixes/nested_keys/namespaces/etc in the future.

**Comment by Hrxn** [comment]
I like the idea..

I have seen it somewhere else, colons used as a free separator in identifiers, I think it's useful.

**Comment by skystrife** [comment]
Why are quoted keys insufficient here?

**Comment by mojombo** [comment]
You can already use dashes or underscores for this purpose! The consuming application could easily specify that as the working mechanism.

``` toml
types = ["file", "folder"]
file-name = "foo"
folder-name = "bar"
```

Or, as was already suggested, you can always use quoted keys.
