### ISSUE TITLE
Suggestion: EOD tag

### ISSUE THREAD

**Issue by mbakke** [toml-lang/toml#429]
Currently there is no way to verify that a TOML document is "complete". Having a closing tag would allow parsers to reject TOML that is only partially read, similar to when JSON is missing the closing bracket.

This is useful when sending TOML over a network, for example.

**Comment by veeg** [comment]
TOML is not a serialization format. Adding any logic that reduces the human-friendly configuration format (ref: @mojombo [comment](https://github.com/toml-lang/toml/issues/263#issuecomment-70174222)) is ill-advised in my honest opinion.

**Comment by TheElectronWill** [comment]
When sending TOML over a network, you usually send the document's length first. So no need for an "EOD" tag in that case.

**Comment by mbakke** [comment]
Fair points. I guess some network transports can take care of validation. From the linked issue, there seems to be some expectation that TOML can be used as a general serialization format. Perhaps a "strict mode" that requires opening and closing tags could work, but I agree that it would be neither obvious nor minimal to require it in normal use.

**Comment by mojombo** [comment]
I think @TheElectronWill's arguments against a closing tag are on point, and I don't see a compelling need for this. Thanks for the suggestion anyhow!
