### ISSUE TITLE
Move list of 3rd-party tools to wiki

### ISSUE THREAD

**Issue by moorereason** [toml-lang/toml#430]
This is a relatively minor detail, but I'm recommending that the list of 3rd-party tools and implementations in the README be moved to the wiki pages.  Updates to the README about 3rd-party tools creates a lot of noise in the git log.  The tools are great, but most of the updates this year don't have anything to do with actual changes or clarifications in the spec.  I'd prefer the git log be about the spec itself and not about the community.

Thanks for considering it.

**Comment by pradyunsg** [comment]
@mojombo I really think this should be done -- or this information moved into another markdown document.

Do you think there's merit to moving this information out of the README?

**Comment by alexcrichton** [comment]
Out of curiosity, was the wiki intended to be a publicly editable resource? The first rule seems to imply that:

> Be careful when editing this document. It's a valuable resource, so proofread your work and make sure it's right.

but unfortunately I don't think I have an edit button at least :(
