### ISSUE TITLE
What's the point of empty quoted keys?

### ISSUE THREAD

**Issue by Lucretia** [toml-lang/toml#432]
> A bare key must be non-empty, but an empty quoted key is allowed (though discouraged).

Seems completely pointless to allow this, why not just disallow it?

**Comment by mk-pmb** [comment]
I'm sure there are a lot more keys that you'd deem pointless. How about keys consisting of just space characters? We should consider a whitelist approach here, and only allow keys that our chosen wise experts deem valuable.

**Comment by BurntSushi** [comment]
@mk-pmb I'd appreciate it if you could be more constructive in future comments. As it stands, your comment isn't very helpful.

In any case, disallowing empty keys would be a breaking change, and I don't think we should be making any breaking changes at this point.

**Comment by Lucretia** [comment]
@BurntSushi didn't answer the question. I wanted to know what they are useful for? I cannot see a point to this.

**Comment by BurntSushi** [comment]
I don't have a good answer for you. If I did, I would have given you one.

**Comment by mk-pmb** [comment]
Use case example: In [xmlattrdict](https://www.npmjs.com/package/xmlattrdict) I use the empty string key for the tag name. Ideally I'd use `null` as a key, to indicate that the entry is in the dict just for convenience even though it's not really a key-value-pair like the attributes. I can't use actuall null in ES5, so the empty string was the closest equivalent I could find.

**Comment by Lucretia** [comment]
@mk-pmb thanks, think  i'll experiment with one of the libs.
