### ISSUE TITLE
UTF-8 byte order mark

### ISSUE THREAD

**Issue by mk-pmb** [toml-lang/toml#437]
Let's add a rule whether a BOM at start of file is allowed, required (<-- probably not) or forbidden. I'd prefer allowed (optional in files, required to accept for parsers).

**Comment by BurntSushi** [comment]
It has to be allowed since it is valid UTF-8. I guess parsers will need to look for it and ignore it though.

Making it required is not an option.

**Comment by mojombo** [comment]
As @BurntSushi said, UTF-8 documents already allow for an optional BOM. But the spec currently says "A TOML file must contain only UTF-8 encoded Unicode characters." which, while suggesting that a TOML file is a UTF-8 document, does not actually say that. Fix imminent.
