### ISSUE TITLE
Tests do not actually test many language features

### ISSUE THREAD

**Issue by tobia** [toml-lang/toml#440]
I've been testing the PHP libraries that attempt to support v0.4.0

All the ones I could find, including the two listed on the front page, fail to parse arrays of sub-tables `[[table.sub_table]]` and inline tables `{...}` correctly.

The simple reason is that the tests inside the `tests` folder in this very repository **do not test these two things, as well as many other TOML features.**

The tests are currently very incomplete and are producing a number of incomplete / buggy libraries. Having no official test would be even better than incomplete tests, because at least it would force library developers to actually write tests for all the language features.

**Comment by StefanKarpinski** [comment]
This issue would be more helpful with some examples of features that aren't tested. I have to say that an argument that incomplete tests are worse than no tests strikes me as perverse. How does one get to the nirvana state of having complete test coverage? In a single ginormous pull request?
