### ISSUE TITLE
How do you pronounce "toml" when you are reading it out loud?  As in "Cargo.toml"

### ISSUE THREAD

**Issue by CleanCut** [toml-lang/toml#447]
I'm making an instructional video course for Rust, which uses .toml files in it's package management system.  When I'm saying "Cargo.toml" out loud to my learners, how should I pronounce .toml?

I'm assuming (and hoping) that there's "one right way" to say it, so we don't end up with perpetual gif-vs-jif-like wars.

**Comment by BurntSushi** [comment]
tom-el

**Comment by CleanCut** [comment]
Thanks!
