### ISSUE TITLE
ABNF forbids comments in empty arrays

### ISSUE THREAD

**Issue by alexcrichton** [toml-lang/toml#448]
I wouldn't necessarily consider myself an ABNF expert by any means, but I think that a document such as this would be rejected?

```toml
foo = [
    # bar
]
```

Is this a bug or intentional? (it'd be great if it were a bug!)

**Comment by BurntSushi** [comment]
I haven't looked at the ABNF yet to confirm, but if the ABNF does indeed reject this, then I'd consider it a bug in the ABNF.

**Comment by jjpe** [comment]
I just ran into a use case in which an empty array would be useful. 
Basically what I want to do is to allow users to specify zero or more files while handling all 3 multiplicities (0, 1, many) uniformly, and by default I want to put a comment in there to conveniently explain to the user what can be done there.

The best abstraction I can think of in this context is an array that also allows emptiness, and that works both with and without comments in all 3 multiplicities.
