### ISSUE TITLE
abnf clarrifications

### ISSUE THREAD

**Issue by ehuss** [toml-lang/toml#473]
There are a couple things that were unclear to me comparing the ABNF and the README.

What characters are allowed in literal strings?  The README is not explicit, generally saying "strings without escapes", but the ABNF is explicit with `%x09 / %x20-26 / %x28-10FFFF`.

Can quoted keys use literal strings?  The README says they are basic or literal strings, but the ABNF uses only `quotation-mark`.

**Comment by a-teammate** [comment]
related maybe a bit to #464?

**Comment by pradyunsg** [comment]
> Can quoted keys use literal strings?

Yes. This is fixed in #491.

> related maybe a bit to #464?

I don't think sp.

> The README is not explicit, generally saying "strings without escapes", but the ABNF is explicit with %x09 / %x20-26 / %x28-10FFFF.

In discussion at #474.
