### ISSUE TITLE
Permit horizontal tabs (ascii 9) in strings

### ISSUE THREAD

**Issue by jvasileff** [toml-lang/toml#474]
The spec states:

> Basic strings are surrounded by quotation marks. Any Unicode character may be used except those that must be escaped: quotation mark, backslash, and the control characters (U+0000 to U+001F).

which seems to indicate that the horizontal tab character is an illegal control character. Is that right?

`toml.abnf` seems to be split on the matter, allowing `%x09` for `literal-string` and `ml-literal-string` but not for `basic-string` and `ml-basic-string`.

**Comment by pradyunsg** [comment]
@jvasileff Horizontal Tab falls within U+0000 and U+001F -- it's U+0009.

You can't use a horizontal tab directly within a basic string, as the spec states. You have to escape it. The best way probably is to just write `\t`.

You can use a horizontal tab in a literal string where you do not escape any characters. Just put that character and you're good to go.

**Comment by pradyunsg** [comment]
If that addresses your concern, please close this issue. :)

**Comment by jvasileff** [comment]
@pradyunsg thanks for the workaround, but this is about altering the spec or at least clarifying it. When writing a TOML parser, I found the restriction against `%x09` within strings to be a bit strange, and given the wording of the restriction and lack of consistency with the rules in `toml.abnf`, perhaps an unintended restriction.

> You can use a horizontal tab in a literal string where you do not escape any characters. Just put that character and you're good to go.

That's actually part of the problem. The spec doesn't indicate that control characters are legal in literal strings, so it would seem literal strings cannot contain tabs *at all*.

For literal strings, the spec has:

> If you're a frequent specifier of Windows paths or regular expressions, then having to escape backslashes quickly becomes tedious and error prone. To help, TOML supports literal strings where there is no escaping allowed at all. Literal strings are surrounded by single quotes.

which (for a spec) is pretty vague, and doesn't mention control characters at all.

For multi-line literal strings, the spec does at least explicitly state that newlines are allowed, but again, no mention of control characters:

> Multi-line literal strings are surrounded by three single quotes on each side and allow newlines.

**Comment by pradyunsg** [comment]
Ah right. I might have misread.

I just re-read the OP and the text in the spec and, agree with you. The spec does indeed seem pretty vague. I guess it could use a revisit. :)
