### ISSUE TITLE
Please update implementation section with compliance information

### ISSUE THREAD

**Issue by ooxi** [toml-lang/toml#477]
Please update the [implementation section](https://github.com/toml-lang/toml#implementations) with information about compliance as generated by [toml-test](https://github.com/BurntSushi/toml-test). For example the most popular PHP TOML library does not support essential features like inline tables or nested tables.

**Comment by pradyunsg** [comment]
This would be partially addressed by #430 -- where it could be noted that this is the case.

**Comment by pradyunsg** [comment]
Or... The libraries should note which version of TOML they support. I think that's a much cleaner way to do this.

Maybe if we split out the lists at the end of the document to another separate document, it would make sense to have a note there for the libraries should be the ones to document which version of TOML they support.

**Comment by alexcrichton** [comment]
@pradyunsg it looks like this may be mostly covered with the move from the readme to the wiki, but I'd also say that I personally at least found the version compliance in the wiki pretty useful as it allows you to just glance at "up to date parsers" which while not relevant years after 1.0 is still relevant for toml which is a slightly changing specification. I wonder if perhaps something like a year after 1.0 the wiki is gc'd (aka archived) and then all parsers are assumed to state their compliance as long as it's minimum 1.0?

**Comment by ooxi** [comment]
I no longer have my test case available, however I think the library I used claimed to be 0.4.0 compatible while not supporting inline or nested tables.

Since I currently do not have the time to do a compliance test myself, I'm closing this issue.
