### ISSUE TITLE
Time for one-dot-oh Mr. Tom!!!

### ISSUE THREAD

**Issue by jhabdas** [toml-lang/toml#479]
Howabout it, ya?

http://semver.org/#how-do-i-know-when-to-release-100

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

**Comment by BurntSushi** [comment]
Dupe of #330

**Comment by ChristianSi** [comment]
Maybe a few duplicates couldn't hurt to increase the urgency of this? It feels sad that the TOML spec, though theoretically almost stable, is practically dead because of lack of proper maintainership 😞

**Comment by jhabdas** [comment]
@ChristianSi No worries! I dropped a comment in the duplicate to trigger some renewed interest. The good thing is [hugo](https://github.com/gohugoio/hugo) has ~20K stargazers now and many of them with themes, like myself, love and use TOML every day.
