### ISSUE TITLE
Format and Syntax check tool

### ISSUE THREAD

**Issue by kennygrant** [toml-lang/toml#48]
As you want there to be one way to do everything, you could consider having a simple tool to reformat toml files in a canonical style tomlfmt, like gofmt for go, to prevent bikeshedding over minor formatting/styling issues, and perhaps later to detect any syntax errors and emit friendly messages on how to fix them.

**Comment by vmchale** [comment]
@kennygrant I have no idea if you're still looking for such a tool, but I have a syntax checker: https://github.com/vmchale/tomlcheck
