### ISSUE TITLE
Ambiguities Specification: missing value

### ISSUE THREAD

**Issue by maiha** [toml-lang/toml#480]
I can't find specs about missing value. Is this valid? or invalid?

```toml
key =
```

I'd like to clarify this and give feedback to specifications and BurntSushi's test-suite.

### FYI

- validator: https://github.com/BurntSushi/toml/tree/master/cmd/tomlv
```
% tomlv unknown.toml
Error in 'unknown.toml': Near line 1 (last key parsed 'key'): expected value but found '\n' instead
```
- JavaScript:  https://github.com/BinaryMuse/toml-node
```
SyntaxError: Expected "'", 
```
- ruby: https://github.com/emancu/toml-rb
```
Failed to parse input on line 1 at offset 5 (TomlRB::ParseError)
```

**Comment by eksortso** [comment]
The spec says that the assigned value must be a "String, Integer, Float, Boolean, Datetime, Array, or Inline Table." All types require non-empty syntax. Even empty strings have explicit syntax, using quotes.

So, unspecified values are invalid.

I think that the meanings of empty values may be taken up again after TOML 1.0 is released. But for now, empties are verboten.

**Comment by maiha** [comment]
I see. Thanks so much!

> The spec says that the assigned value must be a 

One point. It seems `README.md` says not **must** but **may**.
> Values may be of the following types: String, Integer, Float, Boolean, Datetime, Array, or Inline Table.

I'll create a PR about this.

Thanks again.

**Comment by eksortso** [comment]
Glad to help. And thanks for catching what I didn't: the word **may** is currently in use, and ought to be **must**, since what else could it be?

Hope to see your PR soon, and hope it gets pulled quickly.
