### ISSUE TITLE
how to add default value in toml

### ISSUE THREAD

**Issue by rfyiamcool** [toml-lang/toml#489]
see title ?

**Comment by TheElectronWill** [comment]
What do you mean exactly?
I think that what you want is handled by toml librairies not by the language itself.

**Comment by pradyunsg** [comment]
What @TheElectronWill said.

@rfyiamcool TOML is a configuration file format. Implementing fallbacks and default values is something that has to be done by the application using TOML, not in the language itself.

If that addresses your concern, could you please close this issue?

**Comment by mojombo** [comment]
I agree with the others. Please re-open if you have more to discuss. Thanks!
