### ISSUE TITLE
add variable support？

### ISSUE THREAD

**Issue by pzzp** [toml-lang/toml#496]
Maybe it will be useful.
Like this:
`host = "github.com"`
`toml_homepage = "${host}/toml-lang/toml"`

 :)

**Comment by pradyunsg** [comment]
Hi!

I'd say this is something that would be something that consumer of TOML should be doing. Given that it's possible already to do this on top of TOML with basically the same effect, I don't think this should have support at the langauge level.

**Comment by lmna** [comment]
Proposed syntax interferes with posix shell syntax. Ability to inline shell scripts to configuration file is highly desirable in some domains.

**Comment by lmna** [comment]
Names of variables are actually paths. Paths can be either absolute or relative. Now, how should relative paths work inside of nested combinations of arrays and hashes? At first glance, complexity of this feature is far beyond "obvious".

**Comment by pradyunsg** [comment]
Also... #255.

**Comment by mojombo** [comment]
Yep, I think variables and the like (as in #255) are outside the scope of TOML to deal with. TOML is designed to fill the needs of people with simple config requirements. There are other solutions for those with more complicated needs. Also, host programs that really want something like this can indeed specify as much in their documentation and use strings however they please (as suggested).
