### ISSUE TITLE
Bring ABNF into Specification (README)

### ISSUE THREAD

**Issue by pradyunsg** [toml-lang/toml#498]
For discussing what was proposed in https://github.com/toml-lang/toml/pull/491#issuecomment-345242228.

I had a concern that the various snippets are cross-referencing but it'd not be obvious at first glance... that changed when I looked at the JSON spec.

The only thing worth mentioning would be that -- add a line at the top of the spec whenever this is done to link to the ABNF spec.

If it's cool, I don't mind making a PR for this over the weekend.

**Comment by mojombo** [comment]
Yeah, I'd love to see your take on what it would look like, and how much we could streamline things.

**Comment by pradyunsg** [comment]
> add a line at the top of the spec whenever this is done to link to the ABNF spec.

This was an ambiguous statement -- just to clarify -- I meant adding a line to the top of the TOML spec linking to the ABNF spec saying "we use the thing defined here to define TOML" (in nicer wording than that).

**Comment by alexcrichton** [comment]
Out of curiosity, would it be possible to have a section "about ABNF" in the README (or maybe even better, a wiki page?) in terms of pointing to a specification for the syntax and maybe providing a link to a tool which consumes ABNF and/or verifies it? If the tooling doesn't exist though then it seems fine to avoid this for now.

**Comment by pradyunsg** [comment]
> If the tooling doesn't exist though then it seems fine to avoid this for now.

Sounds good to me tbh. It's really just a styling thing.

**Comment by mojombo** [comment]
I think for 1.0 it's safest to leave the ABNF out, and not even reference it in the spec. It's too risky to refer to it as authoritative until it has more time for a robust verification. Once we are more confident in the ABNF, then we can start evangelizing it properly.
