### ISSUE TITLE
Double backslash for escaped characters

### ISSUE THREAD

**Issue by jhamrsky** [toml-lang/toml#510]
ABNF specifies escaped characters as 
```
escaped = escape escape-seq-char
escape = %x5C                          ; \
escape-seq-char =  escape %x22         ; "
...
```
but that would (AFAIK) mean, that for escaped characters user needs to write two backslashes (because `escape` is in fact present twice). This is somewhat in contradiction to samples available, where only one backslash is used (eg. `"I'm a string. \"You can quote me\" .. "`).

Is this intended or there is some part explaining that I am wrong about this one?

**Comment by mojombo** [comment]
Indeed, that is a mistake in the ABNF. Good catch, I'll get it fixed.
