### ISSUE TITLE
PHP compiled TOML extension using zephir

### ISSUE THREAD

**Issue by betrixed** [toml-lang/toml#523]
PHP TOML parser, orgininally forked from Yosymfony/Toml, but now quite a different beast.
Links are
- PHP (@betrixed) - https://github.com/betrixed/toml
- PHP (@betrixed) - https://github.com/betrixed/toml-zephir

The toml-zephir project compiles to a PHP-extension, using Phalcon - Zephir, with the same interface as the PHP project.

Interesting feature - Demonstrates a generalised method of specifying table paths.
Understands [table.[ArrayOfTable].leaf] and other combinations, instead of just having [[table.ArrayOfTable.leaf]]       

Any internal path segment with inner brackets is Array of Tables.
Any plain internal path segment is plain Table.

**Comment by eksortso** [comment]
Could you explain the "interesting feature" a bit more? There's been some discussion (#309) swirling around the syntax for arrays of tables. What syntax does this extension recognize?

**Comment by pradyunsg** [comment]
Looks like OP is suggesting an alternate syntax for arrays of tables. I've noted it in #309 and I think this issue can be closed now. :)
