### ISSUE TITLE
new tiny TOML parser written in javascript

### ISSUE THREAD

**Issue by Jonarod** [toml-lang/toml#524]
Hey ! Loving TOML, but I had to make a few tweaks to the specs for a project I have.

In fact, TOML was an obvious choice (:stuck_out_tongue: ) however, my project needed to be a bit more kind to users mixing YAML's `key : value` with TOML's `key = "value"`... plus I needed another behavior regarding errors: if syntax is incorrect, only the relevant entry should be ignored without throwing the whole app...

For this reason, I created [markty-TOML](https://github.com/Jonarod/markty-TOML) with tiny footprint of 800 bytes and blazing-fast :)

Just wanted to share my work here in the wiki section, but I really don't know where this project should belong? It is not v0.4 compliant per say, even though it comes with all features, so... any suggestion ?

**Comment by pradyunsg** [comment]
Hey @Jonarod! That's a neat library.

Since the library isn't compliant with any of the released specs, I've gone ahead and added it as an entry to https://github.com/toml-lang/toml/wiki#unknown-or-pre-v010-compliance.

Hopefully, that works for you. :)
