### ISSUE TITLE
TOML File Hosting IIS

### ISSUE THREAD

**Issue by safeerk** [toml-lang/toml#526]
Team  ,
               Am integrating the Stellar (Cryptocurrency related) , for that am in need of hosting the TOML file in IIS. Can i know how it can be possible. 
Looking forward.

![image](https://user-images.githubusercontent.com/22815639/37090328-017d5416-2215-11e8-85a8-a242a35ba5d2.png)

**Comment by eksortso** [comment]
This doesn't have anything to do with the TOML standard. If you're having a problem with Stellar or with IIS, you'll need to consult their documentation. If you have a question about TOML, though, we'll be happy to address it.

**Comment by pradyunsg** [comment]
I think this issue can be closed. :)
