### ISSUE TITLE
PHP-CPP Toml 0.4 parser

### ISSUE THREAD

**Issue by betrixed** [toml-lang/toml#527]
PHP-Extension Pun\\TomlReader class , implemented using PHP-CPP.
Includes support classes, object model.
Requirements are PHP >= 7.1, shared libraries  libpcre2-8, and libphp-cpp
and C++ build environment.
As expected, it performs an order of magnitude faster than interpreted PHP code doing the same things.

[Toml-Pun8 Source Code Repository](https://github.com/betrixed/Toml-Pun8)

The C++ design was based on a Php version [Toml-Yosymfony fork](https://github.com/betrixed/toml) with modifications and test rig to suit.

**Comment by pradyunsg** [comment]
Hi @betrixed!

I understand that you want this project to be mentioned in the Wiki. Is that correct?

**Comment by pradyunsg** [comment]
I've gone ahead and added an entry for TOML-Pun8 to the Wiki.
