### ISSUE TITLE
New release with latest updates

### ISSUE THREAD

**Issue by cheshirex** [toml-lang/toml#529]
Assuming issue #515 isn't on the verge of being accepted, I'd like to see the current state at least be formalized as a release, so that existing libraries will agree to add support for newer features that aren't yet included in a formal release.

Thanks!

**Comment by pradyunsg** [comment]
> issue #515 isn't on the verge of being accepted

I'd say it is. :)

**Comment by pradyunsg** [comment]
I'll go ahead and close this issue. :)
