### ISSUE TITLE
Specific TOML syntax for defining REST APIs

### ISSUE THREAD

**Issue by Aliuken** [toml-lang/toml#533]
Add a specific TOML syntax for defining REST APIs, similar to the YAML format, where you define for each operation, identified by its path (URL) and HTTP operation (GET, POST, PUT or DELETE):
- the input data that is part of the request URL
- the input data that is part of the request body (in POST and PUT operations where the body could be a defined JSON)
- the possible HTTP response codes (200, 404, 500...)
- the possible response body (that could be a defined JSON) for each possible HTTP response code
- the types (with all their fields) for the request body and response bodies defined (that could be defined in JSON)

**Comment by pradyunsg** [comment]
To add to what @eksortso says...

This isn't something that can happen at the TOML standard level -- a specification like this would be built using TOML.
