### ISSUE TITLE
can root be array？

### ISSUE THREAD

**Issue by wang37921** [toml-lang/toml#535]
how toml show the json blow

[
    {
        'name': 'c'
    },
    {
        'name': 'j'
    }
]

**Comment by eksortso** [comment]
In TOML, the root is always a table, which is fine for a configuration format. You can't have an array up top.

But if you give that array a dummy key, then the dummy's value will be the array.
```toml
[[dummy]]
name = "c"

[[dummy]]
name = "j"
```

Alternatively:
```toml
dummy = [
  {name = "c"},
  {name = "j"},
]
```

**Comment by wang37921** [comment]
okay, thx for your reply
