### ISSUE TITLE
Bug: Comma in string in list raises IndexError: list index out of range

### ISSUE THREAD

**Issue by seperman** [toml-lang/toml#546]
```py
item = """
a = [
  [
    ",",
    ""
  ]
]
"""

toml.loads(item)
```

raises exception:

```
    587     elif v[0] == '"':
    588         testv = v[1:].split('"')
--> 589         if testv[0] == '' and testv[1] == '':
    590             testv = testv[2:-2]
    591         closed = False

IndexError: list index out of range
```

Yes, I have just one comma in the string.

**Comment by eksortso** [comment]
The TOML string in `item` is valid; `a` is set to an array of arrays of strings. The array contains one array, and that array contains `""` and `","` (an empty string and a single comma), in that order.

This, though, isn't a problem with the TOML standard, or commas in it. It's evidently a bug in a specific Python `toml` parser.

You'll want to bring the issue up over on that project. The Python library in question, or a cousin of it, is listed on PyPI here:
https://pypi.org/project/toml/
