### ISSUE TITLE
Spec Tests…

### ISSUE THREAD

**Issue by iarna** [toml-lang/toml#549]
_Edited now that 0.5 support has landed_

I'm the author of a [Node.js TOML parser and emitter](https://www.npmjs.com/package/@iarna/toml). The current version supports 0.5.

As I implemented 0.5, I wrote out a set of tests directly from the spec, as pairs of TOML and YAML files.  You can find it in [its repo](https://github.com/iarna/iarna-toml/tree/latest/test/spec-test). (And just TOML files [in the errors](https://github.com/iarna/iarna-toml/tree/latest/test/spec-test/errors) directory, as those should throw.)

Would there be interest in having that as an external project to share between parser authors?

One difficulty I ran into is that while my TOML parser supports signed 64 bit ints (on Node.js 10, with BigInts), the available YAML parsers do not. (And YAML is specified as 32 bit, so there's no reason it should.) This means that I can't assert support for that range with a YAML file. I solved this by allowing my assertions to [be JS](https://github.com/iarna/iarna-toml/blob/support-bleeding-edge-toml/test/spec-test/int-max.js) as well, but that wouldn't carry over well to other languages. If there's interest in having a shared conformance test suite, I'd be appreciate suggestions on how to represent that in a more cross-platform manner.

Is there a better venue to have these discussions, or is this the best place?

**Comment by pradyunsg** [comment]
There's a toml-test project, which had a discussion to move into this organization so that it gets a slightly more official status. That didn't happen evidently and last I checked, it's test suite was out of date.

github.com/burntsushi/toml-test

However I do think it would be sensible to reuse that setup. For the 64/32 bit issue, you can represent the integer as a mapping with 2 keys, one to a string for the type and another for the value. (toml-test does this) Then, it becomes easier to compare and work around that issue. :)

**Comment by iarna** [comment]
I'll look at integrating those after I finish up my own! Thanks for the pointer!

**Comment by iarna** [comment]
I'm now running the `toml-test` tests as a part of my test suite (though haven't merged them, they live as a test-time download, as the WTFPL makes folks who care about licenses nervous). I've also started some more [QA-type tests](https://github.com/iarna/iarna-toml/blob/support-bleeding-edge-toml/test/qa.js) ([also](https://github.com/iarna/iarna-toml/blob/latest/test/qa-error.js)).

My plan is to split all of these off into a stand-alone repo, using JSON compat w/ the burntsushi tests, but with a more generally acceptable license.

**Comment by BurntSushi** [comment]
@iarna I just relicensed it to MIT. (I did a similar thing for my own TOML library.)

**Comment by iarna** [comment]
@BurntSushi Awesome!

**Comment by iarna** [comment]
@BurntSushi I'll move further discussion over to your repo then. =)
