### ISSUE TITLE
ABNF doesn't match text readme re whether solidus (slash) is allowed as escape character

### ISSUE THREAD

**Issue by rmunn** [toml-lang/toml#552]
https://github.com/toml-lang/toml/issues/271 suggests that the `/` character is invalid as a backslash-escape (e.g., the string `"foo\/bar"` would be invalid and should just be written as `"foo/bar"`). But in the [toml.abnf file](https://github.com/toml-lang/toml/blob/357a4ba6782e48ff26e646780bab11c90ed0a7bc/toml.abnf) as of today (2018-08-02), `%x2F` (solidus/slash) is still listed as part of the `escape-seq-char` sequence.

From #271 it seems that the intent is for `\/` to be invalid, so `%x2F` should be removed from the ABNF version of the spec.

**Comment by eksortso** [comment]
Are there modern parsers that, after three years, still escape slashes?
And more to the point, is there anything preventing us from updating the ABNF to match the spec?

**Comment by pradyunsg** [comment]
I'm on board to do this.
