### ISSUE TITLE
-0500 and -05:00 Time Zone support?

### ISSUE THREAD

**Issue by robmuh** [toml-lang/toml#555]
Having just read the RFCs (including 822 referenced by the `date` command, which does not have anything I can find related to the offset syntax), I have to ask if it would be worth adding support for the `strftime` `%z` format for time zone, that is easily produced from the `date` command and others. 

Although possible, it is not trivial to produce the same timezone offset with a colon delimiter.

Personally I cannot think of any compatibility issue that would raise, it would simply make the colon optional. 

Thoughts?

**Comment by bitwalker** [comment]
RFC 3339 restricts the date/time syntax to a subset of ISO-8601 deliberately due to the complexity of the latter, and that subset requires the colon delimiter.

If we wanted to be more flexible, then full ISO-8601 compatibility might be desirable, but it's definitely a breaking change.

**Comment by robmuh** [comment]
True. Thanks. However, upon further review I have to ask if the other RFC 3339 formats are supported (or will be). It was while creating an `isotime` utility in Go that I read the following supported formats from that RFC in addition to those listed on the TOML page:

```
 RFC3339     = "2006-01-02T15:04:05Z07:00"
 RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"
```

https://golang.org/pkg/time/

I personally prefer the format on the TOML page with the - and + and with Z having specific meaning without the additional digits following, but clearly the RFC allows for these and so perhaps the TOML spec should clarify this limitation (or allow for it).

**Comment by bitwalker** [comment]
My reading of the RFC doesn't lead me to believe that format is part of the spec, [namely here](https://tools.ietf.org/html/rfc3339#section-5.6). That grammar specifies _either_ `Z` or an offset, not both combined. I suspect that's an extension supported by Go, but perhaps I'm missing something.

**Comment by robmuh** [comment]
I completely agree and in this case feel Go has a rather significant flaw in the format of the constant carrying the RFC3339 moniker. The ABNF is absolutely clear on this point (as you suggested):

```
  time-numoffset  = ("+" / "-") time-hour ":" time-minute
   time-offset     = "Z" / time-numoffset
```
