### ISSUE TITLE
Are hexadecimal / octal / binary integers allowed in floats?

### ISSUE THREAD

**Issue by percontation** [toml-lang/toml#560]
From the doc:

> A float consists of an integer part (which follows the same rules as integer values) followed by a fractional part and/or an exponent part.

This seems to imply that something like `0x56.78` is a valid float, equal to `86.78`. This is unusual enough that it should be explicitly documented if this is intended (and if it isn't, then the documentation should be updated to not seem to say that).

(FWIW, in my opinion this should be explicitly disallowed, because inventing a new mixed-radix format that conflicts with the standard hex-float format seems bad.)

**Comment by lmna** [comment]
> Are hexadecimal / octal / binary integers allowed in floats? 

From toml.abnf:

    float = float-int-part ( exp / frac [ exp ] )
    float-int-part = dec-int
Thus only decimal integers are allowed in floats.
