### ISSUE TITLE
Error defining subkeys directly

### ISSUE THREAD

**Issue by token47** [toml-lang/toml#563]
The documentation says:

```
As long as a key hasn't been directly defined, you may still write to it and to names within it.

a.b.c = 1
a.d = 2

# THIS IS INVALID
a.b = 1
a.b.c = 2

```

But if I paste the first part on an empty file and try to parse it, I get an error. Am I doing anythin wrong or it really should be allowed?

I'm using python 3.6 and pytoml-0.1.18-1, and the script is as simple as this:

```
import pytoml as toml

with open('./variables.toml', 'rb') as f:
    variables = toml.load(f)

print(variables)

```

And this is the variables.tml file (same as the example in the doc):

```
a.b.c = 1
a.d = 2

```

This gives an error:

```
Traceback (most recent call last):
  File "./duetcfgen.py", line 10, in <module>
    variables = toml.load(f)
  File "/usr/lib/python3.6/site-packages/pytoml/parser.py", line 10, in load
    return loads(fin.read(), translate=translate, object_pairs_hook=object_pairs_hook, filename=getattr(fin, 'name', repr(fin)))
  File "/usr/lib/python3.6/site-packages/pytoml/parser.py", line 23, in loads
    ast = _p_toml(src, object_pairs_hook=object_pairs_hook)
  File "/usr/lib/python3.6/site-packages/pytoml/parser.py", line 352, in _p_toml
    s.expect_eof()
  File "/usr/lib/python3.6/site-packages/pytoml/parser.py", line 124, in expect_eof
    return self._expect(self.consume_eof())
  File "/usr/lib/python3.6/site-packages/pytoml/parser.py", line 164, in _expect
    raise TomlError('msg', self._pos[0], self._pos[1], self._filename)
pytoml.core.TomlError: ./variables.toml(5, 1): msg

```

If I don't try to set subkeys directly, all the keys are read fine.

Thank you!

**Comment by token47** [comment]
Yes. But I think (not sure) that "Dotted Keys" refer to another thing. It's the ability to have keys that are one single key but with a dot in the middle, and quoted, like:

"a.b" = 1

In this case, "a.b" is a single key, not the same as a.b without quotes. My problem is with the later.

That is not to say that this should be valid on this version, still inconclusive. What is the reference platform / lib on which the example in the doc work?

Thank you!

**Comment by Screwtapello** [comment]
No, quoting keys so that they can contain non-alphanumeric characters was added in 0.4.0 (determined by comparing the historical versions in the [/versions/en](https://github.com/toml-lang/toml/tree/master/versions/en)). "Dotted keys" means PR #505, merged on 2018-02-05, which introduced the idea of key-names with dots implicitly creating tables.

**Comment by token47** [comment]
Awesome!! Thank you very much. I will switch to a 0.5 version then.
