### ISSUE TITLE
Unclear how comments in strings are handled

### ISSUE THREAD

**Issue by jorisvr** [toml-lang/toml#566]
It is not clear from the specification how comments inside quoted strings are handled.
For example:

    a = """ # is this a comment ?
    # and this ? """

On the one hand, the **String** section states that "_Any unicode character may be used except ..._"
However, the **Comments** section states unconditionally that "_A hash symbol marks the rest of the line as a comment._"

It is clear from the ABNF definition that # inside a quoted string is just string content, but the ABNF is currently not authoritative.

**Comment by pradyunsg** [comment]
I think this can be considered a common knowledge thing that a # in quotes won't start a comment.

Will be happy to get a PR clarifying this if more people feel that it's somehow ambiguous.

**Comment by ChristianSi** [comment]
I'd say it's self-evident and no further clarification is needed. Otherwise we'd also have to explain that '[' does NOT open a table head if it happens to occur within a quoted string, that '=' within a quoted string does not separate a key from its value, and so on.

**Comment by pradyunsg** [comment]
I think it's clear what to do here.
