### ISSUE TITLE
Unclear whether multiple trailing commas are allowed in arrays

### ISSUE THREAD

**Issue by jorisvr** [toml-lang/toml#568]
It is not clear from the specification whether multiple trailing commas are allowed in array values.
For example:

    a = [ 1, 2, , , , ] # is this allowed ?
    b = [ , ] # or this ?

The ABNF definition forbids both cases, but the ABNF is currently not authoritative.

The section **Array** only states that "_Terminating commas (also called trailing commas) are ok after the last value of the array._". This suggests that any number of trailing commas is fine.

**Comment by pradyunsg** [comment]
> # is this allowed ?

No.

> # or this ?

No.

> This suggests that any number of trailing commas is fine.

I disagree but I wouldn't mind changing the language there to use the singular form instead of plural form:

> A terminating comma (also called trailing comma) is ok after the last value of the array.
