### ISSUE TITLE
Unclear whether trailing commas are allowed in inline tables

### ISSUE THREAD

**Issue by jorisvr** [toml-lang/toml#569]
It is unclear from the specification whether trailing commas are allowed inside inline tables.
For example:

    a = { b = 1, c = 2 , } # is this allowed ?

The section **Inline Table** says nothing about trailing commas, implying that they are not allowed.
However, a casual reader of the specification could reasonably assume that the same rules apply to trailing commas in arrays as in inline tables.

The ABNF definition forbids trailing commas in inline tables, but the ABNF is currently not authoritative.
I think the section **Inline Table** should explicitly forbid trailing commas to avoid possible confusion.

**Comment by pradyunsg** [comment]
> The section Inline Table says nothing about trailing commas, implying that they are not allowed.

Yep. Trailing commas are not allowed in Inline Tables.

> ABNF is currently not authoritative.

The ABNF is authoritative and serves to clarify these ambiguities in such cases.

> I think the section Inline Table should explicitly forbid trailing commas to avoid possible confusion.

I haven't taken a look at the section yet but I have a feeling that the more "details" we add to the specification about edge cases like this, the less approachable it becomes. I am ambivalent to this specific change, but minimizing the number of minor details that we put into TOML's human readable specification is definitely a good idea IMO.

**Comment by pradyunsg** [comment]
>  However the comment in the top of the ABNF file says explicitly that the ABNF is **not** authoritative.

Yeah; I see that now. That's mostly there because there might be nuanced issues with the ABNF that might exist that need to be "audited" - you've helpfully pointed out a few. :)

> If indeed the ABNF grammer is authoritative, I agree that is a great way to resolve these details. In that case it may be helpful to add a statement in the specification text, deferring to the ABNF grammer for precise definitions.

Yeah, I think @toml-lang/core will want to do that in the lead up to a v1.0.

**Comment by pradyunsg** [comment]
We'd want to clarify in the specification text that trailing commas in inline tables are not permitted.
