### ISSUE TITLE
Confusion around the term "float"

### ISSUE THREAD

**Issue by SirTates** [toml-lang/toml#572]
I currently get the idea the spec uses the word "float" where it should use "real".
I get this impression especially because of the lack of specifying the precision.
Floats by definition are binary formats, therefore can only have values with the power of 2, and a decimal input is therefore not ideal to parse, albeit far easier for humans to read.
example of this is:
0.1 is in floats stored as 0.100000001490116119384765625 comparable to the issue with 1/3=0.33333... in decimal.
(Hexadecimal Representation of 0.1f would be: 0x3dcccccd)
It is ideal for decimal values, which a select amount of languages support, but per the spec (as it specifies floats, not decimals or the more general term: reals) prohibits it being cast directly to a decimal from the file.
My proposition: leave it to the software implementation to define a real as a float or decimal and call the real numbers reals in the spec.

**Comment by TheElectronWill** [comment]
Leaving the float/decimal/whatever-format decision to the implementation allows the same file to be parsed to different data... which is problematic.

**Comment by nolange** [comment]
The spec should define a minimum to allow files adhering to those minimums to be read and rewritten without loss of information by a fully conforming implementation.
you can always support less (ie. fpu not supporting denormals, loss of precision in dec-to-bin conversion,..) or more for special cases.

The question is rather: should anyone interpret TOMLs floats as base10 (like financial software uses for its calculations) ?
I would argue that TOMLs floats should specifically be the IEEE754 binary variant. base10 would be another type or string.

**Comment by SirTates** [comment]
@TheElectronWill The implementation concerning the float precision already isn't specified, so the spec already allows the same file to be parsed to different data. A direct conversion from the text to a decimal is not officially allowed however.
You would either have to make it a high precision float and convert it to decimal, when you need it, with both conversion errors included, or you'd have to parse it to a string first and parse it inside the program to the decimal, which seems especially backwards to me.
If I were to want to parse it to a float without the possibility of an error I would need to use an integer with a hex input and trick the compiler into using a float pointer to the same data. I like the idea, but don't think many people would agree.
TOML's reals are stored as decimals, they're not actually floats. If you want to use IEEE754 in text, you need to use hex or some binary format, otherwise there will be rounding errors in most files using TOML, if they use the current float notation (which is decimal).

**Comment by TheElectronWill** [comment]
The readme mentions:
```
Floats should be implemented as IEEE 754 binary64 values.
```
Doesn't this sentence specifies how floats are handled?

From a user perspective, I agree that decimal floating-points would be better than binary floats.
On the other hand, most programming languages handle binary floats and not decimal floats (and BigDecimal and other non-primitive representations aren't as easy to use as ieee754 floats).

Now I can see the value of an option decimal/binary floats. I'd prefer this option to be included in the configuration file, in order to have a consistent behaviour between parsers. But perhaps is is not really important for floats🤔

**Comment by SirTates** [comment]
> The readme mentions:
>>Floats should be implemented as IEEE 754 binary64 values.
>
>Doesn't this sentence specifies how floats are handled?

Ah, you're right, I missed that because I only reread the middle part of the section. That still doesn't fix my other concerns of parsing decimal reals from text to floats rounding up or down depending on the language's parser in question and that actual decimals are not supported, which would prevent those rounding errors.

**Comment by pradyunsg** [comment]
TOML does specify floats to be IEEE754 binary64 values as noted.

That's the most common float type in most programming language and hardware. I think it's better to use what is familiar (albeit occasionally annoying) and commonly available on commodity hardware/most programming languages; than allowing parsers/implementations to use a differing implementations.

As for precision/rounding issues, I don't think most users would care much and when they do, converting to a Decimal representation from a string in the application, is probably the way to go tbh. If there are special needs, I suggest building behavior on top of TOML to satisfy them. [\[1\]][1]

[1]: I'm inclined to say it's likely better for TOML to avoid directly dealing with the 20% use cases that causes 80% of the problems; as per the 80/20 rule. ;)

**Comment by pradyunsg** [comment]
None the less, I'm open to any clarifications that might be helpful here, short of introducing/changing a data type in TOML. :)
