### ISSUE TITLE
Register the toml mimetype

### ISSUE THREAD

**Issue by patcon** [toml-lang/toml#574]
Reticketed from #465 (wanted to capture the intent, though won't have time atm)

Form for registering new mimetypes: https://www.iana.org/form/media-types

I'm not sure who (if anyone) in particular needs to submit, but I would think that the best approach would be for someone to fill out responses in an open etherpad or gdoc, and so it'll just be copy-paste when the time comes :)

Created a stub with all the fields:
~~https://public.etherpad-mozilla.org/p/toml-registration~~ (website gone; wasn't much there by copy-pasta though!)

**Comment by pradyunsg** [comment]
I'd suggest using something other than an etherpad for this \[[1]\]:

> While a formal shutdown date has not been announced, Etherpad is near the end of its expected lifecycle.

[1]: https://wiki.mozilla.org/Etherpad

**Comment by pradyunsg** [comment]
I don't think this is, in any way, a blocker for 1.0.

We should do this after 1.0 spends some time in the wild tho.

**Comment by JeppeKlitgaard** [comment]
@pradyunsg 

This seems to be solved already?

https://toml.io/en/v1.0.0#mime-type

The issue should probably be closed.

**Comment by patcon** [comment]
I don't have strong feelings on this, as the project doesn't technically need to register with IANA, but this was about doing it officially (not just informally claiming and documenting in the project docs 🙂 )

`application/toml` has not been submitted to IANA: https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by JeppeKlitgaard** [comment]
@patcon You're absolutely right. This should definitely remain open until the MIME type has been officially registered! My apologies

**Comment by pradyunsg** [comment]
Consolidating this into #870, which includes this.
