### ISSUE TITLE
suggest for new multi-line template string

### ISSUE THREAD

**Issue by LongTengDao** [toml-lang/toml#577]
```html

title = "issue"

article = <end-mark-not-in-string
    "\n\n" = "\u2029"
    "\n" = "\u2028"
    "\s" = "\u0020"
    "{{ name }}" = "Cman"
    "tab|" = "\t"
>

\s\sOne day, {{ name }} is coding, he found `TOML` is pretty good. But writing string in `TOML` is hard, {{ name }} think.

tab|--{{ name }}'s computer said
tab|2018.11.15

</end-mark-not-in-string>

```

Then we got:

```json
{
    "title": "issue",
    "article":
        "\u2028\u0020\u0020One day, Cman is coding, he found `TOML` is pretty good. But writing string in `TOML` is hard, Cman think.\u2029\t--Cman's computer said\u2028\t2018.11.15\u2028"
}
```

and:

1.  resolve the problem using `'''` with `'''` in it.
2.  variable uni-set value, without pre-define syntax mark ( it will cause further more problem -- we have more chars need to escape like in `"""` )

only adding the number of `'` like in markdown ``` `` ` `` ``` can never resolve the problem 1, because the `'` may at the start or the end of the string.
the block pre code syntax in markdown ( ````\n```js\n...\n```\n```` ) can resolve this, but keep use `'` will cause backwords confict, use new mark `` ` `` ( back quote ) is confusing, because there is already two type of string... big cost, and little earning.

**Comment by eksortso** [comment]
This seems too much like an attempt to make TOML into a templating engine.

Regarding quoting, you can use multi-line basic strings to do what you're asking for.

```toml
try-this = """
Use three double-quotes.
Three single quotes (''') can appear as is.
And any number of double quotes (\"\"\") can be escaped."""
```

When parsed, `try-this` will look like this:
```
Use three double-quotes.
Three single quotes (''') can appear as is.
And any number of double quotes (""") can be escaped.
```

**Comment by LongTengDao** [comment]
@eksortso ok, thx
