### ISSUE TITLE
Q: When will version 1.0 and RFC documentation come

### ISSUE THREAD

**Issue by universonic** [toml-lang/toml#578]
Hello, TOML is an awesome project, and we are using it as a configuration file format in some of our production applications. I have a few questions now:
- When will version 1.0 come? Do you have a plan?
- Will there be a lot of major changes when version 1.0 comes (compare to v0.5)?
- Is there a plan for the RFC documentation?

Thanks.

**Comment by pradyunsg** [comment]
> Will there be a lot of major changes when version 1.0 comes (compare to v0.5)?

No. This is documented in the README:

> The goal is for version 1.0.0 to be backwards compatible (as much as humanly possible) with version 0.5.0. All implementations are strongly encouraged to become 0.5.0 compatible so that the transition to 1.0.0 will be simple when that happens.

**Comment by pradyunsg** [comment]
> Is there a plan for the RFC documentation?

Not yet, other than that @mojombo wanted to do it.

> When will version 1.0 come? Do you have a plan?

See #617.
