### ISSUE TITLE
What does the word "Minimal" in TOML's name refer to concretely?

### ISSUE THREAD

**Issue by LongTengDao** [toml-lang/toml#580]

**Comment by Hrxn** [comment]
That TOML is only supposed to be one thing (a configuration file format), and nothing else, but it's good at being that one thing?

**Comment by ChristianSi** [comment]
My two cents: it means that the TOML spec is (and will always be) shorter than the YAML spec.

**Comment by pradyunsg** [comment]
@LongTengDao opened this issue in the context of https://github.com/toml-lang/toml/pull/579#discussion_r236772096 IIUC.

I'll go ahead and close this issue. @LongTengDao let me know if there was some other reason that this issue was filed.

Thanks for pitching in @ChristianSi @Hrxn! :)

**Comment by LongTengDao** [comment]
@pradyunsg Thanks! I think the author of this language maybe the best one to define it, but I worry that it will disturb him. Can I at Tom?

**Comment by pradyunsg** [comment]
Sure! Reopened.

**Comment by LongTengDao** [comment]
@mojombo Thank you! 🛩 Can you help me? I really want to know
