### ISSUE TITLE
Artihmetic expression as values

### ISSUE THREAD

**Issue by nifker** [toml-lang/toml#582]
What about having arithmetic expression as a value, e.g.: 
> size = 1024 * 1024 * 8
  
which would simplify setting values which even derive from arithmetic expressions and as you just need to edit one multiplicand to change the wished result.

**Comment by pradyunsg** [comment]
Is the underlying motivation the same as #427?

**Comment by nifker** [comment]
@pradyunsg no as it could also be used for time e.g.
> time = 60 * 60 * 12

**Comment by eksortso** [comment]
A time duration/timedelta type is proposed in #514.

Unit conversion suffixes and timedelta types would be pretty good additions to the standard, I think. Arbitrary arithmetic expressions, not so much.

**Comment by quadrupleslap** [comment]
Why is that better than a comment?

```toml
time = 43200 # 12 hours
```

**Comment by setop** [comment]
> Why is that better than a comment?
> 
> ```toml
> time = 42300 # 12 hours
> ```

Because a comment can become inconsistent...

**Comment by nifker** [comment]
> Why is that better than a comment?
> 
> ```toml
> time = 43200 # 12 hours
> ```

because you need to recalculate the whole instead of just changing one term

**Comment by pradyunsg** [comment]
While I can see the value that this _could_ have in certain situations, I don't think this is a super valuable addition. Broadly, I don't think a configuration file format should have operator logic happening within it. I think this is further demonstated by the lack of activity on this issue, compared to the rest of the issue tracker. :)

None the less, thanks for proposal and your patience on this!
