### ISSUE TITLE
Parsing enum keys from toml file

### ISSUE THREAD

**Issue by chinedufn** [toml-lang/toml#588]
I'm trying to parse a TOML file into a HashMap.

When I try to do this with serde-json it works just fine, so I'm thinking that I'm misusing or misunderstanding serde-toml.

My TOML file and Rust types (simplified):

```toml
[[Rocks]]
    [Rocks.EQUAL.Quest]
      quest_id = 1
      step = 3

```

Which I'd like to parse into `HashMap<Model, MyType>`

```rust
enum Model {
  Rocks
}

enum MyType {
  EQUAL(Criterion)
}

enum Criterion {
  Quest {quest_id = 1, step = 3}
}
```

Error:

```
Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "invalid type: string \"Rocks\", expected enum Model", key: [] } }',
```

So it looks like it's recognizing `Rocks` as a String instead of a `Model`. Is there any way around this?

Cheers!

**Comment by eksortso** [comment]
I think you're asking the wrong folks. This project, toml-lang/toml, is the TOML standard. You'll want to ask people familiar with [Serde](https://serde.rs/) about how to work with TOML. The Serde page links directly to the Serde project.

**Comment by chinedufn** [comment]
Wooooooooow totally thought I was commenting on [toml-rs](https://github.com/alexcrichton/toml-rs)

So sorry, but also can't help but laugh here.

Apologies!
