### ISSUE TITLE
ABNF grammar does not allow new lines on the first line

### ISSUE THREAD

**Issue by SgtWiggles** [toml-lang/toml#591]
Currently expansion of expression does not allow for newlines at the beginning of the document. The lack of newlines on the first line of the document isn't mentioned anywhere. This could be fixed using:
```
toml = *newline expression *( newline expression )
```
instead of
```
toml = expression *( newline expression )
```

**Comment by eksortso** [comment]
An `expression` can be a zero-length `ws`. So the existing rule for `toml` in the ABNF does in fact allow for newlines at the beginning of the document.
