### ISSUE TITLE
Disallow integers in keys

### ISSUE THREAD

**Issue by xoofx** [toml-lang/toml#592]
Hey,

While implementing the lexer for TOML, I have found that allowing integers in a key makes the lexer parser state dependent. It is pretty uncommon to have this in simple languages as it happens usually in languages that have complicated context dependent parsing (e.g preprocessor macros in a C like language). Imo, it's an unfortunate choice for a simple language like TOML to incur contextual lexers.
 
Another weird side effect of this is that you can have in a key something that looks like a float, or an integer hexa

```toml
[table]
1.0 = 2.0
0x155 = 0x155
```

I don't know if this is something that could be revisited before 1.0 and change a key to `[a-zA-Z\-_][a-zA-Z\-_0-9]*`?

**Comment by pradyunsg** [comment]
> ASCII letters, ASCII digits, underscores, and dashes (A-Za-z0-9_-)

Base keys can not contain `.`. The first key is thus not valid TOML.

As for the alternative notations, I don't think it's really that big an issue.

**Comment by xoofx** [comment]
> Base keys can not contain .. The first key is thus not valid TOML.

Sorry, I used the term key as a bag for base key and dot key. So `1.0` is a valid dot key right?

> As for the alternative notations, I don't think it's really that big an issue.

hm, I don't understand which alternatives you are referring to? 😅 

I'm just pointing a double issue:

- the base key/dot key allow to parse things that look like integers, floating points while of course the specs says that it would be converted to a string, but imo this is confusing
- it makes the lexer state dependent, which is not a great choice for a language that is supposed to be simple

**Comment by bd82** [comment]
Interesting.

I have recently implemented a Toml lexer & parser but did not notice this edge case.

Perhaps it can be resolved by ***lexer states that are independent of the parser state***?
Example:
- Start in KEY mode.
- Once an "=" token is encountered we are in VALUE mode and floating points are allowed.
- Finding a newline in VALUE mode would move us back to KEY mode.

This obviously is naive and simplified (no handling of inline-tables) but it is only meant to demonstrate the concept.

btw if we can differentiate between TOP Level context (key) and value mode
that will also resolve the "[[" vs "[" ambiguity (table vs table of tables vs array of arrays)

**Comment by xoofx** [comment]
> Perhaps it can be resolved by lexer states that are independent of the parser state?

That's a bit playing with the concepts! 😅 As it basically bringing parser knowledge into the lexer... and also as you said, inline tables are typically going to require more knowledge to correctly do it.

In my case, my lexer has something like this:
```c#
if (State == LexerSate.Key)
{
    NextTokenForKey();
}
else
{
    NextTokenForValue();
}
```

and the parser is feeding the lexer with the correct state, and I'm "fine" with this solution.  But this is annoying, because typically, I cannot test my lexer separately on a full TOML document and it is even barely unit testable on slices, as it would require my unit tests to have this parser knowledge...

But I'm worried that my original issue dragged the discussion to some "implementation details" while I should have put an emphasis on the user experience ambiguity first (e.g `1.0 = 2.0`), implying the side effect of an annoying parser/lexer state coupling

**Comment by bd82** [comment]
## Back to the high level concepts.

I agree that from a simplicity perspective that it would be best to decouple the lexing and parsing state completely.

If only due to the fact some language tools have **completely separate** lexing and parsing
phases so more tools could be used to build (correct) parsers for Toml without "advanced mitigation logic"

Some References to a similar (but more complex) scenario:
- ECMAScript is difficult to lex without parser knowledge.
  - https://stackoverflow.com/questions/5519596/when-parsing-javascript-what-determines-the-meaning-of-a-slash
  - https://github.com/sweet-js/sweet-core/wiki/design
  - https://github.com/acornjs/acorn/issues/589 

There is another concern that when creating a ***fault tolerant parser***,
for example to be used in an IDE.
It is much easier to naively recover from lexing errors by simply ignoring unidentified
character sequences when the lexer has only a **single** mode.

**Comment by xoofx** [comment]
> It is much easier to naively recover from lexing errors by simply ignoring unidentified
character sequences when the lexer has only a single mode.

Yes, and specially, in the case of TOML, we are lucky that the grammar doesn't require token previews

**Comment by Jezza** [comment]
So, I just thought I'd add my two cents, having already taken a stab at implementing a toml 0.5 parser.

https://github.com/Jezza/toml/blob/master/src/main/java/com/github/jezza/lang/TomlParser.java#L114

Basically, if it's lexed as number, it needs to be a base 10 integer, otherwise it'll reject it.

I've actually just taken a glance at the spec, and I realise I've actually done some things incorrectly.
First of all, I should definitely accept `0x2` as a valid key.
It's not a number, but still a valid key.

However, floats an issue does come up.
JFlex does nom as much input as it can, and so it'll take `1.0` as a float, over `1` `.` `0`.
I can perform a work around in code, and honestly, it's quite easy, but yeah, just thought
I'd chime in and say maybe the spec should inform us a bit about the precedence.

Reading the actual spec, I would 100% convert `1.0` into a dotted key with `1` and `0`.
I think I'll go change my parser to do that.

**Comment by xoofx** [comment]
> JFlex does nom as much input as it can, and so it'll take 1.0 as a float, over 1 . 0.
> I can perform a work around in code, and honestly, it's quite easy, but yeah, just thought
> I'd chime in and say maybe the spec should inform us a bit about the precedence.

And that's another case to remove this integers in keys in TOML, as I'm pretty sure that many implementations got actually that wrong. 

That's why you can't use a bare lexer, you need to maintain a state, otherwise going through "oh I just parser a float but it is actually not " is pretty fragile/clunky to recover from (specially with the dot, as the parser is usually in a very different state when it handles a dotted key)

**Comment by pradyunsg** [comment]
> So `1.0` is a valid dot key right?

Yes.

This is not going to change in TOML 1.0. We could revisit this post TOML 1.0, if someone's motivated enough to bring this up then. :)

---

Closing since there's nothing actionable here.

**Comment by Jezza** [comment]
Personally, I think that integer keys are a bit weird anyway, but I might just not have the use-case for it.

The best action might be to clarify that `1.0 =` should be parsed as a dotted key `1` `0`.

It's implicit in the spec, but as this issue is showing, a couple of people already missed it, and it's not even version 1.0.

**Comment by pradyunsg** [comment]
> The best action might be to clarify that `1.0 =` should be parsed as a dotted key `1` `0`.

Happy to accept a PR for this. :)

**Comment by xoofx** [comment]
> This is not going to change in TOML 1.0. We could revisit this post TOML 1.0, if someone's motivated enough to bring this up then. :)

Is this because you don't want to break compatibility (while I thought that 0.x could allow this) or you think that the cost of the ambiguity is worth the price that allowing integers in keys is bringing? I could run some stats on all TOML documents on github to find out how many are using integers in their keys if that's something that could balance a decision....
Otherwise, I don't think TOML should revisit later, it is either today or never. 

> It's implicit in the spec, but as this issue is showing, a couple of people already missed it, and it's not even version 1.0.

Yes, and I'm going to send a PR to https://github.com/BurntSushi/toml-test to add these edge cases... pretty sure that it is going to break a few libraries that were assuming full 0.5 compatibility.

**Comment by pradyunsg** [comment]
> Is this because you don't want to break compatibility (while I thought that 0.x could allow this)

This -- the README has a note about 0.5.0 being "very stable".

**Comment by xoofx** [comment]
> @xoofx I'm not sure what you mean by finicky here. I assume you meant it in good faith. :)

I was just teasing a bit, as I found the responses a bit terse regarding the problem I'm bringing here  :blush:

**Comment by philippgl** [comment]
Reading the spec, if would think, that integers (!= string with digits) are not allowed as keys and
```toml
[table]
1.0 = 2.0
0x155 = 0x155
```
is parsed as
```toml
[table]
"1"."0" = 2.0
"0x155" = 0x155
```
and 
```toml
1.0 = 2.0
"1"."0" = "whatever"
```
is forbidden due to the duplicate key.

**Comment by xoofx** [comment]
> Reading the spec, if would think, that integers (!= string with digits) are not allowed as keys and
> ... is forbidden due to the duplicate key. (github output looks strange)

Indeed. The point of the discussion here was just to highlight that "integers like" keys can be actually confusing and it makes the lexer dependent on the state of the parser, which is quite annoying.

**Comment by LongTengDao** [comment]
> (github output looks strange)

maybe github only support toml earlier version which not support dotted keys...

**Comment by pradyunsg** [comment]
(slight OT) @xoofx I usually try not to be terse or come across as dismissive but apologies if it came across as such. Sarcasm isn't something that gets communicated well unless folks share the same context which I didn't in this case.

---

I think the ship has sailed for this. For now, I think it's better to not break compatibility with TOML 0.5 -> 1.0.

In terms of actionable items here, I am splitting this ticket into 2.

- Add a small note to the dotted keys section that `1.0 = true` gets parsed into `{"1": {"0": true"}}`.
- Have a post-1.0 discussion for actually disallowing this in the next major version bump.

**Comment by sevmeyer** [comment]
Please excuse my ignorance, but doesn't this also affect keywords? Even with the proposed rule `[a-zA-Z\-_][a-zA-Z\-_0-9]*`, bare keys remain context-sensitive:

    true = false
    nan  = inf
    -42  = +42

I don't think there is a simple way to avoid this ambiguity.

**Comment by eksortso** [comment]
Devil's advocate says: It's not hard to tell what's on the left side of the equals sign and what's on the right side. Yes you can confuse yourself by naming your keys the same as Boolean values. But there's no good reason to do that.

**Comment by pradyunsg** [comment]
I was open to ideas/reasons to change the behavior. @ChristianSi's comment from the future (see end of post) has convinced me that it's not worth changing this behavior. There are valid use cases for this and we explicitly call this behavior allowed in the current specification. 

We won't be disallowing integers in keys in TOML. A clarification will be added to explain the dotted keys edge case (this is being tracked #616).

Thanks for filing this issue @xoofx and to everyone who's contributed to this discussion! :)

---

<img width="300" alt="Screenshot 2019-05-08 at 10 23 42 AM" src="https://user-images.githubusercontent.com/3275593/57382742-7b983700-717b-11e9-9842-8ddb92b6ceba.png">

Hi @ChristianSi from the future! :P

**Comment by ChristianSi** [comment]
Well, post-1.0 is still a long way of, so the future seemed the right place to make that comment ;)
