### ISSUE TITLE
Repeated keys in tables

### ISSUE THREAD

**Issue by za3k** [toml-lang/toml#599]
It looks like the standard doesn't explicitly say that tables can't contain repeated keys. I assume this is the intent, want to make it explicit? I wouldn't normally push for it except that the JSON standard very notably doesn't mention what to do with repeated keys, and different implementations doing different things has led to issues.

**Comment by LongTengDao** [comment]
> Defining a key multiple times is invalid.
> 
> ```
> # DO NOT DO THIS
> name = "Tom"
> name = "Pradyun"
> ```

[versions/en/toml-v0.5.0.md#L189](https://github.com/toml-lang/toml/blame/master/versions/en/toml-v0.5.0.md#L189)

**Comment by pradyunsg** [comment]
I'm going to go ahead and close this, since as @LongTengDao helpfully pointed out, repeated keys are explicitly disallowed.

**Comment by za3k** [comment]
On 2019-03-06 04:37, 龙腾道 wrote:
>> Defining a key multiple times is invalid.
>> 
>> # DO NOT DO THIS
>> name = "Tom"
>> name = "Pradyun"
> 
> versions/en/toml-v0.5.0.md#L189 [1]


Bare keys, unamiguously yes. Repeated tables, unambiguously yes. I'm 
just suggesting making it explicit for tables within keys, too.

**Comment by LongTengDao** [comment]
> On 2019-03-06 04:37, 龙腾道 wrote: > Defining a key multiple times is invalid. > > # DO NOT DO THIS > name = "Tom" > name = "Pradyun" versions/en/toml-v0.5.0.md#L189 [1]
> Bare keys, unamiguously yes. Repeated tables, unambiguously yes. I'm just suggesting making it explicit for tables within keys, too.

Do you mean repeated keys in inline tables, like this?

```
inline-table = { name = "Tom", name = "Pradyun" }
```
