### ISSUE TITLE
[edge cases discuss] tab in (single) literal string / two ending single quotes in multi line literal string / ctrl chars in file / table array with space / comma in newline

### ISSUE THREAD

**Issue by LongTengDao** [toml-lang/toml#601]
Ask some edge case:

```toml
<BOM> # [ ] Is this ok?
# <CR> # [ ] Is this ok? CR isn't "newline", so it's ctrl char. But spec only said ctrl chars can't in strings

single_literal_string_with_tab = '<Tab>' # [ ] Is this ok?

multi-line_literal_string_with_two_ending_single_quotes = '''

    <Tab> # [v] This is ok, as spec said.

    '' # [v] This is ok, as spec said.
    ''''' # [ ] Is this ok?

[ [array-of-tables-with-whitespace] ] # [ ] Is this ok?

comma-in-newline = [
    'item'
    , # [ ] Is this ok?
]

```

\* `<...>` means control character which I can't directly write in example.

**Comment by LongTengDao** [comment]
In my parser, I currently implement these as:

- __tab in single literal string__: `yes`, as spec said roughly, but I think maybe that's not good practice?

- __two ending single quotes in multi-line literal string__: `yes`, but if more, it's `no`, because multi-line literal string is ends with three, so it could include two serial quote marks at anywhere; spec didn't say it clear, so I think implementation should be tolerant. But I doubt this item.

- __control chars in file__: `no`, except `BOM` at the start of the file. Because file can only contain valid expression, which not include any character spec didn't say. But `BOM` is allowed by Unicode in whole file encoding level, so I think that's valid.

**Comment by pradyunsg** [comment]
> two ending single quotes in multi-line literal string

Once you have a `'''`, the multiline string ends. `''` does not end it.

```
multi-line_literal_string_with_two_ending_single_quotes = '''

    <Tab> # OK

    '' # OK
    ''''' # NOT OK, the string ended at the 3rd '
```

**Comment by pradyunsg** [comment]
The rest are okay and I'll be happy to see any PRs you might want to file for clarifications.
