### ISSUE TITLE
array item is Multi-line basic strings?

### ISSUE THREAD

**Issue by epheien** [toml-lang/toml#605]
such as
```
list = [
'''
hello
world
'''
]
str = '''
hello
world
'''
```

```
>>> s = """
... list = [
... '''
... hello
... world
... '''
... ]
... str = '''
... hello
... world
... '''"""
>>> s
"\nlist = [\n'''\nhello\nworld\n'''\n]\nstr = '''\nhello\nworld\n'''"
>>> import toml
>>> d = toml.loads(s)
>>> d
{'list': ['h'], 'str': 'hello\nworld\n'}
```

**Comment by eksortso** [comment]
This project is for the TOML standard. You want to file a bug with the project for the particular parser that is giving you this erroneous behavior.

**Comment by epheien** [comment]
> This project is for the TOML standard. You want to file a bug with the project for the particular parser that is giving you this erroneous behavior.

because https://pypi.org/project/toml/ say it pass the TOML test suite.

> A Python library for parsing and creating TOML.
The module passes the TOML test suite.

so I think is a standard issue?
I will test other toml implement. and report it to python toml module.

**Comment by TheElectronWill** [comment]
The test suite doesn't seem to test this case, but it's still a valid use of multiline strings.
