### ISSUE TITLE
Is it possible to use a variable in a value of a key-value declaration?

### ISSUE THREAD

**Issue by nlisker** [toml-lang/toml#606]
This is part of the config file:

```
[params]

  # Hero section
  [params.hero]
   title = 'Version 11'

  # Documentation section
  [params.documentation]
    enable = true
    title = "Documentation"
    description = ""

    [[params.documentation.item]]
      title = "Release Notes"
      description = "Read about Version 11"

    [[params.documentation.item]]
      title = "Getting Started"
      description = "Get started with Version 11"

    [[params.documentation.item]]
      title = "Doc"
      description = "Documentation for Version 11"
```

If I change the version to 12, I don't want to go over each value and change it. What I want is to defined `version = "12"` (I guess under `[params]`) and then use this variable in all the values, like:

    description = "Read about Version " + version

or something to this effect. Is something like this possible?

**Comment by TheElectronWill** [comment]
this is not possible in TOML

**Comment by nlisker** [comment]
Thanks, what do you mean by "add `+version` in your application's code"?

**Comment by TheElectronWill** [comment]
instead of writing "read about version 11" in the config you write "read about version" and you add the version number after reading the config

**Comment by drunkwcodes** [comment]
It can be achieved by adopting modern template engines.
There are lots of implementations and different syntax.

It should be agnostic to TOML IMHO.

**Comment by nlisker** [comment]
Got it, thanks.

**Comment by SubhramRanaRZP** [comment]
@drunkwcodes How can I do [this](https://github.com/toml-lang/toml/issues/606#issuecomment-481614770). I have no knowledge on template engines.

**Comment by drunkwcodes** [comment]
@SubhramRanaRZP [jinja](https://jinja.palletsprojects.com/en/3.1.x/templates/#variables), mako, etc.
