### ISSUE TITLE
License command (or text) 

### ISSUE THREAD

**Issue by TomasRoj** [toml-lang/toml#610]
Can I make some command /text which will tel what license of document is it? I think this can be goog and useful.

-tr

**Comment by TheElectronWill** [comment]
Once again there are no commands in toml (#609)
Do it yourself, in your program.

**Comment by TomasRoj** [comment]
And is there some license  text I say text because I don't know how to say it in another way

**Comment by TomasRoj** [comment]
I litlle bit don't understand the blueprint of this project

**Comment by TheElectronWill** [comment]
Like almost all github projects, the license is in the `LICENSE` text file.

What don't you understand about the project? It contains the specification of the TOML configuration language.

**Comment by TomasRoj** [comment]
no I dont mean license of project. I mean like a "title = "TOML Example" . In front of title a license

**Comment by TheElectronWill** [comment]
> In front of title a license

??

If you want a TOML example, look at the README.md

**Comment by TheElectronWill** [comment]
And if you want to include a license header in your toml file, just use comments.

**Comment by TomasRoj** [comment]
Yes, thats what I mean thanks.

**Comment by pradyunsg** [comment]
Thanks @TheElectronWill for answering the question here. :)
