### ISSUE TITLE
Lists in the style of TOML

### ISSUE THREAD

**Issue by Lepzulnag** [toml-lang/toml#613]
For now, TOML lists are JSON-like :
``` 
myVegetables = [
  'potato',
  'onion',
  'tomato',
]
```

Wouldn't it be more TOML-ish to allow to define lists this way :
``` 
[myVegetables]
'potato'
'onion'
'tomato'
```
With this simple rule : if an element has no key, just a value (or just a key and no value, depending on the point of view), it's a list element and its parent is a list.

I'm actually the author of a TOML's Javascript parser, with which I allowed this syntax because it felt so comfortable (I had many URL lists in my configuration file).

**Comment by drunkwcodes** [comment]
Wat?

**Comment by ChristianSi** [comment]
Lists shouldn't use table syntax, that would be too confusing. I think a case could be made for making the comma between list items optional if they were separated by a newline instead. This would allow writing:

````
myVegetables = [
  'potato'
  'onion'
  'tomato'
]
````

**Comment by Lepzulnag** [comment]
Yes, I also think commas are unnecessary.

**Comment by drunkwcodes** [comment]
The comma things are trivial comparing to the table unpacking, keyvar reuse, and the relationship between toml files (or other file formats).

**Comment by eksortso** [comment]
@drunkwcodes None of the things that you mentioned are relevant to this particular issue.

**Comment by drunkwcodes** [comment]
I was amazed by those json-schema features, which do not recommend list as top-level struct.

**Comment by eksortso** [comment]
Ah, good point. Each of the list proposals mentioned here still take the
shape of key=array, which means that the table is still considered the
top-level construct.

**Comment by drunkwcodes** [comment]
This issue leveraged the use of list inappropriately.
While viewing the TOML paging issue, I was thinking about slicing TOML files by tables.

**With the integrity checksum along with data arrays.**

One-dimension data is rare and should only exists in `txt` or `csv` formats IMO.
This is a important place to determine how ALODB will be introduced in implementations.

**Comment by ChristianSi** [comment]
@drunkwcodes Drunk when commenting?

**Comment by drunkwcodes** [comment]
@ChristianSi Also drunk when replying.

**Comment by TheElectronWill** [comment]
Please stop commenting off-topic. This issue is about making the list syntax more lenient, not discussing other features that you found nice.

**Comment by drunkwcodes** [comment]
@pradyunsg  Please mark the second reply as off-topic too. (https://github.com/toml-lang/toml/issues/613#issuecomment-486119260)

And commas in the list are necessary IMHO.

**Comment by pradyunsg** [comment]
Nice catch @drunkwcodes!

I don't think the syntax proposed by OP is good since it's easy to confuse it with tables. The newlines as delimiters discussion is an interesting one but it's a post 1.0 discussion, since it's scope can be bigger than just lists (see #551). 

I'm going to go ahead and close this issue.
