### ISSUE TITLE
Shouldn't these revisit cases be invalid?

### ISSUE THREAD

**Issue by LongTengDao** [toml-lang/toml#615]
```toml
[[a]]
[b]
[[a]]
```

```toml
[a.b]
[b]
[a.c]
```

```toml
[a.b]
[a]
```

They all make same branches not be written together, should they be allowed?

**Comment by eksortso** [comment]
My immediate take is: They look ugly, but they're not violating any rules.
Tables may be defined in any order, whether or not they look right that way.

Are there any TOML files out in the wild that match one if these patterns,
but do so for arguably good reasons?

>

**Comment by drunkwcodes** [comment]
This is a kind of a malformed state. But it allows `echo "\n[new settings]" >> file.toml` to have beautiful diff and test before formatting.

**Comment by LongTengDao** [comment]
> They look ugly, but they're not violating any rules.

The rules is made by human for reasons, so the reason is what we talk.

The spec made appending key/value pair to a static table invalid, because it makes same level things far away from each other:

```toml
a = { x = 1 }
a.y = 2
```

The spec also made re-open a table invalid, because it makes same level things far away from each other:

```toml
[a]
x = 1
[b]
[a]
y = 1
```

So shouldn't it be same to revisit cases?

**Comment by eksortso** [comment]
Let me point out that inline tables, as interpreted here, are static, self-contained, and do not permit subtables to be defined outside their own scope. Tables defined by standard headers are not as strictly controlled, and so the real question is whether we adopt rules limiting how standard tables are defined that are roughly parallel to how inline tables and dotted keys are limited.

So, let's talk aesthetics. I agree with your complaints for the most part. I would personally want to keep related tables, keys, and values close to one another. But I would not want to prevent someone else from using table headers in a flexible manner if it aided their configuration efforts. But I haven't seen any real-life TOML which splits up a table array or splits apart subtables of a common parent.

I know that issues have been raised and sunk in the past calling for strict ordering of tables. I have yet to be convinced that outright banning awkward arrangements of tables in TOML is worthwhile. But at the same time, I've not seen real-life TOML documents veering from an implicit strict table-ordering rule.

At this point, I don't think anything short of the Word Of @mojombo will close this topic. I'd like to see him return and deliver some long-needed attention to this project, and decide some of these issues authoritatively. TOML's use is strong, but without even delegated authority, it's fraying a bit.

**Comment by LongTengDao** [comment]
Okay, maybe this makes sense:

```toml
a.x = 1
b.x = 1

a.y = 2
b.y = 2

c.x = 3
c.y = 3
```

It's still sorted, just not first level order, but still in order. So leave this free.

**Comment by LongTengDao** [comment]
Related issue: #446
