### ISSUE TITLE
TOML 1.0: What all do we want to do?

### ISSUE THREAD

**Issue by pradyunsg** [toml-lang/toml#617]
Hello everyone!

TOML has been fairly stable for a while now and has been adopted by [quite a few projects][1]. This means that it's about time that TOML "grows up" to 1.0. I've just gone ahead and created a [project board] for tracking our 1.0 release.

I do not want to time box our release plans just yet but I do hope to get this done this year. We won't be making backward incompatible changes or adding new syntax, between TOML 0.5 and TOML 1.0. I'm hoping that our 0.5 parser implementations will be able to bump up to 1.0 easily.

---

Consider this issue a meta issue for the discussion of what is needed for TOML's major version bump. I welcome everyone to post ideas for things 'we must address' + 'we'd like to address' prior to 1.0. 

To make it feasible and easier to keep track of things, I request you to post one suggestion per post, state "critical path" or "nice to have", link to an existing issue and provide some summary/rationale. If a suggestion does not have an existing issue filed for it, please file a new issue before posting your suggestion here. We can discuss additional details and the merits of the suggestion on the linked issues. I hope this process is not too much of an overhead. :)

I want to hear from others what they think should be done as a part of TOML 1.0 release process. I'll populate the board as we figure out our plans.

[1]: https://github.com/toml-lang/toml/wiki#projects-using-toml
[project board]: https://github.com/toml-lang/toml/projects/1

**Comment by ehuss** [comment]
I think it would be good to have a decision on how #499 should behave.  Different parsers are treating restrictions on dotted keys differently, in a variety of ways.  This is related to the open/closed discussion at https://github.com/toml-lang/toml/issues/446#issuecomment-388243460.  I think it would be undesirable to have this ambiguity in the final spec.  I'm not sure how to make progress on that issue, though, since it involves both subjective aesthetics and implementation complications.

**Comment by drunkwcodes** [comment]
Transpilers and code generators!

**Comment by lmna** [comment]
An official/blessed test suite. https://github.com/toml-lang/toml/issues/585
Make sure that abnf passes tests.

**Comment by graza** [comment]
I discovered TOML recently and wrote a blog post for myself to help me understand/remember it.  As part of that I created a syntax diagram and wondered if it would be a useful to use this form as part of any official documentation on a github-pages site (on toml.org?).

The blog post is [here](https://gra-ontech.blogspot.com/2019/05/toml-syntax-diagrams.html).

**Comment by nolange** [comment]
I consider #562 for the `critical path`.
Reason being that without you are not able to convert float -> string -> float losslessly, particularly in an efficient manner without even using floating point hardware or ridiculously large integers.

Further, this would make `toml`'s float representation identical to C99/C++11 and directly compatible with the C string functions like [strtod](http://www.cplusplus.com/reference/cstdlib/strtod). So it actually could simplify implementations.

**Comment by eksortso** [comment]
@nolange I'm keen on introducing a decimal literal type. But since I didn't make a strong case for it,, or even insist upon it forcefully, such a proposal will likely have to wait until after v1.0 is released, particularly if the future of TOML involves more general data description.

**Comment by nolange** [comment]
> @nolange I'm keen on introducing a decimal literal type.

I don't understand what you are saying, I am asking for allowing of defining float literals (which already exist in the spec) in another textual format. The problem is that converting values like `3.14-e50` to an internal float value will need multiple integers of magnitude `10 ^ 50` if you care for best-possible representation.
the decimal vs binary exponent (text vs internal) is the culprit here.

using base2 exponents eliminates this issue.

> But since I didn't make a strong case for it,, or even insist upon it forcefully, such a proposal will likely have to wait until after v1.0 is released, particularly if the future of TOML involves more general data description.

There are already 2 points in the project board denoting `new syntax`. I dont know where our misunderstanding lies, but request is not a fundamental change.
The [section float](https://github.com/toml-lang/toml/blob/master/README.md#user-content-float) would get a couple paragraphs adding a syntax like  **0x**1.2**p**3.

Aslong this doesn't collide with the existing syntax it wont have sideeffects, and be 100% backwards compatible with files written for the 0.50 spec.

**Comment by graza** [comment]
@nolange @eksortso Why not use decimal floating-point?  It's kinder to humans (and isn't that the point of TOML?).

Modern processors are now starting to support the [decimal floating-point](https://en.wikipedia.org/wiki/Decimal_floating_point) standard defined in IEEE 754-2008. For example the Intel C compiler [now has support](https://software.intel.com/en-us/cpp-compiler-developer-guide-and-reference-floating-point-formats) for the data types and functions to check the support status.

The C data types in the standard are _Decimal32, _Decimal64. and Decimal128.  Constants/literals in C use a suffix to denote which data type the value is to be represented in.  I believe the suffixes are as per [this proposal in 2008](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1312.pdf): 

- f d l F D L 
- df dd dl DF DD DL

These denote 32/64/128 bit floating-point values, and with the 'd' or 'D', represent a decimal floating-point value.

For TOML, I think this could go one of two ways.  Either:

1. When parsing a TOML document, the parser is instructed to return decimal floating-point when a floating-point number is parsed in the document, or
2. TOML format is updated to support the suffixes.

The first is backward compatible.  The second is new-syntax.

**Comment by pradyunsg** [comment]
Please move the conversation on decimal literals to a new issue.

**Comment by pradyunsg** [comment]
> We can discuss additional details and the merits of the suggestion on the linked issues.

Please move the conversation on decimal literals to the relevant issue or create a new one.

**Comment by pradyunsg** [comment]
Thanks for the suggestions! Keep them coming if there are any more.

I've taken the liberty to change the first line of each comment to be of a consistent style, and marked all non-suggestion/unclear comments as off-topic.

**Comment by eksortso** [comment]
@pradyunsg My apologies for raising the subject. My intent was to highlight that any features that have not been discussed at any length are off the table until after v1.0 is released.

**Comment by pradyunsg** [comment]
@eksortso Please, don't apologize. 🙈

What you (and others) did is perfectly fine; it's just that I want to keep this issue easier to look at for summaries.

**Comment by eksortso** [comment]
Let's add PR #619 to the Critical Path. This is critical because code points U+D800 to U+DFFF, which are explicitly restricted to UTF-16, are forbidden in UTF-8.

**Comment by pradyunsg** [comment]
Things have settled down here. Taking that as a cue that everyone who wanted to say something has said it, I've updated the project board as needed.

Thanks everyone who contributed to the discussion here! :D

**Comment by waldyrious** [comment]
For future reference, after [three](https://github.com/toml-lang/toml/releases/tag/v1.0.0-rc.1) [release](https://github.com/toml-lang/toml/releases/tag/1.0.0-rc.2) [candidates](https://github.com/toml-lang/toml/releases/tag/1.0.0-rc.3), TOML 1.0 was [released](https://github.com/toml-lang/toml/releases/tag/1.0.0) on 12 January 2021! 🎉
