### ISSUE TITLE
Railroad diagrams

### ISSUE THREAD

**Issue by pradyunsg** [toml-lang/toml#620]
I discovered TOML recently and wrote a blog post for myself to help me understand/remember it.  As part of that I created a syntax diagram and wondered if it would be a useful to use this form as part of any official documentation on a github-pages site (on toml.org?).

The blog post is [here](https://gra-ontech.blogspot.com/2019/05/toml-syntax-diagrams.html).

_Originally posted by @graza in https://github.com/toml-lang/toml/issues/617#issuecomment-490152910_

**Comment by LongTengDao** [comment]
About website. I'm a front-end engineer, glad to help if need.

**Comment by jacobconley** [comment]
Wonderful diagrams there, I came to the issues page looking for a formal grammar spec to write a parsing extension for Hacklang and this looks like just what I needed.

**Comment by greggirwin** [comment]
Nice work. We're working on a live-coding RR diagram generator, if anyone is interested in testing and giving us some feedback.

**Comment by greggirwin** [comment]
Your TOML.abnf grammar exposed a couple bugs in our ABNF metagrammar. With those fixed, and a couple alternatives reordered, we were able to use your grammar, as well as our own, to generate diagrams.

**Comment by grinapo** [comment]
Not sure where to mention that the `MultilineString` accepts multiple `Newlines` after `backslash` as far as I see.

**Comment by pradyunsg** [comment]
@greggirwin Awesome! Is there some place we can see this, and try it out ourselves?

**Comment by greggirwin** [comment]
@pradyunsg, we're doing an invited beta for Windows testers right now. I can add you to our Gitter room for that, and/or send you a test release directly.

**Comment by pradyunsg** [comment]
OK, I'm gonna go ahead and say that this isn't gonna happen, given that we've not made a move on this in over two years.

Thanks for the suggestions/recommendations folks. :)
