### ISSUE TITLE
Clarify LocalTime highlight

### ISSUE THREAD

**Issue by zigszigsdk** [toml-lang/toml#628]
https://github.com/toml-lang/toml#local-time

Why is it highlid white on red? In previous examples, that means that that's erroneous. So is this incorrect too, then? If so, what is the correct way to write a LocalTime?

**Comment by pradyunsg** [comment]
That's a bug with GitHub's syntax highlight. Could you file an issue over at https://github.com/github/linguist?

**Comment by BinaryMuse** [comment]
GitHub uses the [TextMate TOML bundle](https://github.com/textmate/toml.tmbundle) for highlighting `.toml` files (as shown below) so any issues are best filed in [`textmate/toml.tmbundle`](https://github.com/textmate/toml.tmbundle/issues).

![image](https://user-images.githubusercontent.com/189606/59314380-ed2b3f80-8c69-11e9-9636-a07f56d9505b.png)

**Comment by pradyunsg** [comment]
Ah perfect, thanks @BinaryMuse!

Filed https://github.com/textmate/toml.tmbundle/issues/12.

**Comment by pradyunsg** [comment]
Thanks for spotting this and filing an issue @zigszigsdk! :)
