### ISSUE TITLE
Add advice to not define dotted keys out-of-order

### ISSUE THREAD

**Issue by pradyunsg** [toml-lang/toml#632]
This should be after the example of ASCII-float keys in "Keys" section.

**Comment by rwitzel** [comment]
Is something preventing to do it? It is blocking release of TOML 1.0, right? Is it really important to be included in 1.0? Can't it wait until 1.1?

**Comment by workingjubilee** [comment]
There is a PR open, it just needs to get merged in. Speaking of

**Comment by LongTengDao** [comment]
I can't wait for 1.0, it's so expected
