### ISSUE TITLE
Transalator

### ISSUE THREAD

**Issue by TomasRoj** [toml-lang/toml#635]
Does something like JSON to Toml translator exists?

**Comment by eksortso** [comment]
The list of [converters](https://github.com/toml-lang/toml/wiki#converters) on the wiki includes at least one JSON-to-TOML conversion tool. Not sure how well it works, but it may fit your needs.

**Comment by TomasRoj** [comment]
Thanks, I am problably going to write my own.

**Comment by eksortso** [comment]
Wish you well. For simple JSON docs (currently those with top-level hashes and no nulls), decoding the JSON then encoding the resulting object into TOML may be your fastest conversion tactic.
