### ISSUE TITLE
Unclear whether multiple key/value pairs can be on a single line

### ISSUE THREAD

**Issue by mmakaay** [toml-lang/toml#637]
When testing my implementation of TOML 0.5.0 against the BurntSushi test set, one test that failed whas the test where there are multiple key/value pairs on a single line. My parser accepted this and during development I did interpret the spec as such consciously.

The spec says "The key, equals sign, and value must be on the same line"
That tells me that this group of three elements must not have inner newlines.
It doesn't say that after a completed key/value pair, there cannot be another pair.

So, based on the spec, I implemented this as valid:
```
key1="value1" key2="value2"
```

If you look at the description of a [table] element, then there's the following text in the spec: "They appear in square brackets on a line by themselves. ". Because of that clear wording, I derived that the same thing didn't apply to key/value pairs.

Since I only seem to find tests that reject this syntax, and examples show key/value pairs on their own line, I went for it and updated my parser to expect an end of line after the value assignment. 

Should be spec be updated to be more clear on this?

**Comment by pradyunsg** [comment]
Thanks for filing this!

It's not valid. You can only have one key-value pair in a line (unless in an inline table).

> Should be spec be updated to be more clear on this?

Do you have a concrete suggestion on what language we should add?

**Comment by eksortso** [comment]
May I suggest the following, or something like it? This example would explain the concept well, after the first few examples in the spec show the key/value pairs on separate lines.

---
Key/value pairs are separated with one or more newlines. Running pairs together on the same line is not permitted. (See [Inline Table](https://github.com/toml-lang/toml#inline-table) for exceptions.)
```toml
first = "Tom" last = "Preston-Werner"  # INVALID
```

**Comment by ChristianSi** [comment]
It's true that this isn't yet explicitly mentioned in the spec -- something that should clearly be corrected.

**Comment by mmakaay** [comment]
My suggestion would be to use the same kind of wording as used to explain that a [table] must be on its own on a line. So maybe a little extension of the wording would do: "The key, equals sign, and value must be on the same line by themselves".

I think eksortso's suggestion is better than mine would have been. The example makes things crystal clear.

**Comment by pradyunsg** [comment]
@eksortso's suggestion LGTM. Happy to merge a PR, in case someone gets to it before me. :)

**Comment by mmakaay** [comment]
A pull request is created.
I tried to keep the changes to the spec as minimal as possible.

**Comment by mmakaay** [comment]
The pull request was merged, so I'm closing the issue.
