### ISSUE TITLE
Unclear whether table [a] can be defined after [a.b] has been defined

### ISSUE THREAD

**Issue by mmakaay** [toml-lang/toml#638]
When implementing my parser, the BurntSushi parser taught me that the following is valid:
```
[a.b]
some="key"
[a]
lala="lalala"
```
The part of the spec related to this is:
```
You don't need to specify all the super-tables if you don't want to.
TOML knows how to do it for you.

# [x] you
# [x.y] don't
# [x.y.z] need these
[x.y.z.w] # for this to work
...
Like keys, you cannot define any table more than once. Doing so is invalid.
```
How I interpreted this, was that `[x.y.z.w]` would be equivalent to 
```
[x]
[x.y]
[x.y.z]
[x.y.z.w]
```
and that therefore, in the following definition, the definition of `[x]` would be invalid, since under the hood that table was already created:
```
[x.y.z.w]
[x]
```

I updated my code to allow this definition now, by keeping track whether or not a table was created implicitly or explicitly. Table `[x]` as created by `[x.y.z.w]` is implicit and I upgrade it to an explicit table based on the next definition of `[x]`.

Is this indeed the intended behavior of TOML?
If yes, then the specification could do with a clarification on that. 
Two directions that I see for this:

1) use the implicit / explicit terminology. E.g. "You don't need to specify all the super-tables if you don't want to. TOML will implicitly create the intermediate tables for you. [..] Like keys, you cannot define any explicitly defined table more than once. Doing so is invalid."

2) focus on key being used for defining the table. E.g. "Like keys, you cannot define a table for a given key more than once. Doing so is invalid."

Adding an example would of course explain things beyond any doubt. It could be a little extension of the existing explanatory example:
```
# [x] you
# [x.y] don't
# [x.y.z] need these
[x.y.z.w] # for this to work

[x] # you can still define this one afterwards
```

**Comment by ChristianSi** [comment]
Yes, that's indeed the intended behavior. An "implicit table" is still not, technically, "defined" (at least not by you), hence explicitly defining it later does not violate the "you cannot define any table more than once" rule.

It might be useful to add the sentence such as "Tables may be defined in any order" to the spec, followed by an example such as the one you gave:

````toml
[a.b]
some="key"
[a]
lala="lalala"
````

**Comment by mmakaay** [comment]
Yes, that would have made it crystal clear to me.

**Comment by pradyunsg** [comment]
Happy to add a small clarification for this.

**Comment by mmakaay** [comment]
A pull request is created.
I tried to keep the changes to the spec as minimal as possible.

**Comment by mmakaay** [comment]
The pull request was merged, so I'm closing the issue.
