### ISSUE TITLE
Proposal for a better definition of the multiline basic string concatenation backslash

### ISSUE THREAD

**Issue by mmakaay** [toml-lang/toml#639]
In the ABNF definition, the multiline basic body is defined as such:
```
ml-basic-body = *( ml-basic-char / newline / ( escape ws newline ) )
```
Although this definition can be used to validate a multiline basic string, it does miss the semantics of the folowing part the specification: "When the last non-whitespace character on a line is a \, it will be trimmed along with all whitespace (including newlines) up to the next non-whitespace character or closing delimiter."

Another thing that can be improved, is the definition of a separate opener and closer, where the optional newline after the opener is included in the opener, so when parsing it semantically adheres to the correct element.

I already started working on a better definition, but am running into problems with either the instaparse parser, or my understanding of ABNF.
I'll get back with a working proposal. For now consider this a work in progress notification.

**Comment by mmakaay** [comment]
No wait, conceptually that shows what I would like to see, but it doesn't work like that in ABNF.
I'll get back on this.

**Comment by mmakaay** [comment]
I'm fiddling some more with the abnf definition, to also include the logic that after the opening '""""', a newline is ignored. So I want to make that one part of the multiline string opener. I'm getting the feeling that the instaparse code does not correctly handle abnf. Here's the code that I'm working with right now:
``` abnf
ml-basic-body = ml-basic-content
ml-basic-string-open = 3quotation-mark [newline]
ml-basic-string-close = 3quotation-mark
```
The reason I think that instaparse might have issues, is that there's a difference in handling when I use `[newline]`, `*1newline` or `0*1newline`. Only with the last of those three, the newline is added to `ml-basic-string-open` in the parse tree. For the other 2 cases, it is added to the `ml-basic-body`. That should not happen, reading the ABNF specification (which says these three forms are equivalent).

**Comment by mmakaay** [comment]
Okay, here's my proposal for multiline strings in ABNF. It produces semantically interesting chunks of data, which allows for simpler handling of the parsed results. This definition is unambiguous.
*(I left out the parts that are already defined in the TOML ABNF, and that need no changes)*

``` abnf
ml-basic-string = ml-basic-string-open ml-basic-body ml-basic-string-close

ml-basic-string-open = 3quotation-mark [ newline ]
ml-basic-string-close = 3quotation-mark

ml-basic-body = [ ml-basic-body-start ] *( ml-basic-body-join [ ml-basic-body-continue ] )
ml-basic-body-start = ( ml-basic-char / space ) *( ml-basic-char / space / newline )
ml-basic-body-join = escape ws newline *( wschar / newline )
ml-basic-body-continue = ml-basic-char *( ml-basic-char / space / newline )

ml-basic-char = ml-basic-unescaped / escaped
ml-basic-unescaped = %x21-5B / %x5D-7E / non-ascii
```

Using this definition, I was able to parse the following input string:
``` toml
ml_string = """
A   \
    	
      B\
"""
```

The multiline string is parsed as follows (hiccup output edited for brevity and clarity)

```
([:ml-basic-string
  [:ml-basic-string-open   [:quotation-mark "\""] x 3 [:newline "\n"]]
  [:ml-basic-body
   [:ml-basic-body-start [:ml-basic-char "A"] [:space " "] x 3]
   [:ml-basic-body-join  [:escape] [:ws] [:newline] [:wschar " "] x 4 [:wschar "\t"] [:newline] [:wschar " "] x 6 ]
   [:ml-basic-body-continue [:ml-basic-char [:ml-basic-unescaped "B"]]]
   [:ml-basic-body-join [:escape] [:ws] [:newline]]]
  [:ml-basic-string-close [:quotation-mark "\""] x 3 ])
```
When processing this parsed data, I can simply concatenate token [:ml-basic-body-start] and [:ml-basic-body-continue] tokens to get the data that make up the actual multiline string body.

**Comment by mmakaay** [comment]
I'm afraid that it's not really feasible to come up with an unambiguous ABNF in the style that I was going for. So here a simplified proposal for changing the multiline basic strinct definition:

``` abnf
ml-basic-body = *( ml-basic-char / newline / ml-basic-body-join )
ml-basic-body-join = ( escape ws newline )
```
So basically the definition as-is currently, but with the `( escape ws newline ) sequence defined as its own rule. That makes it possible to have this sequence in its own token in the parsing output, facilitating the interpretation of the tokens by a parser. Using this definition, it can check for `ml-basic-body-join`, instead of `do I see an escape, followed by whitespace and then a newline?`.

**Comment by pradyunsg** [comment]
Thanks for looking into this @mmakaay! I've gone through your posts and well, you flagged the reasons that your prior suggestions don't work already so I won't pile on. 😉 

> basically the definition as-is currently, but with the `( escape ws newline )` sequence defined as its own rule.

I don't feel that there's much value in doing _this_ -- we don't have a direct concept in the language specification, I don't want to bikeshed on the name, and, anyway, this proposed change is borderline too-trivial-to-bother-doing-independently.

**Comment by mmakaay** [comment]
Okay, no problem. It does cause some duplicate handling of the ( escape ws newline ) sequence, since the interpreting parser will have to recognize this one on its own as well, but that's indeed no biggy (I don't currently use the ABNF for my parser anyway, so it's not causing any bitemarks on me ;-) )

I'll close the issue.
