### ISSUE TITLE
Add `example-v0.5.0.toml`

### ISSUE THREAD

**Issue by chshersh** [toml-lang/toml#643]
Changelog suggests that version `0.5.0` was released on `2018-07-11`. But the [`examples`](https://github.com/toml-lang/toml/tree/master/examples) directory doesn't contain corresponding `example-v0.5.0.toml` file. I think it would be lovely to have an example of such file, so developers of the TOML parsers can test their implementations!

**Comment by pradyunsg** [comment]
Happy to see a PR for this! For TOML 1.0, I'm planning to populate the toml/compliance repository, with test cases for testing implementation (#585).

**Comment by pradyunsg** [comment]
We've dropped the examples directory entirely (in #752), and I think the compliance suite + example in the README should be sufficient. :)

**Comment by pradyunsg** [comment]
Thanks for filing this issue @chshersh! ^>^
