### ISSUE TITLE
Replace single-letter-key examples

### ISSUE THREAD

**Issue by uvtc** [toml-lang/toml#653]
In the readme, is this a typo:

---
As long as a key hasn't been directly defined, you may still write to it and to names within it.

    a.b.c = 1
    a.d = 2
---

Should that last line instead be a.b?

**Comment by uvtc** [comment]
I see. I was confused. The example directly after it suggested to me that it might be an order-dependent thing. As in (incorrectly),

~~~
# This is ok
a.b.c = 1
a.b = 2

# but
# THIS IS INVALID
a.b = 1
a.b.c = 2
~~~

You might consider giving the names here more meaning so they're less easily mistakeable for a typo, for example:

~~~
fruit.apple.fuji = 1
fruit.pear = 2

# But this is invalid:
fruit.apple = 1
fruit.apple.fuji = 2
~~~

**Comment by pradyunsg** [comment]
> You might consider using longer names here to make them less easily mistakable for a typo

Yup. Sounds like a plan. :)

**Comment by pradyunsg** [comment]
If someone could file a PR to fix this, that'd be great! ^>^
