### ISSUE TITLE
More meaningful ml-basic-body's newline escaping

### ISSUE THREAD

**Issue by josuah** [toml-lang/toml#669]
## Context

The ABNF spec, while still valid on that part, could benefit from some improvement:

The README.md shows:
```toml
str2 = """
The quick brown \


  fox jumps over \
    the lazy dog."""
```

And in ABNF:
```ABNF
ml-basic-body = *( ml-basic-char / newline / ( escape ws newline ) )
```

This works:  After the first `\`, there might be multiple whitespaces until a newline is reached, then the next newlines match the standalone `newline` token.

## Problem

But this does not correspond to the semantics: the `newline` token is for inserting an actual newline token into the buffer, while `escape ws newline` is for skipping newlines or whitespaces.

## Proposed solution

I suggest either adding a `ignored-ws-nl` ABNF token:
```ABNF
ml-basic-body = *( ml-basic-char / newline / escaped-ws-nl )
escaped-ws-nl = escape 1*( wschar / newline )
```

Or changing the current token:
```ABNF
ml-basic-body = *( ml-basic-char / newline / ( escape 1*( wschar / newline ) )
```

[EDIT]: it needs at least one whitespace *or* newline

Both seems compatible with the proposed solutions for #640.

I am going for the extra token in my implementation.  I can provide a patch if wanted.

Cheers!

**Comment by eksortso** [comment]
Good catch, @josuah.

According to the README, escaped whitespace in a multi-line basic string begins with a "line ending backslash", and a backslash before a space or tab is not valid. Could you alter your proposal to specify both an `escape` and a `newline` to start the escaped whitespace?

I wanted to provide a working variant of your proposal that addresses this change. But I tried several variants in [Instaparse](http://instaparse.mojombo.com/), and couldn't find a variant that didn't lock up the parser.

**Comment by josuah** [comment]
It had to be changed a bit so that a parser have no choice but  to take the escaped whitespace/newlines into account and not have opportunity to consider "escaped-ws-nl" over and fallback to regular newlines / whitespaces:

```
some.string = """ Some string \
allow leading ws ^             ^ this nl is escaped, so:

^ this newline as well, but given we are in a *( ), the parser can choose to stop

^ same story here: are we part of escaped newline or a regular newline

^ there is no end delimiter: the "delimiter" will be part of the string content
  here it is over"""
  ^ this ends it.
```

Solution: toss whitespace out of ml-basic-char, and only allow ws after a basic char or at beginning of input.

**Comment by josuah** [comment]
Adding an extra token is leading [instaparse][1] to produce multiple versions because its `*` operator works this way (try all possible branches of parsing).

@ChristianSi notes that it is more commonly greedy so this would only introduce ambiguity on instaparse:
> The [ABNF] repetition operator is "greedy", meaning that it always matches the longest possible string. It never backtracks to see if a shorter match would succeed -- http://www.coasttocoastresearch.com/overview

[1]: http://instaparse.mojombo.com/

P.S.: Thanks to @ChristianSi and @ehuss for proofreading my dull mistakes.
