### ISSUE TITLE
[ABNF] lowercase hex digit

### ISSUE THREAD

**Issue by mrjbq7** [toml-lang/toml#672]
Noticed that it doesn't support lowercase hex digits like ``0xdeadbeef``:

```
HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"
```

**Comment by ehuss** [comment]
ABNF is case-insensitive.

**Comment by workingjubilee** [comment]
Specifically, by default it is, and case-sensitivity must be layered on with RFC 7405's specialized syntax: https://tools.ietf.org/html/rfc7405

**Comment by pradyunsg** [comment]
As others have pointed out, ABNF is case-insensitive.
