### ISSUE TITLE
Ambiguous input: \u01234567890ABCDEFGH

### ISSUE THREAD

**Issue by josuah** [toml-lang/toml#675]
Given TOML aims for supporting \u followed by both 4 and 8 bytes, there is a possibility to have ambiguous data:

```
  vvvv
\u0123|4567|89ABCDEFGH
  ^^^^ ^^^^
```

- Parse 4 bytes as above?
- Parse 8 bytes as below?

We probably want to review the choices made by the various implementations and decide what to keep.

**Comment by pradyunsg** [comment]
I don't think that's needed. IIUC, Unicode scalar values are unambiguous in this use case.

**Comment by eksortso** [comment]
The lowercase version, `\u`, is followed by four digits. It's the uppercase version, `\U`, that takes eight digits. In both cases, it's unambiguous.

**Comment by josuah** [comment]
My bad! I'll try to triple check before opening a new issue!
