### ISSUE TITLE
Make numbers more abstract

### ISSUE THREAD

**Issue by clarfon** [toml-lang/toml#682]
It would be nice to allow an abstract representation of numbers, rather than the very concrete, implementation-based version we have right now. There could be a "compatible TOML" variation that could be allowed to revert back to the current behaviour.

A few concrete things to note:

1. Integers may be arbitrary precision, but in compatible TOML, must fit in 64 bits in two's complement.
2. Floats are always "exact", but in compatible TOML, must be losslessly convertible to/from IEEE 754 binary64 format.

Another thing that I would recommend is enforcing that TOML as a format does not distinguish between integers and floats, and that compatible TOML will only require that numbers fit into one of the two implementations. This means that, for example, 9_007_199_254_740_993.0 is valid in compatible TOML because it is exactly an integer, but the same number with a `.1` is not because it is not exactly a float. (I would call this bad style, but not bad syntax.)

This would also mean that numbers like 1e6 would be valid integers.

This gets rid of the "everything is a float" implication that formats like JSON have, while also allowing numbers to be treated as a uniform type in TOML. Parsers would still make the int/float distinction, but config writers would mostly not care unless they used extremely precise or large numbers.

**Comment by ChristianSi** [comment]
What's wrong with the current requirements? Considering that arrays are now heterogeneous, I see no reason why it should matter whether in TOML's conceptual model there two different numeric types or just one.

Also, I note that in Python, `type(1e6)` is `float`, same as in TOML. Using exponent notation for integers is unusual, at least, and it also seems inconsistent, since with a *negative* exponent you certainly *won't* get an integer.

**Comment by ChristianSi** [comment]
Also, note that implantations allowing integers of arbitrary size are compatible with the spec. The spec only requires that *at least* the "64 bit (signed long) range" must be supported. Anything beyond that is, of course, fine too.

**Comment by lmna** [comment]
> It would be nice to allow an abstract representation of numbers
> Integers may be arbitrary precision
> Floats are always "exact"

How would configuration files benefit from arbitrary precision integers and from "exact" floats? Is proposed degree of abstractness of numbers sufficient, or should we make one step further and support [algebraic numbers](https://en.wikipedia.org/wiki/Algebraic_number), complex numbers, [quaternions](https://en.wikipedia.org/wiki/Quaternion), etc?

**Comment by clarfon** [comment]
@ChristianSi I think that being able to write `5e9` to indicate five billion is not unusual, even though a lot of languages still explicitly state this is a float.

Although from what it seems, honestly, this isn't that great of a proposal anyway, and I'll close it.
