### ISSUE TITLE
`Integer` type specification question

### ISSUE THREAD

**Issue by alan-isaac** [toml-lang/toml#688]
The spec says:
"64 bit (signed long) range expected (−9,223,372,036,854,775,808 to 9,223,372,036,854,775,807)".
Is this meant to be the *minimum* integer range (so that, e.g., JavaScript implementations must use `BigInt`)? Or what?

**Comment by abelbraaksma** [comment]
This is the standard range for any 64 bit signed integer. If you have 64 bits, one is used as the sign bit, and then you get that range by default. See https://en.m.wikipedia.org/wiki/9,223,372,036,854,775,807

Most languages support 64 bit signed integers, it's `long` in C# for instance.

**Comment by abelbraaksma** [comment]
In Javascript, this means you lose precision, as it has only 15 digits precision due to all numbers being stored as 64 bit floating point. Ergo, only 52 bits are use for the integer part.

**Comment by alan-isaac** [comment]
My question is about the meaning of "expected".  Here are things it could mean. i. You must use a 64 bit signed integer if it is available, otherwise the spec is silent (even if, e.g., a `BigInt` type is available).  ii. You must use type with at least the range of a 64 bit signed integer if it is available, otherwise the spec is silent (so e.g. in JavaScript, use `BigInt`).  iii. Etc.

Shouldn't the spec be ... specific?

**Comment by abelbraaksma** [comment]
I agree it's vague. Also, it's currently at the bottom of the section on integers, I'd personally prefer range limits on types to be the first thing you see.

My take on this: it's like 'should' vs 'must' in W3.org specifications. The range should be of signed 64 bits, but if a language doesn't support this natively, it can pose a different limit on it. But someone with more knowledge of the spec should chime in here ;). 

And perhaps we can reword that phrase for clarity,or have a specific section on ranges of data types in general.

**Comment by alan-isaac** [comment]
Ideally the spec will make it clear e.g. whether a JavaScript parser should fall back to `number`, fall forward to `BigInt`, or consider the meaning to be completely undefined. I assume the intent is that JavaScript should use `BigInt`.  (That still leaves open the interesting question of what it was "expected" before there was a `BigInt`.)

**Comment by abelbraaksma** [comment]
Some TOML is an open specification that's agnostic to the implementing language, it shouldn't advice on Javascript or any other language specifically.

However, there are certain invariants between languages that are assumed, and where this assumption does not hold, we should say what implementors are allowed to do. Does conformance mean: the whole range, or is a subrange also conformant? 

Whether an implementor chooses bigint or another way to express 64 bit integers is an implementation detail the spec shouldn't have to concern itself with. Same is true for how nested arrays are implemented, i.e. as jagged arrays, as nested arrays, as sequences of arrays or something else? Just to say, that's not relevant what TOML concerns. 

BTW, same things can be said for, for instance, Unicode strings. Is an implementation valid if it cannot support the whole range of Unicode? Or if limits are imposed on array size?

**Comment by alan-isaac** [comment]
Understood.  The JavaScript example was meant only to highlight one situation where the spec is not providing adequate guidance, not to suggest JavaScript should be separately addressed.  I meant to  discuss the intent of the spec for *any* language facing the kind of tradeoffs faced by JavaScript.  I refered to JavaScript only because it is a very popular language where TOML use is increasing rapidly but where this part of the spec provides inadequate guidance for implementers.

**Comment by ChristianSi** [comment]
I'd say that it's the minimum range, yes. All integers in this range **must** be accepted by a parser and **must not** be silently converted into a different number. So, if a JavaScript implementation encounters an integer whose absolute value is so large that it cannot losslessly be expressed as a Number, the parser must return a BigInt instead.

In my understanding, TOML doesn't force implementations to use the same native type for all values of a TOML type, so it's perfectly fine to use Numbers for all TOML integers in the range from `Number.MAX_SAFE_INTEGER` to `Number.MIN_SAFE_INTEGER`.

**Comment by YoYoYonnY** [comment]
> So, if a JavaScript implementation encounters an integer whose absolute value is so large that it cannot losslessly be expressed as a Number, the parser must return a BigInt instead

I don't interpret the wording of the TOML spec that way, but either way, this should really be an implementation detail, not part of the spec. TOML parsers should be able to _parse_ a TOML file that follows spec, but shouldn't necessairly be able to _represent_ every valid TOML file.

ex: Hand-written C parser for simple config file that only recognizes certain keys, and automatically returns an error otherwise (Or ignores them, point is it doesn't represent all TOML files in the same way, but the files themselves are still considered "TOML" files).

**Comment by ChristianSi** [comment]
This issue can be closed now, as it was accidentally fixed by #739 (after an independent rediscovery of the mentioned ambiguity).
