### ISSUE TITLE
Publish release candidate for 1.0

### ISSUE THREAD

**Issue by ChristianSi** [toml-lang/toml#698]
As far as I can see, [TOML 1.0](https://github.com/toml-lang/toml/projects/1) is now feature-complete except for a [website](https://github.com/toml-lang/toml.io/issues/1) and a Standard Test Suite (#585). That's very good news but it also means that we need to seriously think about getting v1.0 released and published.

A website, while nice to have, is certainly not essentially – for the last 7 years TOML has done just fine by living on GitHub. And while a comprehensive test suite would be great, it would be an add-on to the spec rather than an integral part of it. Also it seems that no recent work has been done on the test suite at all and it is clear that a *comprehensive* test suite would be a monumental task. I'd argue that this huge unfinished business shouldn't stop v1.0 either. A test suite is important, but it can be released and expanded after the finalization of the spec itself – and it will probably never really be "finished".

Hence I propose that we publish a release candidate for 1.0 **now** (maybe after proofreading the spec once more). It's feature-complete and it's time. After publishing the RC, announce it widely to collect as much feedback from the community of users and implementers as possible.

If nothing serious comes up within 2 to 3 months, rename the RC to 1.0 proper. Otherwise publish a new RC and iterate.

**Comment by pradyunsg** [comment]
Honestly, we're basically stuck on me finding about a week to do all the things needed here (write the compliance tests, cut the rc-release, reach out to maintainers and a bunch more minor tasks).

I'm happy to make a 1.0.0-rc1 later this month (possibly next week?). If anyone has any suggestions for communication around this release, I'm all ears. :)

**Comment by h-vetinari** [comment]
> @pradyunsg: I'm happy to make a 1.0.0-rc1 later this month [...]

February has come and gone - are there any updates on the planned timeline for `1.0.0-rc1`?

**Comment by marzer** [comment]
@pradyunsg since the remaining tasks for 1.0.0 seem to be mostly administrative, perhaps 1.0.0-rc1 could be released ASAP with the spec exactly as it is now, and the full-fledged 1.0.0 release could include the remaining bits?

**Comment by eksortso** [comment]
Perhaps as soon as [toml.io](https://toml.io)  is up, the first release candidate could go out.

That's just my opinion though.

**Comment by ChristianSi** [comment]
@eksortso:

> Perhaps as soon as toml.io is up, the first release candidate could go out.

I see absolutely no reason why we should wait for that. A new website is nice to have, but TOML is just as useful without it. Also, there will in any case be months between the RC and 1.0 final. Having the website finished when 1.0 final is released would be great (though by no means essential), but toml.io shouldn't block the finalization process itself.

**Comment by eksortso** [comment]
>A new website is nice to have, but TOML is just as useful without it.

That is true. Its usefulness is already well-established. But a dedicated website does indicate the level of commitment that a project has. Something for casual or curious observers to latch on to. That's why I'm convinced a website is essential for 1.0.

We can continue to point users here. GitHub really isn't a place for casuals or the merely curious, though, unless they're technically minded enough to follow the project.

>Also, there will in any case be months between the--

Jeez. I'm convinced now. Release 1.0rc1 already! :)

**Comment by h-vetinari** [comment]
Another month, another friendly ping. :)

Also big +1 that not all `1.0-final`-related tasks need to be done for `1.0-rc`.

**Comment by pradyunsg** [comment]
My mental health took a sharp dive in late-Feb/March, so I've fallen behind on a whole bunch of my OSS responsibilities (like TOML). We'll tackle the bus factor problem for TOML, when I'm in better shape.

There's a release process for TOML now, so that I can actually do releases without feeling like you've missed something. Other than that, I'll be waiting for a day (I don't want to be releasing on April 1st) before merging/tagging 1.0.0-rc.1, so if anyone spots something drastically wrong with the Release PR above -- holler there!

**Comment by marzer** [comment]
Looks good to me! :D

> "Bus factor"

Hah. Today I learned.

**Comment by h-vetinari** [comment]
> My mental health took a sharp dive in late-Feb/March, so I've fallen behind on a whole bunch of my OSS responsibilities (like TOML). We'll tackle the bus factor problem for TOML, when I'm in better shape.

Sorry to hear you haven't been well, and for piling on on top of that. Hope you get better soon!

**Comment by pradyunsg** [comment]
TOML 1.0.0-rc1 is out in the wild!

Thanks everyone for the nudges! Implementations are welcome to update themselves to 1.0.0-rc1. In general, more syntax is considered valid in this version compared to the previous versions.

There are a couple of areas where help and feedback is welcome:
- writing specification tests for 1.0.0-rc1 in the same format as burntsushi/toml-test.
- identifying any ambiguities in the specification (in the prose, or the abnf)

It's fairly likely that this repository gets significantly reorganised prior to the final 1.0.0. No promises on the timeline for 1.0.0 though. :)

**Comment by marzer** [comment]
> Please make sure to not advertise support for TOML 1.0.0-rc* as being TOML 1.0.0 support.

Oops. Think I got a bit lazy with some of my parser's documentation on that front.
