### ISSUE TITLE
Object references in TOML

### ISSUE THREAD

**Issue by James-Hudson3010** [toml-lang/toml#699]
Has any thought been given to including the JSON concept of a [Reference](https://json-spec.readthedocs.io/reference.html) into the TOML spec?

In my use case, would love to be able to treat TOML as a complete replacement of JSON, but that concept in JSON is important to maintain.

**Comment by eksortso** [comment]
That concept of Reference isn't actually a part of the core JSON spec (i.e. ECMA-404), but an add-on that can be expressed in JSON and interpreted by a parser that can do JSON References.

The TOML spec is like ECMA-404, in that it's all about the core language. References could be done similarly to how they're done in JSON, like so:
```toml
[external]
"$ref" = "http://some/where"
```

A TOML references spec, if one were made, wouldn't belong to the core TOML spec, though. It would be a complementary specification.
