### ISSUE TITLE
Wrong output when using 2 part dotted keys with multiline strings

### ISSUE THREAD

**Issue by gonzalezzfelipe** [toml-lang/toml#708]
I'm seeing this unwanted behaviour when using multiline strings. I have 2 toml's that are completely equivalent AFAIK, yet they produce different results:

```toml
[test]
foo.bar = "test"
```
```toml
[test]
foo.bar = """\
  test\
  """
```

When loaded, they produce this different results:

```python
>>> import toml
>>> example_1 = '''[test]\nfoo.bar = "test"'''
>>> print(toml.loads(example_1))
{'test': {'foo': {'bar': 'test'}}}
>>> example_2 = '''[test]\nfoo.bar = """\\\n  test\\\n  """'''
>>> print(toml.loads(example_2))
{'test': {'foo': {}, 'bar': 'test'}}
```

I'm using `toml==0.10.0`, Python 3.6.8.

**Comment by marzer** [comment]
This repository is the home of the TOML _language_, not any particular implementation. You probably want the python `toml` package repo: https://github.com/uiri/toml

**Comment by gonzalezzfelipe** [comment]
You are right, sory for the inconvenience.

**Comment by nat-n** [comment]
Link to new issue: https://github.com/uiri/toml/issues/286
