### ISSUE TITLE
Support \e ESC Escape Character

### ISSUE THREAD

**Issue by nixpulvis** [toml-lang/toml#715]
I'm excited to see the progress of #709, however one other escape that seems to really be missing is `\e` (`ESC`) which is `\x1b`.

For example, `echo -e '\e[31mfoo\e[0m'` on an ANSI compatible terminal will print `foo` in red.

I'm wondering how people here feel about adding this to TOML?

For what it's worth, the maintainers of [Alacritty](https://github.com/alacritty/alacritty) are considering switching from YAML to TOML, and being able to express terminal escape sequences easily would be very nice for us.

**Comment by pradyunsg** [comment]
Seems reasonable. :)
