### ISSUE TITLE
since there are v0.3.1 to fix incorrect example, should there also be v0.5.1 for same reason?

### ISSUE THREAD

**Issue by LongTengDao** [toml-lang/toml#722]
1. Wrong float example https://github.com/toml-lang/toml/blame/master/versions/en/toml-v0.5.0.md#L417 which is fixed in v1.0.0-rc.1.
2. And missed menu `MIME Type` item between line 42 and 43.

**Comment by eksortso** [comment]
Go ahead and submit a PR to update the table of contents. We don't need a v0.5.1 for this. Worst case scenario, another release candidate could be released before the final v1.0.0. But for small corrections, another rc won't be necessary.

**Comment by LongTengDao** [comment]
@eksortso I know what you mean, but I'm not sure if docs kind of spec could modify after release. If can, then why there was a v0.3.1, which was only to fix date example.

**Comment by pradyunsg** [comment]
I don't think there's much value in releasing patch releases for the older version, when we're moving toward a major release. Plus, this isn't significant and the timeline of 0.3.0 vs 0.3.1 would be very different from 0.5.0 vs 0.5.1 if we make the release now.

Feel free to file a PR for adding the "Table of Contents" amendment. Let the mistake in the float example stay-as-is; it can stay that way forever.

So, to answer the question in the title with fewer words: no. But we can fix the "Table of Contents" mistake via a PR to 0.5.0.
