### ISSUE TITLE
maybe mistake

### ISSUE THREAD

**Issue by LongTengDao** [toml-lang/toml#723]
https://github.com/toml-lang/toml/blame/master/README.md#L18

Maybe `non-` should be removed? Or it's correct in English expression?

---

BTW:
1. https://github.com/toml-lang/toml/blame/master/README.md#L795 has two spaces after period.
2. https://github.com/toml-lang/toml/blame/master/README.md#L794 the space after `key/value` is `\xA0`, not `\x20`.
3. https://github.com/toml-lang/toml/blame/master/README.md#L945 ` or of compatible type` should be removed, because now mixed type array is ok.

Since it's rc version now, fix them is not too late.

**Comment by marzer** [comment]
The "non" is correct here; it's saying that the will only be changes between the RC and full release if something critical comes up.

For the other minor text formatting things, you could submit a pull request...

**Comment by LongTengDao** [comment]
@marzer Does "critical change" mean "important change" and "break change" here?
But the whole sentence seems tried to tell people version 1.0.0-rc.1 is very stable, and won't have "important" nor "break" change with version 1.0.0 in the future?

**Comment by pradyunsg** [comment]
+1 to all that @marzer said. :)

That language basically keeps the option to make a change open. I think it also clearly communicates that we don't plan to make any changes to the to the language's design without a very strong reason to do so, between now and 1.0.0.

**Comment by LongTengDao** [comment]
I see, so this sentence means that 1.0.0 won't have big changes, except the change (problem) is too big, which we have to change. Thank you!
