### ISSUE TITLE
Clarification: same bare and quotted keys sematically equivalent?

### ISSUE THREAD

**Issue by CuiCui66** [toml-lang/toml#733]
The question is simple: Do `a` and `"a"` refer to the same semantic key?

For example, is that forbidden?
```toml
a = 4
"a" = 5
```

My interpretation of the specification is that `a` and `"a"` are the same semantic key. It is what makes the most sense for me. However the implementation I use in Ocaml, [To.ml](https://github.com/ocaml-toml/To.ml), make them semantically separate. They have either `KeyBare of string` or `KeyDotted of string` (That's a sum type for those that do not know Ocaml) and so bare key and dotted keys can never overlap. Did I misunderstood or should I raise an issue on their side.

Furthermore, once this is clarified here, I strongly suggest you make it explicit in the standard because even if I read it one way on my first read, I have to admit I cannot prove that the other interpretation is wrong with the current specification text.

**Comment by abelbraaksma** [comment]
I agree it is not explicitly mentioned in the spec that they are the same. To the best of my knowledge, `name`, `"name"` and `'name'` are equivalent, and while a parser may distinguish them while parsing, they should ultimately translate to the same key: the same name quoted or not should lead to an error. 

Maybe there's a test case that covers this? If not, it would be good to add one. 

Someone with more knowledge of the spec should probably give his or her insight here as well ;).

**Comment by eksortso** [comment]
All keys in TOML resolve to strings. To this end, treat bare keys like basic literal strings without the surrounding single quotes.

So it follows that `k`, `"k"`, and `'k'` are all the same key. Likewise, `k` is the same key as `"\u006b"`.

**Comment by ChristianSi** [comment]
It might be useful to explicitly mention that keys are strings. Currently that is more or less implied.

Also, the example

```toml
# DO NOT DO THIS
name = "Tom"
name = "Pradyun"
```

could be changed to:

```toml
# DO NOT DO THIS
name = "Tom"
"name" = "Pradyun"
```

**Comment by eksortso** [comment]
That's reasonable. I'll make a PR.

**Comment by pradyunsg** [comment]
What @eksortso said is correct.

I really don't think we need to make changes to the spec for this, since I think the only reason this issue came up is that an implementation is not handling them as expected. I'd much rather push correctness in implementations on this front through the compliance tests, rather than complicate our "keys" section more.

**Comment by ChristianSi** [comment]
@pradyunsg I disagree and would argue that a least short explanation would improve the spec. Right now the string-nature of keys is merely implied, but never states clearly and unambiguously.

Also, not every TOML document can be mapped losslessly to a JSON document, nor vice versa. (JSON lack's TOML's date/time types, TOML lack's JSON's `null`.)

**Comment by pradyunsg** [comment]
I think the string nature of keys is clearly stated.

> Bare keys may only contain ASCII letters, ASCII digits, underscores, and dashes (A-Za-z0-9_-). Note that bare keys are allowed to be composed of only ASCII digits, e.g. 1234, but are always interpreted as strings.

> Quoted keys follow the exact same rules as either basic strings or literal strings and allow you to use a much broader set of key names. Best practice is to use bare keys except when absolutely necessary.

---

I am well aware that TOML is not entirely equivalent to JSON. :)

My point was, there are examples that already clarify this detail (like the `pi` example, the dotted keys example etc). They show the equivalent in "JSON land" where dotted and bare keys are both represented as strings.

This specific issue of `"string"` being the same as `string`, on the LHS of a key-value pair, is not worth calling out explicitly IMO. I'd much rather have a test case in the compliance suite to make sure parsers reject `a = 1\n"a" = 2`.

**Comment by ChristianSi** [comment]
@pradyunsg O-kay, consider me convinced!

**Comment by abelbraaksma** [comment]
> I think the string nature of keys is clearly stated.

As a spec writer myself (xslt), I've come to learn that specs need to be very explicit. That keys are strings is implied, which is not good. 

I'd argue to simplify the definition, instead of complicating it. For instance, all becomes clear by making the first line something like:

> A key is a string and may be either bare, quoted, or dotted. The quotes are not part of the key name.

Or, because we need to be language agnostic (interpretations may store a key using a different format):

> A key is interpreted as a string and may be either bare, quoted, or dotted. The quotes are not part of the key name.

Either definition removes any ambiguity about how the rest of the text on keys needs to be interpreted.

**Comment by eksortso** [comment]
After v1.0.0 is released and the website is up, it may be necessary to change the README from a user-centric document to a full-on strict specification. Either that, or introduce a new document as the official spec and repurpose the README as a companion document for new users. The spec would include the ABNF as an appendix, and it would codify behaviors captured in the compliance tests that the README or website doesn't explicitly mention.

**Comment by ChristianSi** [comment]
Why not do it as @abelbraaksma has suggested?

**Comment by eksortso** [comment]
@ChristianSi In principle I fully agree with @abelbraaksma's proposed changes. I do think there must be a clean break between README the configuration manifesto and README the detailed specification. Unless we draw a line it'll never get done.

That line, though, is in the future of the TOML spec, not now. I seriously don't want v1.0.0 held up any longer. The practicality of the spec on hand, which has already gained some accolades, already beats the purity of having our very own ECMA-404.

**Comment by abelbraaksma** [comment]
> Unless we draw a line it'll never get done.

I'd suggest marking bugs as editorial, minor or major/critical in this stage, where only critical bugs would delay publishing version 1.0. Bugs like these are in the minor or editorial range, as it merely asks for clarification. 

A very literal reading of the spec might reveal more bugs like these. But the spec as it is has proven to be pretty stable and quite well and unambiguously understood by many implementers. Certainly, small differences in interpretation exist, but there's nothing wrong with publishing a spec as "official" for v1.0, de editing it in place a few times wrt to editorial bugs (the ones that don't change any features if the spec), as long as you document that carefully (let's say by saying something like "this document was edited in place to fix some links, and improve some wording, for details on the changes, see... ").

That way you can move on without worrying too much on getting it perfect the first time around, and/or with an empty list of bugs. As there's no such thing as a bug free spec (and you're pretty close to perfect already!).

**Comment by ChristianSi** [comment]
What's a status of this? Should a prepare a small PR following [abelbraaksma's suggestion](https://github.com/toml-lang/toml/issues/733#issuecomment-626171546)? Or do we just leave this as is for v1.0?

(Personally, I'm in favor of clarification. A question that has been asked in the past will surely come up again in the future.)

**Comment by abelbraaksma** [comment]
@ChristianSi, in light of time spend on this, it is probably quicker to just bite the bullet this time and put it in. Since it is a clarification and not a language change, it doesn't influence any implementation (though that argument can also be used to postpone this). For me, it's ultimately a flip of a coin at this stage.

**Comment by pradyunsg** [comment]
I'm not super convinced that this is needed still. Anyway, I'm happy to accept a single sentence change for this.

I'll add another bullet to my TODO item for "TOML spec: nuance clarifications", to think about this if/when I get to that item. :)

**Comment by eksortso** [comment]
"A key is simply a string in a table that defines a name for a given value." Would this work?

**Comment by abelbraaksma** [comment]
@eksortso, the whole point as to make it explicit that single and double quoted strings are treated equally. Have a look at my proposals that make that clear: https://github.com/toml-lang/toml/issues/733#issuecomment-626171546

**Comment by abelbraaksma** [comment]
If those proposals are not sufficient/satisfactory/clear enough, another approach is perhaps to change this:

> Whitespace is ignored around key names and values

Into this:

> Whitespace is ignored around key names and values;  delimiting quotes are not part of either the key name or value.

**Comment by eksortso** [comment]
@abelbraaksma I do not see how this will work well as a single sentence in the current README, but your text is certainly a lot better than mine.

Taking your suggestion into account here.  Consider, in a new PR, making this the first paragraph of the Keys section:

 > A key is treated as a string and may be either bare, quoted, or dotted.

Also, let's place this in the paragraph where dotted keys are explained. I explicitly called out the surrounding quotes.

> The quotes surrounding a quoted key are not part of the key name.

Nothing will be said about the distinction between basic and literal strings, and nothing will be said about multi-line strings in this context. Hope that works; it's been a rough day. What do you think?

**Comment by abelbraaksma** [comment]
LGTM. I think that certainly removes the ambiguity, I'd go for it!

Rough day here too, European bed time now :p.

**Comment by eksortso** [comment]
Thanks, @abelbraaksma.

So invalid tests still needs to be composed, and @pradyunsg already mentioned a good one, `a = 1\n"a" = 2`. I'll include `a = 1\n"\u0061" = 2` as another one, because that basic-string quoted key is equivalent to `a`. We'll offer those for compliance testing, which I'm still setting up but looking forward to running!

**Comment by abelbraaksma** [comment]
Similarly, perhaps a few tests like this:

```toml
# whitespace stripped, fail equal names
a     = 2
a = 3
# only surrounding whitespace is stripped, fail: illegal name
a b = 3
# whitespace relevant (but fail: illegal name)
"a " = 2
"a" = 3
# whitespace relevant (success test, values are NOTE equal)
a = " to do "
b = "to do"
# different quotes, fail same keys
a = 2
'a' = 2
# different quotes, fail same keys
'a' = 2
"a" = 2
# success test, capital not equal to small
a = 2
A = 3
# inner quotes are not stripped from value, a & b are equal
a = "\"quoted\""
b = """"quoted""""
# quote correction is not applied, fail syntax error
"a = "test"
'a = 'test'
"a = 'test"
'a = "test'
```

**Comment by abelbraaksma** [comment]
Hmm, I just checked the current text, and we say keys follow the exact same rules for "basic strings". Looking up strings show that _basic strings_ can be delimited with triplets like `"""` and singles like `"`. So I _think_ the above is allowed where I wrote `"""a""" = 2`, but since it is all red, I am not so sure anymore. Same is true for literal strings.

**Comment by ChristianSi** [comment]
@abelbraaksma: The spec defines "four ways to express strings: basic, multi-line basic, literal, and multi-line literal", but only two of them are allowed as quote keys: "basic strings or literal strings".

Hence, keys surrounded by triple quotes should indeed be rejected by a compliant parser. It's a good idea to add some negative test cases to make sure that's indeed the case.

**Comment by abelbraaksma** [comment]
@ChristianSi, it's a pity we call "multi line strings" basic. Hence my confusion. Same is true for literal. This leads to sentences like "x can take the form of a basic string" to be ambiguous. 

But I guess adding tests to rule this out should be sufficient. There are a few in my list anyway.

**Comment by marzer** [comment]
@abelbraaksma Your whitespace normalization test case above is wrong for `\n` and `\r`, per the spec:

> TOML parsers should feel free to normalize newlines to whatever makes sense for their platform.

**Comment by abelbraaksma** [comment]
@marzer, but that quote from the spec deals with whitespace, that is, actual whitespace and not escapes, so that a parser can safely normalize any input file before parsing. 

Here it's an escaped character, that's not the same. Surely a literal `\n` in a context where escaping is allowed, must translate to LF and `\r` to CR? It would be very surprising if that's not the case. Likewise, someone having `\u000D` really ought to be different than `\u000A`. These aren't whitespace in the sense of that spec quote, but escapes that translate to an exact Unicode character.

(if I'm wrong, then that's quite a surprising rule of toml that I hadn't expected)

**Comment by marzer** [comment]
Oh! Of course. Duh. I read the phrase "whitespace is not normalized", remembered the line in the spec, and immediately short-circuited. Carry on, heh.

**Comment by abelbraaksma** [comment]
Reading the spec again, I think it's quite explicit in making sure that newlines, unless escaped, can be treated however is needed for that platform. The ML strings are even given their possible counterparts as single quoted strings, showing the potential difference:

```toml
# On a Unix system, the above multi-line string will most likely be the same as:
str2 = "Roses are red\nViolets are blue"

# On a Windows system, it will most likely be equivalent to:
str3 = "Roses are red\r\nViolets are blue"
```

**Comment by abelbraaksma** [comment]
Posted at (almost) same time ;p

**Comment by pradyunsg** [comment]
#753 should cover this.

**Comment by eksortso** [comment]
Thanks @pradyunsg, for that, and for the separation of toml.md from the README. That's the clean break we were looking for.
