### ISSUE TITLE
Clarification: Array of tables vs Array of inline tables

### ISSUE THREAD

**Issue by CuiCui66** [toml-lang/toml#738]
The question is: Do array of tables with the `[[table]]` syntax have the same meaning as inline array of tables ?

For example: do those two documents have the same value ?
```toml 
[[table]] 
a = 42
b = "test"

[[table]]
c = 4.2
```

And

```toml
table = [ { a = 42, b = "test" }, {c = 4.2} ]
```

I expect that they have the same value but a sentence in the specification mentioning that they are indeed the same seems a good idea. In particular this sentence from the specification is problematic: 

> The last type that has not yet been described is an array of tables

It is at the beginning of the "Arrays of table" and can be interpreted to imply that an array of table is a new type that wasn't defined before and in particular that it is not the same type as the type described in section "Arrays". It would be much better to describe it as a another syntax for an existing type rather than a new type. I suppose that in TOML history table of arrays were introduced before inline arrays and so that sentence is historical.

I wouldn't mention it normally but it seems that the only test suite listed on your wiki, i.e https://github.com/BurntSushi/toml-test, does a difference between double bracket array of tables and array of inline table. The former do not have the `{type="array", ...}` marker but the latter does, and so the two documents above are parsed differently in JSON according to that test suite.

Hopefully when https://github.com/toml-lang/compliance is operational that kind of problem won't exist anymore

**Comment by ChristianSi** [comment]
Yes, array of tables and array of inline tables are two syntaxes that can be used to express the *same* data structure.

The spec already points this out, mentioning at the end of the Array of Tables section: "You may also use inline tables where appropriate". But admittedly that's not absolutely very clear. To remove any doubts, a sentence such as "Conceptually, an array of tables and an array that contains nothing but inline tables are the same thing" could be prepended before that one.

> I suppose that in TOML history table of arrays were introduced before inline arrays and so that sentence is historical.

That's indeed the case.

Maybe

> The last type that has not yet been described is an array of tables.

should be changed to something like:

> The last syntax that has not yet been described allows writing arrays of tables.

**Comment by goodmami** [comment]
I think it's worth pointing out that the two differ in what element they belong to when placed in a larger document context. The array of tables specifies its *full path* via its key, but the inline table is an element of whatever table it is in. For example, using the latest [tomlkit](https://github.com/sdispater/tomlkit/):

```python
>>> from tomlkit import loads
>>> loads('''
... [foo]
... 
... [[table]]
... a = 42
... b = "test"
... [[table]]
... c = 4.2
... 
... [bar]
... 
... table = [ { a = 42, b = "test" }, { c = 4.2 } ]
... ''')
{'foo': {}, 'table': [{'a': 42, 'b': 'test'}, {'c': 4.2}], 'bar': {'table': [{'a': 42, 'b': 'test'}, {'c': 4.2}]}}

```

Note how the inline table is under "bar", but the array of tables is not under "foo". Admittedly I found this a bit surprising, but I'm still learning the fine details.

**Comment by ChristianSi** [comment]
@goodmami Yes, names in brackets (or double brackets) are always absolute, while keys (names within a table) are always relative. The "belong to" refers to the placement or a sub-table (or sub-array) within an array of tables, see the README for examples.
