### ISSUE TITLE
Is it possible to make TOML support root value as any type?

### ISSUE THREAD

**Issue by LongTengDao** [toml-lang/toml#745]
array:

empty array:

```
[]
```

array with item(s):

```
[
  'item',# here must be at least a newline or comma inside
]
```

other types:

```
'string'
```

```
true
```

```
1
```

```
1.1
```

```
2020-01-01
```

---

risk:

1. conflict with `[]` table access in the future
2. conflict with non-value key in the future

another root assignment solution without risk above is:

```
= [] # any value type
```

which can also used to assign value to "array of tables":

```
[[array]]
key = 'value'

[[array]]
= 'value'

[[array]]
= []
```

**Comment by pradyunsg** [comment]
How's this relevant to a configuration file?

**Comment by LongTengDao** [comment]
> If you're asking for this to be added, please explain how this is relevant to a configuration file. :)

There are some config only need one value. If toml not support that, here will be some very strange `.txt` file mixed in toml files:

```
config/sites.toml
config/server.toml
config/last-modified-time.parse-to-date-time.txt
config/proxy.toml
config/pid.parse-to-integer.txt
config/paths.toml
```

**Comment by abelbraaksma** [comment]
Seems to me that such scenarios are not good candidates for toml. But if you do need them parsable as toml, do something similar as used to be done in ini files or reg files with `@default`. Just choose a single name and stick with it, so you need only one function and mapping in your code to deal with those scenarios:

```toml
# pid
default=4356
```

The advantage being that you can still use toml comments and the like. It's also possible in toml to use empty strings as keys:

```
# pid
"" = 3469
```

I think allowing the absence of keys may not be easy to express unambiguously in EBNF, and currently, it's expressly forbidden by the spec.

**Comment by pradyunsg** [comment]
TOML isn't meant for representing arbitrary data values. If someone really wants to use TOML's syntax for a document-with-one-value, it's possible to do:

```toml
value = "whatever you want"
```

I don't think we should allow anything-as-root -- the complexity this would introduce to TOML is not worth it.
