### ISSUE TITLE
Clarification: nested table dotted notation without [table] opener

### ISSUE THREAD

**Issue by mosteo** [toml-lang/toml#746]
I've found discrepancies in behavior between several parsers when confronted with:
```
[[somearray]]
one.two = false
```
but I think we can boil down the issue to simply
```
one.two = false
```
Now, my expectation was that that were equivalent to
```
[one]
two = false
```
but my experiments show the following results:
Python's TOML v0.10.0 (from PIP):
```
>>> import toml
>>> toml.loads('one.two = false')
{'one': {'two': False}}
```
Python's TOML v0.9.3 (from Ubuntu LTS 18.04)
```
>>> import toml
>>> toml.loads('one.two=false')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/toml.py", line 176, in loads
    item + "'. Try quoting the key name.")
toml.TomlDecodeError: Found invalid character in key name: '.'. Try quoting the key name.
```
npm's toml fails with (see at https://runkit.com/embed/kagrz6s6rsrf):
```
SyntaxError: Expected "=", [ \t] or [A-Za-z0-9_\-] but "." found.
```
One TOML2JSON converter using [toml.js](https://github.com/ricardobeat/toml.js) accepts it too: https://toml-to-json.matiaskorhonen.fi/

Finally, the Haskell validator at https://github.com/vmchale/tomlcheck also rejects it:
```
$ ./tomlcheck -f bad.toml 
bad.toml:2:4:
  |
2 | one.two = false
  |    ^
unexpected '.'
expecting '=' or alphanumeric character
```

In regard to TOML's [README](https://github.com/toml-lang/toml/blob/master/README.md#table), the closest example I find is
```
[fruit]
apple.color = "red"
apple.taste.sweet = true
```
but there's no example of multilevel tables without an opening `[something]`, nor an explicit statement that that's mandatory.

After writing all of that, I read in the [Changelog](https://github.com/toml-lang/toml/blob/master/CHANGELOG.md): "Clarify behavior of tables defined implicitly by dotted keys." So I guess I could find the answer somewhere in the 1.0 spec, but I'm not seeing it. I read: 
```Dotted keys define everything to the left of each dot as a table.``` that seems to imply that it should be valid, but there's no explicit example.

Looking for a clarification to determine a course of action for pmderodat/ada-toml#5

**Comment by pradyunsg** [comment]
You're using older versions of the packages on npm/PyPI, which don't implement the newer versions of TOML.

Please look at the [Wiki page](https://github.com/toml-lang/toml/wiki#implementations) for which version of TOML each implementation provides. You can cross-reference that to TOML's Changelog/version tags to see what features are available in that version of TOML.
