### ISSUE TITLE
Error in floating point section; leading zeros are allowed in exponents

### ISSUE THREAD

**Issue by JoeUX** [toml-lang/toml#747]
The Float section has this example value: `flt5 = 1e06`

The `6` at the end is highlighted in red. No explanation or comment is given.

If this was supposed to be about the leading zero, they are allowed in exponents, per the spec. Right below the example it says: "An exponent part is an E (upper or lower case) followed by an integer part (which follows the same rules as decimal integer values but may include leading zeros)."

So the red highlighting should be removed. If it's about something else, an explanation should be provided on that line as a comment, like is customary throughout the spec. I couldn't do a PR because I don't see how the red highlighting is created or removed when I tried editing the file...

**Comment by abelbraaksma** [comment]
There are more such cases, the highlighter is, I think, itself not part of the spec, and has a few bugs.

**Comment by pradyunsg** [comment]
GitHub's TOML highlighting isn't updated for TOML 1.0.0-rc1. It needs to be updated, which is tracked via #688, so I'm going to go ahead and close this issue in favor of that.

Thanks for filing this!

**Comment by JoeUX** [comment]
@abelbraaksma Yeah I noticed that date too. The spec says you can use a space to separate date and time if you want, but then it highlights that example.
