### ISSUE TITLE
TOML 1.0.0-rc2?

### ISSUE THREAD

**Issue by ChristianSi** [toml-lang/toml#750]
As v1.0.0-rc.1 was published more than 2.5 months ago and various issues have been discovered and (partially) addressed since than, I propose it's time to proceed to publishing v1.0.0-rc.2 – which might then, if we're lucky, be promoted to 1.0 Final after two more months or so.

Prior to tagging and announcing RC 2, I think the following actions are needed:

- Merge this PR:
  - [x] #743 (would fix #733)
- Decide on these open issues (close / mark them as "post-1.0"):
  - [x] #685
  - [x] #738
  - [x] #748
  - [x] #749
  - [x] #707

---

These issues should be addressed as well, but probably need not block a new RC:

* #585
* #668

**Comment by marzer** [comment]
Re #668: I took a look at the `toml.tmbundle` repo and it looks like abandonware at this point. _All_ of their repos do, actually. Lots of PRs waiting to be merged with very little activity from the maintainers. Is this _really_ where github gets their syntax highlighting juju from??

**Comment by pradyunsg** [comment]
@ChristianSi Thanks for filing this! I've taken the liberty of editing the issue description, to use it as a checklist.

I actually think that nearly all the changes flagged since 1.0.0-rc1 have been *extremely* trivial, and that we can just hop to 1.0 directly. The only blocker to us doing so is #585, which, well, is 1-weekend-of-work away from completion. :)

**Comment by ChristianSi** [comment]
@pradyunsg Wow, that was a quicker and more thorough reaction than I could have hoped for!

Since the changes since RC 1 went beyond mere typofixes, my own inclination would be NOT to jump to 1.0 final immediately, but to release an RC 2 first. If nothing (or only typos or postponable things) comes up, it could be promoted to 1.0 final after (at least) 4 weeks. What do others think?

**Comment by pradyunsg** [comment]
Hmm... I think that'll work well actually.

It's probably a good idea to run through do-a-release at least once before 1.0.0 (since that's changed with the new website) and I'll also get a bit more time to tackle #585. Consider me convinced that an 1.0.0-rc2 is a good idea. :)

**Comment by ChristianSi** [comment]
What's the status of this? Of all the tracked issues, only #685 is still open, as far as I can tell. I believe that one just needs a maintainer decision, then it could be closed quickly and the RC released...

**Comment by pradyunsg** [comment]
I'd like to add in #759 as well.

**Comment by ChristianSi** [comment]
Just a quick reminder that this needs to be released. #685 is still open, but it could be closed quickly and is not a blocker in my mind.

**Comment by ChristianSi** [comment]
What's the status of this? Any hopes of an upcoming release?

**Comment by pradyunsg** [comment]
I'm gonna be optimistic, and say that I'll do it over the weekend. :)

**Comment by ChristianSi** [comment]
Will we see an August release?

**Comment by pradyunsg** [comment]
Thanks for the nudge @ChristianSi!

I got distracted by automating the release process. 😅 On the plus since, the effort needed to make releases is super low now, now that I actually finished #764, so I have fewer reasons to be slow about this. :)

> Will we see an August release?

Yes. Once #765 merges (inputs+reviews welcome on that!), I'll cut the release.

**Comment by pradyunsg** [comment]
Done! https://github.com/toml-lang/toml/releases/tag/1.0.0-rc.2
