### ISSUE TITLE
Should floats allow omission of integer or fractional/exponent?

### ISSUE THREAD

**Issue by marzer** [toml-lang/toml#759]
I recently did a conformance pass over [toml++](https://github.com/marzer/tomlplusplus) to ensure it passed any remaining test cases from both BurntSushi's and iarna's test suites, and was surprised to find that I wasn't passing some of the floating-point tests. Specifically, I was accepting some inputs that would be valid as literals in C and C++, but are apparently not in TOML. Excerpt from my test suite before I updated it:

```c++
// omitting leading integer part
parse_expected_value(FILE_LINE_ARGS, "     .1 "sv,       .1 );
parse_expected_value(FILE_LINE_ARGS, "    +.1 "sv,      +.1 );
parse_expected_value(FILE_LINE_ARGS, "    -.1 "sv,      -.1 );
parse_expected_value(FILE_LINE_ARGS, "   .1e1 "sv,     .1e1 );
parse_expected_value(FILE_LINE_ARGS, "  .1e+1 "sv,    .1e+1 );
parse_expected_value(FILE_LINE_ARGS, "  .1e-1 "sv,    .1e-1 );
parse_expected_value(FILE_LINE_ARGS, "  +.1e1 "sv,    +.1e1 );
parse_expected_value(FILE_LINE_ARGS, " +.1e+1 "sv,   +.1e+1 );
parse_expected_value(FILE_LINE_ARGS, " +.1e-1 "sv,   +.1e-1 );
parse_expected_value(FILE_LINE_ARGS, "  -.1e1 "sv,    -.1e1 );
parse_expected_value(FILE_LINE_ARGS, " -.1e+1 "sv,   -.1e+1 );
parse_expected_value(FILE_LINE_ARGS, " -.1e-1 "sv,   -.1e-1 );

// omitting trailing fractional part
parse_expected_value(FILE_LINE_ARGS, "     1. "sv,       1. );
parse_expected_value(FILE_LINE_ARGS, "    +1. "sv,      +1. );
parse_expected_value(FILE_LINE_ARGS, "    -1. "sv,      -1. );
parse_expected_value(FILE_LINE_ARGS, "   1.e1 "sv,     1.e1 );
parse_expected_value(FILE_LINE_ARGS, "  1.e+1 "sv,    1.e+1 );
parse_expected_value(FILE_LINE_ARGS, "  1.e-1 "sv,    1.e-1 );
parse_expected_value(FILE_LINE_ARGS, "  +1.e1 "sv,    +1.e1 );
parse_expected_value(FILE_LINE_ARGS, " +1.e+1 "sv,   +1.e+1 );
parse_expected_value(FILE_LINE_ARGS, " +1.e-1 "sv,   +1.e-1 );
parse_expected_value(FILE_LINE_ARGS, "  -1.e1 "sv,    -1.e1 );
parse_expected_value(FILE_LINE_ARGS, " -1.e+1 "sv,   -1.e+1 );
parse_expected_value(FILE_LINE_ARGS, " -1.e-1 "sv,   -1.e-1 );
```
All of those representations are valid in C and C++ (and I assume other languages, too), but not legal in TOML.

Upon re-reading the TOML spec I realized that it is fairly clear that the integer part is always required (it's never subject to an _'or'_), so my knee-jerk assumption that followed the same rules as C and C++ wasn't particularly clever. Despite that, prefixing or suffixing an integer with a '.' character is a common short-hand for expressing that the value is in fact a float of some sort, and until encountering these test case violations, my assumption was that it was allowed in TOML seemed like a fairly natural one.

I guess the question is: should these representations, or some subset of them, be legal? If the answer is ultimately 'No', I think it would be wise to add a few invalid examples to the spec doc to explicitly call them out.

**Comment by ChristianSi** [comment]
The fractional part is optional if an exponent is used; the spec contains several examples of this (5e+22, 1e06, -2E-2). The trick, of course, is that the spec expects you to have a digit on both sides of the decimal dot. I believe that's pretty reasonable to keep numbers readable for "normal people" (read: non-programmers). `2.e-3` is just a less readable way of saying `2e-3`, so why not use the latter? Likewise, `.7` is a less readable way of saying `0.7`, frowned upon (= forbidden) by the spec.

In my viewpoint, these restrictions are reasonable to keep TOML files readable. TOML is not a programming language and doesn't have to support all the shortcuts (or longer cuts in the case of the unnecessary dot) sometimes used by programmers.

**Comment by marzer** [comment]
Yeah, I get _one_ of the fractional and exponent are optional. I'm only talking about both.

Certainly it is the case that my surprise at `.7` and friends being illegal was borne from my background in programming, and I have no objection to it remaining illegal in TOML. I do think a few clarifying invalid examples would go a long way, given that I'd wager a large proportion of TOML's current user base are programmers too (particularly Rust and Python). Go where the audience is, etc.

**Comment by ChristianSi** [comment]
@marzer You mean a little PR that adds some examples of things that are forbidden? That would be fine with me.

**Comment by marzer** [comment]
@ChristianSi Yup.

**Comment by pradyunsg** [comment]
> I guess the question is: should these representations, or some subset of them, be legal?

No. I think nearly all of the mentioned examples are equally (if not more) clear with a "0" in the appropriate location.

> If the answer is ultimately 'No', I think it would be wise to add a few invalid examples to the spec doc to explicitly call them out.

Please do. :)

I'd suggest keeping it very limited though -- perhaps just a single sentence + code block w/ 2 examples (one for trailing, one for leading).
