### ISSUE TITLE
Adding lower case hexadecimal digits to abnf

### ISSUE THREAD

**Issue by ju-sh** [toml-lang/toml#763]
The [abnf](https://github.com/toml-lang/toml/blob/master/toml.abnf#L238) for hexadecimal characters (`HEXDIG`) specify only the upper cased alphabets. 

    HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"

But since hex values are case insensitive, shouldn't the lower case letters also be added? 

It is mentioned that terms like `HEXDIG` are built-in and are added to the file for clarity but since they are mentioned.

Edit: [RFC5234](https://tools.ietf.org/html/rfc5234#page-14) expansion of `HEXDIG` seem to mention only the upper case letters though.

**Comment by pradyunsg** [comment]
Thanks for filing this! ABNF strings are case-insensitive, so this isn't an issue.

This exact thing has been discussed earlier in #672, so I'm gonna close this as a duplicate. :)
