### ISSUE TITLE
how to get key without section

### ISSUE THREAD

**Issue by zchong1992** [toml-lang/toml#776]
```
a=1
[section1]
b=2
c=2
```
we can use select section and key to get the value,like `section1.b` `section1.c`,but how can we get the `a` value use api?

**Comment by zchong1992** [comment]
I use  golang,without define the struct

**Comment by marzer** [comment]
@zchong1992 this repository is for the TOML _language_, not for any particular implementation. You need to find the repository or forum for your implementation and ask API questions there.

**Comment by zchong1992** [comment]
ok
