### ISSUE TITLE
ANTL4 Grammer?

### ISSUE THREAD

**Issue by cmackenzie1** [toml-lang/toml#777]
I see there is an [ABNF grammar defined](https://github.com/toml-lang/toml/blob/master/toml.abnf) - is it possible to also get an official ANTLR4 grammar?

**Comment by marzer** [comment]
I know nothing about ANTLR, so take this with a grain of salt, but could this help? http://www.robertpinchbeck.com/abnf_to_antlr/

**Comment by cmackenzie1** [comment]
Thanks for the link @marzer ! I checked it out but it doesn't seem to accept the ABNF grammar for translation.

Do you know of any tools to work with ABNF grammar? I see it is widely used in RFC specs but I can't seem to find tooling around it in Java/JVM. I could also be searching for the wrong terms... 🤔

**Comment by marzer** [comment]
> Do you know of any tools to work with ABNF grammar?

Nope, I can't help much I'm afraid. I wasn't one of the contributors to the TOML ABNF, I just googled "ABNF ANTLR" and found that link, heh.

**Comment by pradyunsg** [comment]
My understanding is that @mojombo had intended to propose TOML as an IETF standard -- which requires that the language be specified through ABNF. Translating ABNF -> EBNF and other forms is "fairly straightforward", in that they're all describing the same language/grammar, albeit with a different syntax.

I'm not aware of any tools at this time that directly translate across the syntax boundaries though, and as far as I know, a significant chunk of parser-generators use some dialect of EBNF. :)

**Comment by pradyunsg** [comment]
> is it possible to also get an official ANTLR4 grammar?

I'm gonna go ahead and say: No, not in the short term.

ABNF is _fine_ for now. While it's possible that we'd change the language we're using for the syntax spec at some point in the future, it's not going to happen in the short term (say 6-12 months, if not more).
