### ISSUE TITLE
Add option to not ignore NULL values in toml.encode

### ISSUE THREAD

**Issue by raj-manvar** [toml-lang/toml#778]
Currently if we have `test_dict = {"test_key" : None}` and do `toml.dumps(test_dict)`, dumps returns an empty string. <br> It's not always that keys with `None` values aren't required as None has it's own semantics and there could be application specific handling of None. <br> It'd be great to add a flag to not ignore that.

**Comment by eksortso** [comment]
This is, in one sense, an encoder issue, not an issue with the TOML language. I don't know which specific encoder you're using, though it resembles [`uiri/toml`](https://github.com/uiri/toml) in operation.

However, there is something about TOML configurations that you will need to adjust for: _there can be no empty-valued keys_. As of v1.0.0-rc.3, TOML does not have a data type corresponding to Python's `None`. Null values are simply not permitted, so your `test_dict` cannot be encoded to faithfully preserve a value of `None`.

**Comment by raj-manvar** [comment]
Hmm. Will work around by doing `test_dict = {"test_key" : "None" }` and then `toml.dumps(test_dict).replace('"None"', 'None')` in that case.

**Comment by eksortso** [comment]
You could do that, but just note that the result won't be valid TOML.
