### ISSUE TITLE
Hi, Does toml support normal map data struct ? like Red-Black or HashMap

### ISSUE THREAD

**Issue by ayanmw** [toml-lang/toml#779]
Does toml support normal map data struct ? like Red-Black or HashMap.

### Example
member_ages={"Tom":19, "Ann":31, "Flex": 27}

### will toml support it later? why?

**Comment by eksortso** [comment]
This project is for the TOML language and specification. We can't field questions about specific parser implementations. You'll need to find your parser's project (presumably it's a Java library?) and ask them your questions. Our [wiki](https://github.com/toml-lang/toml/wiki#implementations) may be able to help you locate the project.

**Comment by pradyunsg** [comment]
You might also find https://toml.io/en/v1.0.0-rc.3#inline-table to be relevant.

**Comment by pradyunsg** [comment]
I don't think there's anything actionable on this issue, so I'm going to go ahead and close this eagerly.
