### ISSUE TITLE
Request to add a 1.0.0-rc3 compliant toml parser to the wiki 

### ISSUE THREAD

**Issue by komkom** [toml-lang/toml#794]
Hello
This is the project I would like to add to the wiki. 
https://github.com/komkom/toml
It is compliant with the only spec test I could find from https://github.com/iarna/toml-spec-tests. 
What do you think?
Best Michael

**Comment by marzer** [comment]
Ah welcome to another implementation!

Go ahead, it's a wiki, anyone can add to it without needing any sort of approval. Just be mindful of the formatting (the implementations are in alphabetical order, I believe).

**Comment by pradyunsg** [comment]
Go ahead and create a heading for that!

**Comment by komkom** [comment]
ok thanks.
