### ISSUE TITLE
should add end mark?

### ISSUE THREAD

**Issue by Silentdoer** [toml-lang/toml#800]
usually, we add new config will add in end of config file, such as cinfig is:
name=aaa
age=9

and should add new key is gender will in
name=aaa
age=9
gender=male

 not:
name=aaa
gender=male
age=9

or not:
gender=male
name=aaa
age=9

but if origin config is:

uri=/api/test
[stud1]
name=aaa

if we add new key is timeout, we must add like this:

uri=/api/test
timeout=90
[stud1]
name=aaa

can not be:

uri=/api/test
[stud1]
name=aaa
timeout=90

so i think should add some end mark like:

uri=/api/test
[stud1]
name=aaa
<< end>>

and can add new config in end of config:

uri=/api/test
[stud1]
name=aaa
<< end>>
timeout=90

it equals:
uri=/api/test
timeout=90
[stud1]
name=aaa
<< end>>

**Comment by marzer** [comment]
This is fundamentally the same suggestion as those in #565 and #768. If you follow those discussions you'll see why TOML doesn't currently allow this and is unlikely to ever include a facility to do this.

More generally, your suggestion that new config values typically go at the end of their documents:

> usually, we add new config will add in end of config file

Simply isn't true. Config formats pretty much universally have some structure that violates that idea. In TOML this structure is provided via `[table headers]`; top-level keys go literally at the top of the file before the first header appears This keeps them grouped together visually _and_ logically.

**Comment by Silentdoer** [comment]
> This is fundamentally the same suggestion as those in #565 and #768. If you follow those discussions you'll see why TOML doesn't currently allow this and is unlikely to ever include a facility to do this.
> 
> More generally, your suggestion that new config values typically go at the end of their documents:
> 
> > usually, we add new config will add in end of config file
> 
> Simply isn't true. Config formats pretty much universally have some structure that violates that idea. In TOML this structure is provided via `[table headers]`; top-level keys go literally at the top of the file before the first header appears. This keeps them grouped together visually _and_ logically.

thank you
