### ISSUE TITLE
how would I implement a library in V?

### ISSUE THREAD

**Issue by chovy** [toml-lang/toml#804]
I'm looking to write a toml library for v (https://vlang.io)

**Comment by eksortso** [comment]
This project is for the TOML standard, which is programming language-agnostic. We do catalog various compliant parsers and such on https://toml.io, but we can't provide help for particular languages.

I'll admit I've got a passive interest in v, so I can direct you to the [V Language & Apps Discord](https://discord.com/invite/vlang), which is very active. Their community could help you get started.

**Comment by chovy** [comment]
yeah I get that but what are the parsing rules? are there any docs on writing a TOML parser?

**Comment by pradyunsg** [comment]
@chovy There's no specific docs for how to write a TOML parser.

Doing so requires the same background + information as writing a parser for any other context free grammar. A web search for "writing a language parser" seems to yield relevant results on all major search engines. :)
