### ISSUE TITLE
what's the definition when two toml config file merged to one 

### ISSUE THREAD

**Issue by gangxie112** [toml-lang/toml#823]
when merge 2 toml config file2, how to treat the fields in second one? :

1.toml:
k1=v1
[struct]
name=name1

2. toml:
k2=v2

so, in this case, we treat the k2 as a field under struct?

**Comment by marzer** [comment]
TOML files are self-contained; the notion of merging config files doesn't appear in the spec, so there's no standard way to do this. If your application needs to do this the semantics are entirely up to you.

**Comment by pradyunsg** [comment]
What @marzer said. :)

> If your application needs to do this the semantics are entirely up to you.

If your application needs to do this the semantics are chosen/decided on by the developers of application.

**Comment by marzer** [comment]
=/

"Your application" == "The application you're developing".

**Comment by gangxie112** [comment]
Not very understand, the behavior seems to be defined by viper, with the function MergeCofig/MergeInconfig?
further more, we have no way to load multiple remote configs. For example, multiple dataids of the nacos. If we implement the remote provider, there is no way to do merge. if the provider merge its self,  we have to implement most functions of the viper.

**Comment by marzer** [comment]
@gangxie112 it sounds like you're referring to a particular application or implementation; note this repository is for the TOML _language_, not any library or application that makes use of it.

**Comment by marzer** [comment]
You probably should ask here: https://github.com/spf13/viper

**Comment by gangxie112** [comment]
Oops，sorry
