### ISSUE TITLE
TestML support

### ISSUE THREAD

**Issue by felipefoz** [toml-lang/toml#825]
Hey, how you guys doing?

I've been reading about TOML and other configuration formats and a stumbled upon the TestML Project and verified that projects such as YAML [a complete test suite](https://github.com/yaml/yaml-test-suite/tree/master/test) that can be used for any programming language that wants to implement a parser. 

Have you ever considered creating those programming language agnostic tests?

Regards,

**Comment by marzer** [comment]
https://github.com/toml-lang/toml/issues/585

**Comment by pradyunsg** [comment]
Consolidating into #585.
