### ISSUE TITLE
Reading/Writing Struct into TOML

### ISSUE THREAD

**Issue by hyphen249** [toml-lang/toml#832]
### Discussed in https://github.com/toml-lang/toml/discussions/831

<div type='discussions-op-text'>

<sup>Originally posted by **joseph-pollacco** June 28, 2021</sup>
 Hi I have a large SoilWater-ToolBox model and I have got all the input parameters, Parameters, as a mutable struct. In order to create a package I will need to read the parameters outside the model as recommended in previous post as a TOML format.

**So the question is how to convert the structure into TOML?
Then how to read TOML file into a structure?**

I will be delighted if one can provide me guidance how to perform this task for example by using the simple structure:

```
mutable struct OPTION
   transpiration:: TRANSPIRATION
   soil:: SOIL 
end

mutable struct TRANSPIRATION
      Evaporation :: Bool
      Transpiration :: Bool
end

mutable struct SOIL
      Topsoil :: Bool
      Macropore :: Bool
end

# ====
Evaporation = true
Transpiration = false
transpiration = TRANSPIRATION(Evaporation, Transpiration)

Topsoil = true
Macropore = false
soil = SOIL(Topsoil, Macropore)

option = OPTION(transpiration, soil)

```
Many thanks for any help you may provide,
Joseph</div>

**Comment by eksortso** [comment]
This project is for the TOML format, for the standard, and is more or less language-agnostic. Your question is about how you would convert a Julia struct into TOML, and so is better suited to the project for that particular implementation of TOML in Julia.

**Comment by pradyunsg** [comment]
Closing since #831 already covers this, and it likely belongs on a Julia-specific communication channel as @eksortso has noted already.
