### ISSUE TITLE
TOML 1.0 implementation for PHP

### ISSUE THREAD

**Issue by Awilum** [toml-lang/toml#839]
I can't find TOML 1.0 implementation for PHP. 
Can you help me with this ?

**Comment by marzer** [comment]
There's a few pre-1.0 implementations listed on the [wiki](https://github.com/toml-lang/toml/wiki), try checking those to see if they're actually up-to-date but just not listed as such

**Comment by pradyunsg** [comment]
The Wiki has all the information
