### ISSUE TITLE
ABNF / Spec contradiction

### ISSUE THREAD

**Issue by epage** [toml-lang/toml#843]
The webpage says
> Control characters other than tab (U+0000 to U+0008, U+000A to U+001F, U+007F) are not permitted in comments.

While the ABNF says
```
non-eol = %x09 / %x20-7F / non-ascii

comment = comment-start-symbol *non-eol
```

Note the `7F`, it should be `7E`

**Comment by eksortso** [comment]
You're not looking at the most recent commit. This was already corrected. Later versions will include the correction.

**Comment by epage** [comment]
Thanks, I was just going off what the website linked me to (and didn't see any existing issues).  I'll start tracking master now.
