### ISSUE TITLE
Explanation on the purpose of date(and/or time) data types?

### ISSUE THREAD

**Issue by WhyIsEvery4thYearAlwaysBad** [toml-lang/toml#855]
I am confused why date and time data types are in the TOML language, and there is no obvious explanation that I can find on the [TOML home page](https://toml.io/), github page, or anywhere online.

**Comment by pradyunsg** [comment]
Closing since @marzer answered it. :)

**Comment by WhyIsEvery4thYearAlwaysBad** [comment]
@marzer Thanks. I see why datetimes are in TOML now, and I want them to continuing being in the spec.

Although I wish the reasons were explicitly displayed.

**Comment by StephenCleary** [comment]
Is there a working link to this discussion?
