### ISSUE TITLE
How to slove ''\n parse to '''?

### ISSUE THREAD

**Issue by linglaiyao1314** [toml-lang/toml#857]
this is my raw toml file content:
`sql_template = """
    select * from xxx
    where eventvalue2 != ''
    and a != 0
    """ `

after load, value become: 
`
{'sql_template': "    select * from xxx\n    where eventvalue2 != '''    and a != 0\n    "}
`
the eventvalue2 != '' become eventvalue != '''

**Comment by marzer** [comment]
Seems like a parser bug. Which language/TOML parser library are you using?

You could try using a _literal_ (i.e. single-quoted) multi-line string instead:
```
sql_template = ''' select * from xxx where eventvalue2 != '' and a != 0 '''
```
Having the two single quotes inside the single-quoted multi-line string is OK; it's only when you have _three or more_ that it's a problem. If that doesn't work for you, consider filing an issue on the repository for the TOML parser you are using (this is the repository for the TOML language, not any particular implementation).

**Comment by linglaiyao1314** [comment]
> If you truly do not have any newlines in the TOML and it's adding them for you then it's a parser bug. Which language/TOML parser library are you using?
> 
> You could try using a _literal_ (i.e. single-quoted) multi-line string instead:
> 
> ```
> sql_template = ''' select * from xxx where eventvalue2 != '' and a != 0 '''
> ```
> 
> Having the two single quotes inside the single-quoted multi-line string is OK; it's only when you have _three or more_ consecutively that it's a problem. If that doesn't work for you, consider filing an issue on the repository for the TOML parser you are using (this is the repository for the TOML language, not any particular implementation).

Thanks your reply ! I use the python library to parser , library version is: **toml==0.10.0**
if i don't put  '' or ""  at the end of the line, not error raise。add a \ at the end of the line is also available, now I use the latter method, because mysql sql_template param is very long.

**Comment by marzer** [comment]
Ok, so if I understand you correctly, you're using `\` to split the milti-line string over multiple lines in your config? If so, you should have posted _that_ in your issue, not the edited version above. To be sure, can you please post your TOML file _exactly_ as it appears, _with zero edits at all_, in this thread?

**Comment by linglaiyao1314** [comment]
> Ok, so if I understand you correctly, you're using `\` to split the multi-line string over multiple lines in your config, because otherwise it was one very long query and too hard to read? If so, you should have posted _that_ in your issue, not the edited version above. To be sure, can you please post your TOML file exactly as it appears, **without editing it at all** (except to remove sensitive information like passwords etc), in this thread?

Ok, my original toml file is: 
``
```
```

**Comment by marzer** [comment]
Yup, there's nothing wrong that TOML - this is definitely a bug in the parser. I just checked out the repo for the TOML lib you're using, [uiri/toml](https://github.com/uiri/toml), and it seems it's two versions ahead of the one you're using, so consider updating, and/or filing a bug report there.

Alternatively, you could try using [pytomlpp](https://pypi.org/project/pytomlpp) or [tomli](https://pypi.org/project/tomli/) - both are known to be TOML 1.0.0 compliant (and much faster than the one you're using).

**Comment by pradyunsg** [comment]
Closing this since this is a parser issue; not a standards issue.
