### ISSUE TITLE
Inconsistenty between spec and BNF

### ISSUE THREAD

**Issue by sheepduke** [toml-lang/toml#862]
Hi folks, I have found a place where the spec and BNF are inconsistent.

The spec explicitly declared that:

> An exponent part is an E (upper or lower case) followed by an integer part (which follows the same rules as decimal integer values but may include leading zeros).

But in the BNF it is declared as:

```abnf

exp = "e" float-exp-part
float-exp-part = [ minus / plus ] zero-prefixable-int
```

Is there a missing `E` case in BNF definition here?

**Comment by eksortso** [comment]
No, because this is actually ABNF, which is case-insensitive by default. The `"e"` in the spec picks up `E` as well as `e`.

**Comment by pradyunsg** [comment]
See #763 and #672, where this has been brought up before.
