### ISSUE TITLE
TOML parser in C without stdlib

### ISSUE THREAD

**Issue by amyipdev** [toml-lang/toml#863]
Hello!

Are there any parsers for TOML written in C that don't use the standard library? I don't have standard library access in my development environment (with the exception of allocator functions).

**Comment by eksortso** [comment]
This is the repo for the TOML standard. We have a [wiki page](https://github.com/cktan/tomlc99) where we maintain a list of parsers by language, but it's not a comprehensive list. We would certainly welcome contributions to that list, but it will always be incomplete.

As of now, the wiki lists three C-based parser projects, one of which ([cktan/tomlc99](https://github.com/cktan/tomlc99)) is v1.0.0-compliant. At first glance, it appears to use `stdlib`. I don't know whether it could be adapted to work without the library, but you could see how far you can get with it. Make sure to check the others too, if you haven't already.
