### ISSUE TITLE
abnf grammar has incorrect line endings

### ISSUE THREAD

**Issue by bendyarm** [toml-lang/toml#873]
The file `toml.abnf` uses LF between lines.  
The abnf spec requires CRLF between lines:  
https://datatracker.ietf.org/doc/html/rfc5234#section-2.2  
(Some checkers and consumers of abnf grammars permit LF instead, but that is off-spec.)  
I will also submit a PR for this issue.

**Comment by pradyunsg** [comment]
Fixed in #876.
