### ISSUE TITLE
Documentation is ambiguous about tab `\t` in single-line basic strings

### ISSUE THREAD

**Issue by abravalheri** [toml-lang/toml#877]
Hello, I was just reading the [spec](https://toml.io/en/v1.0.0#string) in the website and I noticed that the docs are ambiguous about tab being required or not to be escaped in single-line basic strings. Specifically, it states:

```
Basic strings are surrounded by quotation marks ("). Any Unicode character may be used except those that
must be escaped: quotation mark, backslash, and the control characters other than tab (U+0000 to U+0008,
U+000A to U+001F, U+007F).
```

So according to the text, tab characters don't need to be escaped.

However, the very next example, shows tabs being escaped:

```
str = "I'm a string. \"You can quote me\". Name\tJos\u00E9\nLocation\tSF."
```

Am I correct to assume that the text + example implies that `\t` chars *don't have to* be escaped, but *can*?

I had a quick look in the ABNF and I have the impression that tabs need to be escaped, but I might be wrong interpreting the ABNF...

**Comment by pradyunsg** [comment]
What @frostming said! :)

Tab is allowed both as a tab character, as well as in an escaped format.
