### ISSUE TITLE
Tagged String Literals

### ISSUE THREAD

**Issue by guybedford** [toml-lang/toml#883]
A common pattern in Markdown is the syntax highlighting code block via:

```
  ```markdown
  # This is markdown
  (\)```
```

To support a similar pattern in TOML, the `"""` and `'''` strings could be permitted as tagged via `tag"""` and `tag'''`, both of which are currently syntax errors so can be supported in a backwards-compatible way.

When parsing, the result could be a dictionary of type `{ tag, literal }`, or alternatively a tuple or similar dictionary format.

For example permitting TOML like:

```
docs = markdown"""
# This is markdown
"""
```

The primary benefit would be in editors and viewers of TOML in supporting well-known tags such as syntax languages to allow internal string syntax highlighting and validations.

I did not see this discussed anywhere else, but it would be a great feature to extend the possibilities of the language.

**Comment by pradyunsg** [comment]
Hi, thanks for the proposal!

In markup languages, those are "code blocks" so it is a safe assumption that things contained within would be valid code. I don't think that's common or even a valid assumption with strings in a configuration language and I don't think designing for syntax highlighting in a tiny subset of potential usecases is worthwhile. I also don't think it's common enough to embed code in a multiline string, in a configuration file, in a manner where getting syntax highlighting for it is particularly valuable. It's also unclear what this would decode as.

Overall, I don't think this would be generally applicable enough to justify adding this.

**Comment by guybedford** [comment]
@pradyunsg a good example would be bash scripts with something like GitHub actions YAML files. For my use case I'm actually building a task runner with JS snippets where first-class code highlighting would be highly beneficial. For other use cases one can imagine markdown or any other embedded language. I wouldn't outright dismiss the use case.
