### ISSUE TITLE
Proposal: Freeze the spec

### ISSUE THREAD

**Issue by hukkin** [toml-lang/toml#886]
Firstly, even though the title may seem somewhat radical, this issue is merely to raise some initial discussion. I'm not yet even sure what my own stance is regarding this :smile:

Based on its wide adoption, TOML seems like a useful language as it is today. Most feature proposals I see in this issue tracker don't seem nearly as universally useful as the features TOML (v1.0.0) already ships with.

Back incompatible changes could be devastating to TOML consumers, but even non-breaking changes have some breaking effects unless consumers pin a TOML spec version.

An example from the Python ecosystem: the pyproject.toml file is shared by countless build (and other) tools. If one these tools decides to include newer TOML syntax in the shared file, and other tools use an incompatible older parser, there will be breakage. This is true even if the TOML syntax used was "backwards compatible". Arguably, yes, this is the Python ecosystem's fault for [not pinning TOML version](https://discuss.python.org/t/9031). However, with a frozen spec, e.g. JSON, this would be a non-concern.

As mentioned, JSON is more or less a frozen spec, and that's quite handy: other specifications relying on it can simply refer to JSON instead of JSON v1.3.2. Do we want TOML to have the same property?

**Comment by pradyunsg** [comment]
> Do we want TOML to have the same property?

I don't, no.

I don't imagine we'd be making a 2.0 release anytime soon (I won't say never, but that's pretty close). Until then, at best, we'd allow more syntax to be valid (eg: multiline inline tables). The bar for that though, will stay pretty high so I don't think "freezing" the spec makes much sense.
