### ISSUE TITLE
Feature request: Open TOML file on AWS S3 bucket

### ISSUE THREAD

**Issue by gcaria** [toml-lang/toml#892]
It seems that toml files located on a AWS S3 bucket can't be read:
```python
import toml
toml.load('s3://path/to/toml')

FileNotFoundError: [Errno 2] No such file or directory: 's3://path/to/toml'
```

Could this be implemented?

**Comment by marzer** [comment]
This is the repository for the TOML _language_, not any particular implementation.

Looks like you want [uiri/toml](https://github.com/uiri/toml).

**Comment by gcaria** [comment]
My bad sorry, I'll close this then.
