### ISSUE TITLE
Allow `:` for assignment inside inline tables

### ISSUE THREAD

**Issue by lizelive** [toml-lang/toml#901]
```toml
hello = { world : 42 }
```

should be equivalent to

```toml
hello = { world = 42 }
```

this synergies with #516 and #902 to make all json objects that don't include null valid toml.

pros:
1. paste json
2. easier to move over to toml
3. more choice
4. more readable

**Comment by pradyunsg** [comment]
> make all json objects that don't include null valid toml.

This isn't a goal.
