### ISSUE TITLE
Lack of Offset Time

### ISSUE THREAD

**Issue by linclelinkpart5** [toml-lang/toml#905]
Was wondering why TOML does not support the combination of a Local Time + Offset? Does it not make semantic sense, or is there another reason for excluding it?

**Comment by eksortso** [comment]
@arp242 Initially I was confused but then realized that your example makes more sense if you had said `20:00:00-08:00` instead. I did understand your point though.

@linclelinkpart5 Did we answer your question? If so, please close the ticket, and if not, please follow up.
