### ISSUE TITLE
ERC20

### ISSUE THREAD

**Issue by Bigboy1982** [toml-lang/toml#906]

**Comment by marzer** [comment]
Crypto spam, really?

**Comment by Bigboy1982** [comment]
Í have no idea what I'm doing

**Comment by Bigboy1982** [comment]
I'm trying to get some assets to my wallet

**Comment by marzer** [comment]
Well opening random issues on github repositories that have nothing to do with crypto isn't the way to do it, champ. All that's going to do is piss people off. Suggest you take it to twitter or something.

**Comment by Bigboy1982** [comment]
Ok I'm from Iceland.. and my English is not the best.. what can I do

**Comment by Bigboy1982** [comment]
I'll stop doing and not knowing what I'm doing

**Comment by arp242** [comment]
> Well opening random issues on github repositories that have nothing to do with crypto isn't the way to do it, champ. All that's going to do is piss people off. Suggest you take it to twitter or something.

So he can piss people off on Twitter? 😂 Then again, everyone always seems angry by default on Twitter, so...

**Comment by pradyunsg** [comment]
Closing since this is off topic.
