### ISSUE TITLE
Clarify which control characters are allowed in comments

### ISSUE THREAD

**Issue by autumnull** [toml-lang/toml#934]
Currently the spec says this:

> Control characters other than tab (U+0000 to U+0008, U+000A to U+001F, U+007F) are not permitted in comments.

However there are more control codes than just those listed in parentheses - namely the ones listed above cover the C0 control code range, but there are also the [C1 control codes](https://en.wikipedia.org/wiki/C0_and_C1_control_codes#Unicode) (U+0080 to U+009F), which are valid unicode. It is unclear from the specification whether the C1 codes are allowed to be present in comments or not.

**Comment by arp242** [comment]
There's an open PR/discussion for this: https://github.com/toml-lang/toml/pull/924

**Comment by arp242** [comment]
I think this can be closed now that #924 is merged?

**Comment by autumnull** [comment]
yes
