### ISSUE TITLE
Clarify whether hex digits can be lowercase or not

### ISSUE THREAD

**Issue by autumnull** [toml-lang/toml#935]
From the prose spec:
> Hex values are case-insensitive.

From the ABNF grammar:
```abnf
HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"
```

**Comment by marzer** [comment]
ABNFs aren't case sensitive. Lowercase hex digits are fine.

**Comment by autumnull** [comment]
you're right, my bad
