### ISSUE TITLE
[Proposal] Allow apostrophe escaping in inline literal strings

### ISSUE THREAD

**Issue by Keyacom** [toml-lang/toml#949]
## Preface

Allow apostrophe escaping in inline literal strings.

## Why

The YAML specification nicely allows `'` to be placed inside a raw string by preceding it with itself:
```yml
ParsedString: "Emma's boyfriend is nice."
RawString: 'Emma''s boyfriend is nice.'
```
When fed to a YAML parser, both `ParsedString` and `RawString`'s values will be the same.

TOML does not allow that within the current specification. I am proposing this, so you won't need to create a multiline literal string just to include an apostrophe in it.

## Questions

You can ask more below!

### Why not `\'` instead of `''`?

This could be influenced by how Ruby parses raw strings, but I don't want that because of the potential for ambiguous behavior of `\`, which could be a potentially breaking change.

**Comment by marzer** [comment]
> When fed to a YAML parser [...] 

In general I think where YAML chooses to do one thing, it would be to the betterment of TOML health to explicitly _not_ choose to do that thing. There's just [far too much magic](https://noyaml.com/) in YAML. This is a good example; why add this magic when there's already two good alternatives that don't introduce unexpected behaviour? A double-quoted string would accept your example text verbatim without issue. More complex examples can use a ML literal string.

**Comment by eksortso** [comment]
To illustrate @marzer's point, here are two ways to state the string `Emma's boyfriend is nice.` in TOML without having to escape the apostrophe.

```toml
ParsedString = "Emma's boyfriend is nice."
RawString = '''Emma's boyfriend is nice.'''
```

The `RawString` example uses multi-line literal string syntax (three single-quotes on each side). Within them, you can use apostrophes, or even literal pairs of apostrophes, freely.

The website [toml.io](https://toml.io) even mentions this explicitly in its quick tour:

> Since there is no escaping, there is no way to write a single quote inside a literal string enclosed by single quotes. That's where **multi-line literal strings** come in:

though that site doesn't actually use an example like this. I'll run this past them.

**Comment by arp242** [comment]
> Edit: also worth noting that this would be a backwards-incompatible change; merely updating the TOML spec version of a parser would change the way a literal string featuring '' was parsed. There's a lot of TOML out in the world already.

This isn't a concern since `''` is only parsed inside `'..'`-delimited strings; so just `''` is still an empty string. For example in SQL:

```
(1)=# select '', '''';
 ?column? │ ?column?
──────────┼──────────
          │ '
```

Not saying I'm in favour of this proposal, just pointing out it is backwards-compatible as far as I can see.

**Comment by marzer** [comment]
> This isn't a concern since '' is only parsed inside '..'-delimited strings; so just '' is still an empty string. For example in SQL:

This is true for single quote strings (since it is currently impossible to form a single-line literal string containing `''` without delimiting the string itself), though my line of thought was w.r.t multi-line literal strings. The sensible assumption would be that this escaping, if adopted, be extended to those as well (otherwise it would introduce an internal inconsistency that would be, er, _very dumb_), but then that means existing ML literal strings can change meaning:

```toml
quotes = '''''''' # '' before this proposal, ' after it
```

**Comment by arp242** [comment]
I assumed that `''`-type escapes wouldn't take effect in triple-quoted strings, as there's no real need for it. (`''' ' '''` is already valid).

**Comment by eksortso** [comment]
@Keyacom Have we sufficiently addressed the issue that your proposal was attempting to address? If so, please close this issue. If not, please give us more details to make your case for the proposal.

**Comment by Keyacom** [comment]
A summary, so everything about my proposal is clear:
- `''` (double apostrophe) is embeddable in single-line raw strings, and only works there.
- `'` (single apostrophe) still allowed by itself in multiline raw strings.
Example:
```toml
[example]
same-texts = [
  'Maya''s boyfriend',
  "Maya's boyfriend",
  '''Maya's boyfriend''',
]
```
When reading according to the new specification (Python example):
```py
import tomllib # assume it's updated already

with open("example.toml", "rb") as file:
    l = tomllib.load(file)['example']

assert all(e == l[i+1] for i, e in enumerate(l[:-1]))
```

**Comment by Keyacom** [comment]
I think I'm going to close this proposal due to the criticism it gathered.
