### ISSUE TITLE
Does time need to be < 24h? (use case: elapsed time)

### ISSUE THREAD

**Issue by silverhook** [toml-lang/toml#952]
I have a use-case where I want to log how much time something took.

In that case should I use the (local?) **time** type? Which may be against the (local) time type intention.

```toml
time = 342:12:29
```

or do I need to declare it as a **string**? Which is just very confusing since there is also a time type (and it is OK if you use it within the range of 24h).

```toml
time = "342:12:29"
```

**Comment by marzer** [comment]
Yes, the Time time in TOML is a time _point_, as in, a time of day (or a time of day at a specific date for the full Date-Time formats).

What you're asking for is a Duration type; there's a proposal to add one to the language here: https://github.com/toml-lang/toml/issues/514

**Comment by silverhook** [comment]
Ah, thanks. I searched before and at a very lazy look that issue did not seem the same, but you’re right.

I’m closing this issue in favour of #514 then.

**Comment by marzer** [comment]
If you're not too interested in down-to-the-nanosecond precision, a user-friendly workaround for this is to simply use a float, e.g.

```toml
timeout_minutes = 2.5 # 2 min 30 sec
```

**Comment by silverhook** [comment]
@marzer That’s a good option, thanks. But my use case is at the same time kinda niche and silly, and not really that important – I use TOML to keep my highscores and [a few games record also how much time something took](https://matija.suklje.name/hooks-highscores#crimzon-clover-world-explosion).

I decided to just save it as a string for now.

**Comment by marzer** [comment]
Ah yup, in that case you'd definitely want precision, lest you incur the wrath of angry players :D
