### ISSUE TITLE
[Proposal] Better raw string quoting

### ISSUE THREAD

**Issue by Keyacom** [toml-lang/toml#962]
The follow-up proposal to #949.

A similar thing is done in Markdown (both for inline code and code blocks):
````````markdown
<!-- This allows to include ``` inside a code block. -->
````markdown
```py
print("Hello world!")
```
````
````````
And also in Rust, which only allows double quotes for strings:
```rs
let s: &'static str = r"Does not allow quote marks!";
let s: &'static str = r#"Allows for a quote mark ("), but not for a quote-and-hash combo"#;
let s: &'static str = r####"The number of hashes (###) must be less than in the delimiter to include in the raw string when preceeded by a quote mark"####;
```

Personally, I think Rust's system of raw strings is better because this doesn't employ any sort of leading/trailing whitespace detection by just disallowing `#` counts (only if immediately followed by `"`) longer than in the delimiter.

Instead of just allowing multiple single quotes (which could be more breaking than what I'm proposing), use the `$` character (this is NOT yet final) instead of Rust's `#`, which is used in TOML for comments. Any character that is not yet defined in TOML's grammar could be allowed, or we could settle on just one. Best if we avoid alnum and any of `#[].{},\=_-"'+`, which are defined in the TOML grammar.

Examples:
```toml
# Hypothetically, after accepting this
# proposal (assuming we settled on "$")
[strings]
q = [
  'does not allow single quotes inside',
  $'allows single quote: ''$,
  $$'allows single quote followed by a dollar sign: '$'$$,
  $$$$$'allows single quote followed by up to four dollar signs: '$$$$'$$$$$,
]
```

**Comment by arp242** [comment]
I wouldn't be in favour of your previous `''` proposal, but I'd be okay with it landing in TOML too. As someone who typically prefers using `'` I can see how it's useful, I just don't think it's useful enough to warrant adding it.

But I would *definitely* not be in favour of an entire new string delimiter, and I feel much stronger about this than your `''` proposal. It's very non-obvious, and I don't really see what the problem of using `".."` or `''' .. '''` is? It doesn't strike me as that much harder to type or read.

TOML stands for "Tom's Obvious, Minimal Language"; this is neither "obvious" or "minimal".

**Comment by marzer** [comment]
> I don't really see what the problem of using ".." or ''' .. ''' is? It doesn't strike me as that much harder to type or read.

This was my main issue with #949, and remains here too. @Keyacom what is the underlying reason behind you wanting to change TOML's strings to match other languages? Is there some real use-case you have that is currently very unweildy/impossible, or is it just window-shopping?

**Comment by pradyunsg** [comment]
I don't think adding more complexity to the way TOML handles strings is going to fly. None the less, having a real-world example demonstrating the situation where this would be helpful is definitely necessary for any sort of progress to be made in the direction of adding yet-another-way to do this.

**Comment by Keyacom** [comment]
> This was my main issue with #949, and remains here too. @Keyacom what is the underlying reason behind you wanting to import additional string syntaxes from other languages? Is there some real use-case you have that is currently very unweildy/impossible, or is it just window-shopping?
> 
> If you can demonstrate some real-world TOML that would be obviously improved* by these proposals you may have more success. Synthetic examples don't really have the same impact.

Okay, so here would be my list of example use cases. Currently, TOML does not allow inline raw strings with an apostrophe and multiline raw strings with `'''`. My proposal would fix this problem, which was also addressed during my previous proposal.

```toml
[tests]
# Allow an inline raw string with an apostrophe
# All of the below are valid and resolve as the same string
single-line = [
  "Maya's boyfriend",
  '''Maya's boyfriend''',
  $'Maya's boyfriend'$,
]
# Allow a multiline raw string with an apostrophe
# Both of the below are valid and resolve as the same string
python-injected-docs = [
  """r'''
  This function does many things on its own.
  
  For example, it can break regexes, like /[^\\S\\n]/.
  
  :raises TypeError: on random occurrences
  '''""",
  $'''r'''
  This function does many things on its own.

  For example, it can break regexes, like /[^\S\n]/.
  
  :raises TypeError: on random occurrences
  ''''''$,
]
```

**Comment by marzer** [comment]
If you're injecting python docs based on some TOML configuration, why require the TOML to have the python-side  `'''` at all? Can't the code generator just add those itself? That seems a far more obvious and user-friendly solution.

**Comment by pradyunsg** [comment]
I'm going to go ahead and say that we're not going to be adding more complexity to the language's string handling to cover such use cases. They're covered well-enough already and the current constraints of TOML pushes configuration designers in the right directions.

**Comment by pradyunsg** [comment]
Thanks @Keyacom for filing this issue!
