### ISSUE TITLE
Dump Multiline string to toml file

### ISSUE THREAD

**Issue by reisenmachtfreude** [toml-lang/toml#968]
How can I dump an multi-line string to a toml file?
My approach was:
```
mystr = """Some
content"""
with open('dump.toml', 'w') as f:
  toml.dump({'content' : mystr}, f)
```
Expected output in toml file:
```
mystr="""Some
content"""
```

However, the content was automatically converted to a single line string
`mystr="Some\\ncontent"`

Is there any code which helps to reach my expected result?

**Comment by marzer** [comment]
This is the repository for the TOML _language_, not any particular implementation. You'll need to find the github or package repository for tthe implementation you're using and ask your question there.

Looks like python, might be one of:
- []()
- - []()

**Comment by reisenmachtfreude** [comment]
Great! Thank you very much!
