### ISSUE TITLE
Multiline literal string clarification

### ISSUE THREAD

**Issue by englercj** [toml-lang/toml#974]
Have a quick clarifying question. I'm confused by the multiline literal section which says:

> You can write 1 or 2 single quotes anywhere within a multi-line literal string, but sequences of three or more single quotes are not permitted.

But then provides an example of a valid string which seems to do exactly what this sentence says is disallowed:

```toml
# 'That,' she said, 'is still pointless.'
str = ''''That,' she said, 'is still pointless.''''
```

I'm not clear why the closing four quotes of this line are valid, considering the language of the spec as quoted above. Currently my parser rejects this line because it sees 3 quotes and closes the string, then gives an error about the fourth orphaned quote.

If one or two single quotes (but not three) are allowed within the string, next to the closing three quotes, would this also be valid?

```toml
str = ''''That,' she said, 'is still pointless.'''''
```

Should I only reject this if there are six trailing quotes?

```toml
str = ''''That,' she said, 'is still pointless.''''''
```

(GitHub sure seems to think so, and the abnf seems to agree. Maybe I just misread.)

**Comment by marzer** [comment]
> I'm not clear why the closing four quotes of this line are valid

Because if you interpret the trailing three to be the closing delimiter, the first leading quote is simply an isolated single quote. This requires your parser to look ahead when it sees consecutive single-quotes and only take the trailing three, rather than completing the string immediately when it sees \*just\* three.

**Comment by englercj** [comment]
Thanks for the clarification!
