### ISSUE TITLE
rust workspace version reference generates a problem in vs code

### ISSUE THREAD

**Issue by softstream-link** [toml-lang/toml#976]
[package]
name = "blah"
version.workspace = true

results in this error
Expected "=", [ \t] or [A-Za-z0-9_\-] but "." found.

**Comment by marzer** [comment]
This is not the right place to report this - this repository for the TOML langauge, not any particular implementation or application. You need to find the repository for the software you're using and report it there instead.

If this is for rust's cargo, you should try here: https://github.com/rust-lang/cargo
