### ISSUE TITLE
Is the order of elements within arrays strict?

### ISSUE THREAD

**Issue by Raildex** [toml-lang/toml#991]
When Application `A` writes a TOML that contains an array, and Application `B` reads that TOML, is the order of the elements guaranteed to be the same?

The spec does not say anything about how parsers should parse arrays.

I imagine a parallel parsing that partitions the raw TOML and puts them into the parsed result in any order.

**Comment by marzer** [comment]
Yes, order will be preserved.

The preservation of order of elements in an Array is one of the defining characteristics of it being an Array at all; if the order was lost, then it's not an array.

Any parser/serialiser that does not maintain that invariant is bugged.
